### ISSUE TITLE
Question: gmi model creation API

### ISSUE THREAD

**Issue by zhang-alvin** [SCOREC/core#100]
Is there an API that allows the user to create actual model entities (i.e. create model vertex with ID 20 that has coordinates (x0,y0,z0)?

I expected to find such a function in [gmi_load](https://github.com/SCOREC/core/blob/e0103960beeebf7b449788272b0cccca7aa037c3/gmi/gmi.c#L191 ). It looks like it loops over all of the available extensions (from gmi_register) and then if the filename you provided matches one of those extensions, the filename is passed into a member of the creator structure, namely gmi_creator f, which takes in a filename as input and returns a gmi_model*. But I don't see any code associated with what gmi_creator does. I was expecting a loop that looks at each line in the file and creates the corresonoding model entity. What am I missing?

**Comment by ibaned** [comment]
The creation / manipulation API is this "agm" thing:

https://github.com/SCOREC/core/blob/master/gmi/agm.h

The built-in implementations start with `gmi_base`, which holds some stuff that is common between the analytic and `.dmg` backends:

https://github.com/SCOREC/core/blob/master/gmi/gmi_base.c

Here is the code that actually reads a `.dmg` file and builds the entities using `agm`:

https://github.com/SCOREC/core/blob/master/gmi/gmi_file.c#L52

The analytic model implementation is here:

https://github.com/SCOREC/core/blob/master/gmi/gmi_analytic.c

**Comment by zhang-alvin** [comment]
Thanks, this is sufficient information for what I need.
