### ISSUE TITLE
simmetrix discrete APIs

### ISSUE THREAD

**Issue by yangf4** [SCOREC/core#101]
I don't know if anyone uses simmetrix discrete APIs. I might be the only person using this. 

But still, I add SimDiscrete library here:
https://github.com/SCOREC/core/blob/1ee2654285d6e9283ec0016fbbe95bcd5211ee31/cmake/FindSimModSuite.cmake#L122

@cwsmith  Please let me if you are OK or not with this.

**Comment by cwsmith** [comment]
Where are the SimDiscrete APIs being used?

**Comment by yangf4** [comment]
Right now, yes. This is the only place using SimDiscrete. But in the future, chef may use this too.

**Comment by yangf4** [comment]
wrap is here:
https://github.com/SCOREC/core/commit/4944146dd1b083224ccf3f450ff8c14dd69e3d8e

**Comment by cwsmith** [comment]
Ideally, if/when it is added to chef it'll be optional.

**Comment by yangf4** [comment]
OK. I see. I will close this for now. If you have any concern about this, please feel free to reopen it.
