### ISSUE TITLE
several tests fail when SIM_PARASOLID=OFF and SIM_ACIS=OFF

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/core#105]
On pachisi, using core/develop, simModSuite 11.0-170427dev, the modules:
```
module load \
cmake/latest \
mpich3/3.1.2-thread-multiple \
parmetis/mpich3.1.2/4.0.3 \
zoltan/mpich3.1.2/3.81 \
simmetrix/simModSuite
```
and the following cmake command:
```
cmake ../core -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx \
-DCMAKE_Fortran_COMPILER=gfortran -DSCOREC_CXX_OPTIMIZE=on \
-DMDS_ID_TYPE=int -DPCU_COMPRESS=ON -DENABLE_ZOLTAN=ON \
-DPUMI_FORTRAN_INTERFACE=on -DENABLE_OMEGA_H=OFF -DIS_TESTING=ON \
-DENABLE_SIMMETRIX=ON -DSIM_MPI=mpich3.1.2 -DSIM_PARASOLID=OFF -DSIM_ACIS=OFF \
-DMESHES=/lore/cwsmith/geometries/pumi-meshes/ 
-DCMAKE_INSTALL_PREFIX=/lore/cwsmith/develop/build-jessie-core-sim-on/install
```

Building, then running ctest, results in:
```
91% tests passed, 9 tests failed out of 95

Total Test time (real) =  39.74 sec

The following tests FAILED:
	 16 - migrate_interface (Failed)
	 17 - dg_ma_test (Failed)
	 18 - chef-BL_query (Failed)
	 20 - ph_adapt (Failed)
	 31 - convert_2d_quads (Failed)
	 32 - convert_2d_tris (Failed)
	 33 - verify_2nd_order_shape_quads (Failed)
	 34 - verify_2nd_order_shape_tris (Failed)
	 62 - simZBalance_4 (Failed)
Errors while running CTest
```

If `SIM_PARASOLID` and `SIM_ACIS` are set to `ON`, all tests pass.  

`migrate_interface` fails in the simModSuite `GM_Load` call.  I suspect this is a problem with the linking order.

**Comment by KennethEJansen** [comment]
I can also add the phastaChef fails and probably all chef runs that attempt to do an adaptation while using a dmg file.

I don’t have the time to trace back when this change happened but my limited knowledge of  this part of the code says that setting in.transferParmetric=1 
as a default seems guaranteed to break dmg adapt.  Here is a simple diff of what restored it back to working

diff --git a/phasta/phInput.cc b/phasta/phInput.cc
index 4148ad4..c7c2ea6 100644
--- a/phasta/phInput.cc
+++ b/phasta/phInput.cc
@@ -52,7 +52,7 @@ static void setDefaults(Input& in)
   in.restartFileName = "restart";
   in.phastaIO = 1;
   in.snap = 0;
-  in.transferParametric = 1;
+  in.transferParametric = 0;
   in.splitAllLayerEdges = 0;
   in.filterMatches = 0;
   in.axisymmetry = 0;
lines 1-13/13 (END)

---------------------------------------------------------------- 
Kenneth E. Jansen, Professor 
Ann and H.J. Smead Department of Aerospace Engineering Sciences
ECAE 161                                   OFFICE (303) 492-4359 
429 UCB                                      FAX  (303) 492-4990 
University of Colorado at Boulder          jansenke@colorado.edu 
Boulder, CO, 80309-0429        http://www.colorado.edu/aerospace 
----------------------------------------------------------------

**Comment by mortezah** [comment]
31 and 32 should not be added to the tests when SIM_PARASOLID is off (they use native models). I will take care of that part. 

16 and 17 fail because the box.smd in this folder here https://github.com/SCOREC/pumi-meshes/tree/master/phasta/dg is missing the corresponding native file (I guess! Because I can not load that model into simmodeler either).

**Comment by mortezah** [comment]
convert_2d_{quads, tris} won't be added to tests if PARASOLID=off as of bedfefb57 

I should have mentioned #105 in my commit but I forgot ;)

**Comment by yangf4** [comment]
the native model is missing for the dg interface related tests. I make some change https://github.com/SCOREC/core/commit/43a7b437674db91b02208f78631324ba4b1d8cba so they won't run if PARASOLID is off (for now). I may find that native model or add a new one instead.

**Comment by mortezah** [comment]
@ibaned, it seems that you added the test simZBalance_4, which fails when PARASOLID is OFF. Is that the expected behavior?

**Comment by ibaned** [comment]
1. Do we actually have a use case for Simmetrix without Parasolid?
2. Failure when Parasolid is not present is a function of the model, not of the test. If the model is `.x_t` or `.xmt_txt`, then it will definitely fail. If the model is `.smd` and is not a translated model, then I'm not sure exactly what Simmetrix's failure modes are, but chances are it could fail. The `annular.smd` file sure seems to be a reference for a Parasolid model, so its likely to fail. I recommend asking Simmetrix about how well they expect things to work with this kind of model when Parasolid isn't around.

Overall, don't be surprised when such a test fails and `if` them out as needed. I don't recall ever building with Simmetrix without Parasolid.

**Comment by mortezah** [comment]
1. I don't know the answer to this one.

2. Even though annular.smd is a reference to Parasolid (and the corresponding Parasolid is missing) when the PARASOLID=ON that test does not fail. It fails only when PARASOLID =OFF.

Given that for now, I can change the condition https://github.com/SCOREC/core/blob/43a7b437674db91b02208f78631324ba4b1d8cba/test/testing.cmake#L311

to look like 
if(ENABLE_ZOLTAN AND ENABLE_SIMMETRIX AND SIM_PARASOLID)

@ibaned, please let me know if this is OK with you?

**Comment by ibaned** [comment]
sure
