### ISSUE TITLE
Implementation Question: apf::construct() and apf::setCoords(), unexpected behavior

### ISSUE THREAD

**Issue by zhang-alvin** [SCOREC/core#110]
I've attempted to construct the following mesh in parallel (with 2 ranks) using apf::construct() and apf::setCoords(). Here, elements {0,1,2,3} and vertices {0,1,4} belong to rank 0 and elements {4,5,6} and vertices {2,3,5,6,7} belong to rank 1 (in gray). 
![reconstructmesh_initial2d](https://user-images.githubusercontent.com/7065326/27093927-0f4be1ca-502e-11e7-9e9d-4f712689cde1.png)

The following is the result:
![constructmesh_failure](https://user-images.githubusercontent.com/7065326/27094773-d76acf8e-5030-11e7-9f87-a200c285f3e2.png)

The following is the code that I used to attempt the mesh construction. Based on the mesh output, it looks like the coordinates for each point are set correctly, but the connectivity is completely off. What am I missing?
```
#include <apf.h>
#include <apfMDS.h>
#include <apfMesh2.h>
#include <PCU.h>
#include <pcu_util.h>
#include <cassert>
#include <ma.h>
#include <gmi_mesh.h>
#include <gmi_lookup.h>
#include <gmi_null.h>
#include <stdlib.h>
#include <apfConvert.h>
#include <apfNumbering.h>

#include <iostream>

int main(int argc, char** argv) {
  MPI_Init(&argc, &argv);
  PCU_Comm_Init();

  gmi_register_null();
  gmi_model* nullModel = gmi_load(".null");
  apf::Mesh2* m2 = apf::makeEmptyMdsMesh(nullModel,2,false);
  int nelem;
  int nverts;
  int etype;
  int* conn;
  double* coords;
  apf::GlobalToVert globalToVert;

  if(PCU_Comm_Self()==0){
    nelem = 4;
    nverts = 3;
    etype = apf::Mesh::TRIANGLE;
    conn = (int*) malloc(sizeof(int)*nelem*3);
    conn[0]=  1;
    conn[1] = 7;
    conn[2] = 5;

    conn[3] = 1;
    conn[4] = 4;
    conn[5] = 7;

    conn[6] = 4;
    conn[7] = 0;
    conn[8] = 7;

    conn[9] = 0;
    conn[10] = 6;
    conn[11] = 7;

    coords = (double*) malloc(sizeof(double)*nverts*3);
    coords[0] = 0.0;
    coords[1] = 0.0;
    coords[2] = 0.0;

    coords[3] = 0.0;
    coords[4] = 1.0;
    coords[5] = 0.0;

    coords[6] = 0.0;
    coords[7] = 0.5;
    coords[8] = 0.0;
  }
  if(PCU_Comm_Self()==1){
    nelem = 3;
    nverts = 5;
    etype = apf::Mesh::TRIANGLE;
    conn = (int*) malloc(sizeof(int)*nelem*3);
    conn[0]=  5;
    conn[1] = 7;
    conn[2] = 2;

    conn[3] = 7;
    conn[4] = 3;
    conn[5] = 2;

    conn[6] = 7;
    conn[7] = 6;
    conn[8] = 3;

    coords = (double*) malloc(sizeof(double)*nverts*3);
    coords[0] = 1.0;
    coords[1] = 1.0;
    coords[2] = 0.0;

    coords[3] = 1.0;
    coords[4] = 0.0;
    coords[5] = 0.0;

    coords[6] = 0.5;
    coords[7] = 1.0;
    coords[8] = 0.0;

    coords[9] = 0.5;
    coords[10] = 0.0;
    coords[11] = 0.0;

    coords[12] = 0.5;
    coords[13] = 0.5;
    coords[14] = 0.0;
  }
  apf::construct(m2,conn,nelem,etype,globalToVert);
  apf::setCoords(m2,coords,nverts,globalToVert);
  apf::alignMdsRemotes(m2);
  apf::deriveMdsModel(m2);
  m2->verify();
  free(coords); free(conn);
  apf::GlobalNumbering* globalNum = apf::makeGlobal(apf::numberOwnedNodes(m2,"apf_destruct"));
  synchronize(globalNum);
  apf::writeVtkFiles("reconstructedMesh_parallel", m2);
  std::cout<<"COMPLETED RECONSTRUCTION!\n";
  apf::destroyGlobalNumbering(globalNum);
  PCU_Comm_Free();
  MPI_Finalize();
}
```

As an additional note, if I consolidate the connectivity and coordinates arrays into a serial case, the resulting mesh is as expected.

**Comment by diamog** [comment]
I believe the problem lies in the order that you are giving the coordinates to apf::setCoords(). Looking at the function and this comment "The coords most be ordered according to the global ids of the vertices." It is likely that your coords array does not match the order in globalToVert after the call to apf::construct().

**Comment by cwsmith** [comment]
Yar.  I agree.  See this comment:

https://github.com/SCOREC/core/blob/5198f7de40b78bc96a79f688d7b2aaae61c614a6/apf/apfConvert.h#L50-L59

**Comment by zhang-alvin** [comment]
Shouldn't the order in globalToVert reflect the global numbering that I prescribed initially?  I can print out the entries in the globalToVert map: 
```    
for (std::map<int,apf::MeshEntity*>::iterator it=globalToVert.begin(); it!=globalToVert.end(); ++it)
      std::cout << it->first << " => " << it->second << '\n';
```
The result is the following for rank 0:
```
0 => 0x21
1 => 0x1
4 => 0x19
5 => 0x11
6 => 0x29
7 => 0x9
```
and for rank 1: 
```
2 => 0x11
3 => 0x19
5 => 0x1
6 => 0x21
7 => 0x9
```
From what I understand, my coordinates array on each rank is exactly specifying the coordinates for the owned vertices in the order listed by globalToVert.

**Comment by cwsmith** [comment]
IIRC, `setCoords` is handles multiple processes reading from of a large array of vertex coordinates (possibly from a single file) where the array is ordered by global vertex id.  A large mesh defined in a single file is a common, but primitive, mesh format.  

So, as the function documentation indicates, `Peer 0 provides the coords for vertices 0 to m-1, peer 1 for m to n-1, ...`.  So, you'll want each rank to roughly provide an equal number of vertex coordinates, in order of global id; i.e. rank 0 provides coords for vertices 0-3 and rank 1 provides 4-7.  This code:
https://github.com/SCOREC/core/blob/5198f7de40b78bc96a79f688d7b2aaae61c614a6/apf/apfConstruct.cc#L199-L235
will then retrieve the coordinates needed for each process using a 'broker' process that is know to hold the given range of global coordinate ids.

**Comment by ibaned** [comment]
Yea, @zhang-alvin this is what I mentioned on the call about `setCoords` not being intuitive and probably not being the right choice for your development. It caters to the strange needs of SeisSol. The input to `setCoords` doesn't line up at all in any way with the input to `construct`. If you have the `(input_global, input_coords)` pairs for each vertex in the MPI rank, you're better off just using `globalToVert` directly:
```cpp
mesh->setCoords(globalToVert[input_global], 0, input_coords);
```

**Comment by zhang-alvin** [comment]
Ah, I see so the coordinates array specifies the coordinates of a continuous set of vertices by global ID but those vertices need not be owned by the rank. That definitely resolves the problem.  Thanks @diamog @cwsmith .

**Comment by a-jp** [comment]
@ibaned Can I just confirm that when you said setCoords in this comment (https://github.com/SCOREC/core/issues/110#issuecomment-308207937) you meant setPoint?
Thanks 
Andy

**Comment by cwsmith** [comment]
Correct, it should be `setPoint(...)` to set the coordinates of a single mesh entity.

https://github.com/SCOREC/core/blob/d9eeb2b028afd6182b4d3bc1063d3aae3a348760/apf/apfMesh2.h#L58-L59

**Comment by a-jp** [comment]
so something like:
```cpp
for (const auto &p : globalToVert)
{
    apf::Vector3 point(ordinates[0][p.first], ordinates[1][p.first], ordinates[2][p.first]);
    mesh->setPoint(globalToVert[p.first], 0, point);
}
```

Is this valid in parallel if I've only read part of the mesh on that processor? Can't get my head round this.  So on one processor I may have read two vertices, they could be globally [96, 23] but locally have the id range [0, 1].

Will p.first start from zero and be a local id of the vertex on that processor?  Or the global id of the vertex in the mesh?  The latter would invalidate access into the map so I can't believe it's that.  Which is right?  In serial it's a non issue since one proc reads the whole mesh and the local ids are coincident with the global ids.

**Comment by a-jp** [comment]
Ignore that, that's garbage. It's the the global ids of the vertices in the mesh.  Friday....
