### ISSUE TITLE
New library for Boundary Conditions

### ISSUE THREAD

**Issue by timetravellers** [SCOREC/core#114]
I'm planning putting the boundary condition classes from the [phasta library](https://github.com/SCOREC/core/tree/a6446aa1ee3e97f830a9db60c1edfbfdaa581f39/phasta) into a new library because we need a general way of dealing with analysis cases in the amsi/biotissue code.

It doesn't make that much sense to need to reinvent the wheel for dealing with BCs and interfacing with Simmetrix for each analysis code based on core.

Does anyone have issues with this?

**Comment by cwsmith** [comment]
I don't see a problem with this as long as the output formatting for the application (i.e., to files) is separated from the data structures that maintain BC info.

Will you reuse the code that reads non-simmetrix boundary conditions?
https://github.com/SCOREC/core/blob/8c462070cc75172b931cef0ee08079762b01babe/phasta/phBC.cc#L98

Please make a branch or fork for this work.

**Comment by timetravellers** [comment]
Yes, I was planning on reusing the code for reading non-simmetrix BCs
