### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by JaredCrean2** [SCOREC/core#115]
My Travis CI tests failed to build Pumi (the `master` branch as of about 12:30 PM 7/7/17 (half past noon)) with the following error:

```
 59%] Building CXX object ma/CMakeFiles/ma.dir/maShapeHandler.cc.o
[ 59%] Building CXX object ma/CMakeFiles/ma.dir/maQuality.cc.o
[ 59%] Building CXX object ma/CMakeFiles/ma.dir/maSplits.cc.o
/home/travis/.julia/v0.4/PumiInterface/deps/core/apf/apfVector.h: In function ‘size_t ma::_ZN2maL30isSurfUnderlyingFaceDegenerateEPN3apf4MeshEPNS0_11ModelEntityERiRSt6vectorIdSaIdEE.constprop.61(apf::Mesh*, ma::Model*, int&, std::vector<double>&)’:

/home/travis/.julia/v0.4/PumiInterface/deps/core/apf/apfVector.h:171:26: error: array subscript is above array bounds [-Werror=array-bounds]

cc1plus: all warnings being treated as errors

make[2]: *** [ma/CMakeFiles/ma.dir/maSnap.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [ma/CMakeFiles/ma.dir/all] Error 2
make: *** [all] Error 2
```

Here is my `config.sh` file:

```
#!/bin/bash

mkdir -v ./install

cmake .. \
  -DCMAKE_C_COMPILER="mpicc" \
  -DCMAKE_CXX_COMPILER="mpicxx" \
  -DCMAKE_C_FLAGS="-O2 -g -Wall" \
  -DCMAKE_CXX_FLAGS="-O2 -g -Wall" \
  -DENABLE_THREADS=OFF \
  -DBUILD_SHARED_LIBS=True \
  -DCMAKE_INSTALL_PREFIX=`pwd`"/install" \
  -DIS_TESTING=True \
  -DMESHES=`pwd`"/../../pumi-meshes"
```

Here is a link to the [full Travis log](https://travis-ci.org/OptimalDesignLab/PumiInterface.jl#L4000)

**Comment by ibaned** [comment]
So first off the SCOREC/core build system will likely override your flags, and it adds a `-Werror` by default. This is really just a warning, but is promoted to an error. The warning message is also really crappy, I don't know which compiler is behind `mpicxx` but consider using a newer one.

The warning points somewhere in `ma::isSurfUnderlyingFaceDegenerate`, so probably @mortezah should look at this. There maybe an out-of-bounds access into a vector, or we may need to assert that this is not the case.

**Comment by cwsmith** [comment]
Any update on this @JaredCrean2 ?

**Comment by JaredCrean2** [comment]
The compiler behind `mpicxx` is `g++` 4.6 (the default compiler for Ubuntu 12.04).  I can make Travis install newer compilers if that would help get a better error message, but I would rather make that the long term solution.

**Comment by ibaned** [comment]
GCC 4.6 is pretty pretty old. For reference, Sandia just moved away from GCC 4.7.2, and that was a long drawn-out process. Aren't there newer Ubuntu images for Travis?

**Comment by JaredCrean2** [comment]
It looks like Travis is going to make Ubuntu 14.04 the default by the [end of August](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming).  I'm running a [test](https://travis-ci.org/OptimalDesignLab/PumiInterface.jl#L4000) now where I manually specify the the distro.  14.04 uses gcc 4.8

**Comment by ibaned** [comment]
Wow... Travis is lagging way behind. Another point of reference: GCC 4.8 supports almost all of C++11, whereas GCC 4.6 really doesn't. I moved all my code to C++11 a long time ago. Glad I don't use Travis.

**Comment by JaredCrean2** [comment]
It failed, but the error is different this time.

**Comment by ibaned** [comment]
... can you post it?

**Comment by JaredCrean2** [comment]
```
Building CXX object phasta/CMakeFiles/ph.dir/phAxisymmetry.cc.o
[ 72%] Building CXX object crv/CMakeFiles/crv.dir/crvTables.cc.o
[ 72%] Building CXX object phasta/CMakeFiles/ph.dir/phInterfaceCutter.cc.o
[ 72%] Building CXX object crv/CMakeFiles/crv.dir/crvQuality.cc.o
/home/travis/.julia/v0.4/PumiInterface/deps/core/phasta/phInterfaceCutter.cc:3:20: fatal error: apfSIM.h: No such file or directory
 #include <apfSIM.h>
                    ^
compilation terminated.
[ 72%] Building CXX object crv/CMakeFiles/crv.dir/crvVtk.cc.o
make[2]: *** [phasta/CMakeFiles/ph.dir/phInterfaceCutter.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [phasta/CMakeFiles/ph.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX shared library libcrv.so
[ 72%] Built target crv

make: *** [all] Error 2
```

**Comment by ibaned** [comment]
Pretty sure commit 643ea36 broke compilation without Simmetrix, and the SCOREC test system doesn't test without Simmetrix. That include statement needs an `#ifdef HAVE_SIMMETRIX` around it.

**Comment by cwsmith** [comment]
`develop` should build without Simmetrix again: 24ba5e47d4053c407a08e5d89667bcc03633a464

**Comment by yangf4** [comment]
Thanks, @cwsmith .  I also made a commit: https://github.com/SCOREC/core/commit/9ef6025a4753d42553bc4ab3d36a25a3197667cf

**Comment by JaredCrean2** [comment]
`develop` branch build succeeds.  Was there an actual problem with an out-of-bounds array access, or was gcc 4.6 getting confused?

**Comment by ibaned** [comment]
hopefully the latter. one would hope that later versions of GCC would only get better at spotting these issues, not worse.

**Comment by JaredCrean2** [comment]
Hopefully.  Ready to close the issue?

**Comment by cwsmith** [comment]
I'm closing this until we find other evidence of a problem.
