### ISSUE TITLE
Albany build broken

### ISSUE THREAD

**Issue by ibaned** [SCOREC/core#118]
It looks like a function was put in the wrong place, or not there at all:
```
apf.cc:(.text+0x88d): undefined reference to `apf::computeCosAngleInTri(apf::Mesh*, apf::MeshEntity*, apf::MeshEntity*, apf::MeshEntity*, apf::Matrix3x3 const&)'
```
http://my.cdash.org/viewBuildError.php?buildid=1256573

@bgranzow @cwsmith

**Comment by bgranzow** [comment]
I think a new [source](https://github.com/SCOREC/core/blob/master/apf/CMakeLists.txt#L46) file was added to APF that didn't make it's way into the tribits package cmake [file](https://github.com/SCOREC/core/blob/master/apf/pkg_tribits.cmake).

@mortezah, be sure to take a look at the corresponding `pkg_tribits.cmake` file if you add any additional source and/or headers and ask me to fire off a build of Albany to see if everything's OK.

**Comment by bgranzow** [comment]
3215b6e should fix this

**Comment by bgranzow** [comment]
Closing as it looks like this was resolved:
http://my.cdash.org/index.php?project=Albany&date=
