### ISSUE TITLE
Building core without SimAdvMeshing

### ISSUE THREAD

**Issue by mjuha** [SCOREC/core#119]
Hello,
I am trying to compile core with Simmetrix and I am getting the following compilation error:

/home/marioju/projects/scorec/phasta/phOutput.cc:13:27: fatal error: SimAdvMeshing.h: No such file or directory
 #include <SimAdvMeshing.h>

The cause is simple. I do not have a license for SimAdvMeshing. Could you add a logic in the code for cases where the user does not have or does not need that capability? Any workaround that does not need to adquiere the license of SimAdvMeshing?

**Comment by bgranzow** [comment]
@cwsmith, @yangf4 Is it safe to say that the phasta package requires advanced meshing features? If so, would it make sense to simply disable it if the [optional](https://github.com/SCOREC/core/blob/master/cmake/FindSimModSuite.cmake#L130) Simmetrix libraries are not found?

**Comment by mjuha** [comment]
@bgranzow that is basically what I was thinking. Thanks for improve my comment.

**Comment by yangf4** [comment]
If one has to compile phasta package with Simmetrix, then, it is safe to say phasta package requires advanced meshing features. I think we can disable it (if the optional Simmetrix libraries are not found) for now. If someone encounters a trouble in the future, we can think of adding logic then.

**Comment by cwsmith** [comment]
@yangf4 I modified the phasta code in the [build-without-simadvmeshing](https://github.com/SCOREC/core/commits/cwsmith/build-without-simadvmeshing) branch to build with and without SimAdvMeshing.  From what I could tell the only code that made SimAdvMeshing calls was the `getGrowthCurves` function.  Given that, I moved it to its [own source file](https://github.com/SCOREC/core/blob/6739e5ca5c5d94dd8d8d9701570e27ff0b09f4a3/phasta/phGrowthCurves.cc) and [compile it only when SimAdvMeshing is available](https://github.com/SCOREC/core/blob/6739e5ca5c5d94dd8d8d9701570e27ff0b09f4a3/phasta/CMakeLists.txt#L38-L42).

`cut_interface`, `phSnap`, and `sim_part` were including `SimAdvMeshing.h` but did not appear to need it or the calls to `SimAdvMeshing_[start|stop]()`.  Note, [`chef` still calls `SimAdvMeshing_[start|stop]()`](https://github.com/SCOREC/core/blob/6739e5ca5c5d94dd8d8d9701570e27ff0b09f4a3/phasta/chef.cc#L42-L44). The compile flag controlling those calls comes from [test/CMakeLists.txt](https://github.com/SCOREC/core/blob/6739e5ca5c5d94dd8d8d9701570e27ff0b09f4a3/test/CMakeLists.txt#L97-L99).  Can you please test your workflow using a boundary layer mesh to confirm that things are not broken by these changes?  If you find a step/binary that no longer works would you please add a test for it to the branch?

**Comment by yangf4** [comment]
I just ran some tests. Both `cut_interface` and `sim_part` need `SimAdvMeshing.h`. Otherwise, the BL information will be gone. So we need to put compile flag around `SimAdvMeshing.h` for these two. 

We can remove `SimAdvMeshing.h` in `phSnap`. 

I am going to add some regression tests on this issue.

**Comment by bgranzow** [comment]
All this is strongly suggesting we should resolve #58

**Comment by cwsmith** [comment]
@bgranzow I agree.

@yangf4 Thank you.  Please let me know when the tests are in the branch and I'll make the changes to conditionally include `SimAdvMeshing.h` (unless you want to :) ).

**Comment by yangf4** [comment]
@cwsmith  regression tests are added. https://github.com/SCOREC/core/commit/16935caca345775cd4a66f003b389ccd26bcc54e

Please note that I didn't put `SimAdvMeshing.h` in if conditional for `cut_interface` and `sim_part`.

**Comment by cwsmith** [comment]
The branch has been merged: 57a42c14349cbe567ed64fd13aedf73f20786fcb

@bgranzow Would you please start a Trilinos/Albany build?

**Comment by bgranzow** [comment]
just fired it off.

**Comment by bgranzow** [comment]
My nightly Albany/Trilinos build installed OK.

**Comment by cwsmith** [comment]
@mjuha I'm going to close this issue.  Please re-open the ticket if you have more build problems related to SimAdvMeshing.

**Comment by mjuha** [comment]
@cwsmith still I am having compilation issues:

/home/marioju/projects/scorec/test/simTranslate.cc:11:25: fatal error: SimAdvModel.h: No such file or directory
 #include "SimAdvModel.h"
                         ^
compilation terminated.

Any ideas?

**Comment by cwsmith** [comment]
master or develop branch?  what git hash/commit?

**Comment by mjuha** [comment]
Cameron,
master branch. This is the commit:

commit 12cf1184f76ad65688051ad9dcaf2930d5b635ed
Merge: f0edfed 2be180d
Author: Nightly Bot <donotemail@scorec.rpi.edu>
Date:   Mon Aug 7 17:06:51 2017 -0400

    Merging develop into master

**Comment by cwsmith** [comment]
Is the build directory clean?  I.e. was it completely empty when you ran cmake?

**Comment by mjuha** [comment]
yes. It was clean. I jus removed the test and then compiled correctly. The problem is that simTranslate.cc includes SimAdvModel.h.

**Comment by cwsmith** [comment]
Blehhh.  I misread the AdvModel as AdvMeshing... We'll have to address that separately.  Please create another issue for that.

**Comment by mjuha** [comment]
Same issue appear again, but now with at least the following files:

phMeshQuality.cc
measureAnisoStats.cc
visualizeAnisoSizes.cc

Is there any way not to compile phasta tools at all?

**Comment by cwsmith** [comment]
I just pushed a few commits that support building and testing without libSimAdvMeshing.a and the corresponding header:
https://github.com/SCOREC/core/commit/6ca4571df39cc0768fdcab94e089a65b0f58a6f1
https://github.com/SCOREC/core/commit/cfef354890b1c6a927507f6f0ce87904068940ff

**Comment by mjuha** [comment]
It compile. The only issue is with:

 [ 97%] Building CXX object test/CMakeFiles/simTranslate.dir/simTranslate.cc.o
/home/marioju/projects/scorec/test/simTranslate.cc:11:25: fatal error: SimAdvModel.h: No such file or directory  #include "SimAdvModel.h"

But I solved the problem not compiling that program.

Thank you

**Comment by mjuha** [comment]
With this commit:

commit 4ccd10a6cd424ffc26f92fc7e8b638af0af6b444
Merge: 28d2299 6ca4571
Author: Nightly Bot <donotemail@scorec.rpi.edu>
Date:   Thu Nov 29 00:19:33 2018 -0500

    Merging develop into master

The problem with SimAdvMeshing was solved. The problem compiling SimTranslate persist, but it is another issue. I will close this issue.
