### ISSUE TITLE
Wiki page explaining mesh file formats

### ISSUE THREAD

**Issue by bgranzow** [SCOREC/core#122]
A wiki page with explanations of file formats (e.g. `.dmg`, `.smb`, `.sms`, `.smd`) and conversions between the file formats using PUMI utilities (e.g. `convert`, `mdlConvert`) would be beneficial if it doesn't already exist

**Comment by cwsmith** [comment]
This page covers geometric models.

One for meshes would be nice.

**Comment by cwsmith** [comment]
We also have a mesh generation page now:
https://github.com/SCOREC/core/wiki/Mesh-Generation

Since things can clearly never get better than they are now, I'm going to close this issue.
