### ISSUE TITLE
Trilinos package build fails new TriBITS checks

### ISSUE THREAD

**Issue by ibaned** [SCOREC/core#128]
Reported by @mperego
```
CMake Error at
cmake/tribits/core/package_arch/TribitsPackageMacros.cmake:838 (MESSAGE):
  Must call TRIBITS_PACKAGE_DEF() after TRIBITS_PROCESS_SUBPACKAGES() in
/users/mperego/nightly/repos/Trilinos/SCOREC/CMakeLists.txt
Call Stack (most recent call first):
  SCOREC/pkg_tribits.cmake:6 (TRIBITS_PROCESS_SUBPACKAGES)
  SCOREC/CMakeLists.txt:5 (include)


-- Configuring incomplete, errors occurred!
See also "/users/mperego/nightly/build/TriBuild/CMakeFiles/CMakeOutput.log".
See also "/users/mperego/nightly/build/TriBuild/CMakeFiles/CMakeError.log".
Command exited with the value: 1
Error(s) when configuring the project
CMake Error at
/users/mperego/nightly/repos/Albany/doc/dashboards/jenga.scorec.rpi.edu/ctest_nightly_jenga_32bit.cmake:446
(message):
  Cannot configure Trilinos build!
```

This is a bit strange, because `pkg_tribits.cmake` contains:
```cmake
INCLUDE(TribitsPackageMacros)
INCLUDE(TribitsAddOptionAndDefine)

TRIBITS_PACKAGE(SCOREC)

TRIBITS_PROCESS_SUBPACKAGES()

TRIBITS_PACKAGE_DEF()

TRIBITS_PACKAGE_POSTPROCESS()
```

@bartlettroscoe how is this package using TriBITS wrong?

**Comment by ibaned** [comment]
relevant

https://github.com/TriBITSPub/TriBITS/issues/200

https://github.com/trilinos/Trilinos/commit/e2b8a39f480b5fe61f348e3213f38e56bd71f700

**Comment by bartlettroscoe** [comment]
You need to call `TRIBITS_PACAKGE_DECL(SCORC)` instead of `TRIBITS_PACAKGE(SCORC)` since the package has subpackages.  Also, you don't need (or want) the includes at the top.  So what you want is:

```
TRIBITS_PACKAGE_DECL(SCOREC)

TRIBITS_PROCESS_SUBPACKAGES()

TRIBITS_PACKAGE_DEF()

TRIBITS_PACKAGE_POSTPROCESS()
```

See:

* https://tribits.org/doc/TribitsDevelopersGuide.html#packagedir-cmakelists-txt

which points to the example: CMakeLists.txt file:

* https://github.com/TriBITSPub/TriBITS/blob/master/tribits/examples/TribitsExampleProject/packages/with_subpackages/CMakeLists.txt


Sorry for the confusion.  We should have written these checks into TriBITS years ago.  IT wold have caught all kinds of stuff.  In this case, it was benign.  In other cases (like ???), mistakes with calling these functions correctly can cost a lot of human time and productivity.

I will look into improving the error message in this case.

**Comment by ibaned** [comment]
I pushed  363c08d which hopefully fixes this. Will reopen if it doesn't.

**Comment by mperego** [comment]
Thanks. Unfortunately now I get this error:

`CMake Error at cmake/tribits/core/package_arch/TribitsPackageMacros.cmake:762 (MESSAGE):
  Must call TRIBITS_PACKAGE() before TRIBITS_PACKAGE_POSTPROCESS()

   at the top of the file:
   /users/mperego/nightly/repos/Trilinos/SCOREC/CMakeLists.txt
Call Stack (most recent call first):
  SCOREC/pkg_tribits.cmake:7 (TRIBITS_PACKAGE_POSTPROCESS)
  SCOREC/CMakeLists.txt:5 (include)
`

**Comment by ibaned** [comment]
@mperego did you do a completely clean reconfigure?

**Comment by mperego** [comment]
@ibaned, Yes.

**Comment by ibaned** [comment]
@mperego are you still seeing this? Is it visible on one of Albany's CDash sites?

**Comment by mperego** [comment]
Yes, I still see this. It would be on this dashboard
http://my.cdash.org/index.php?project=Albany&date=
but unfortunately Trilinos configuration dies and nothing is reported on the dash.

I'm building this on Jenga and this is the script:
https://github.com/gahansen/Albany/blob/master/doc/dashboards/jenga.scorec.rpi.edu/ctest_nightly_jenga_32bit.cmake

**Comment by ibaned** [comment]
@mperego if you remove this `FATAL_ERROR` line:
https://github.com/gahansen/Albany/blob/master/doc/dashboards/jenga.scorec.rpi.edu/ctest_nightly_jenga_32bit.cmake#L446
and do `CTEST_SUBMIT` before failing, then we can see the output even if configure fails.

**Comment by mperego** [comment]
Thanks. You can see it now:
http://my.cdash.org/index.php?project=Albany&subproject=JengaTrilinosDev

**Comment by ibaned** [comment]
@bartlettroscoe any ideas? Your suggested calls seem to give a conflicting error.

**Comment by bartlettroscoe** [comment]
@ibaned, do you have instructions on how to configure SCOREC under Trilinos to reproduce this failure?   We may need to improve the error messages.

**Comment by ibaned** [comment]
@bartlettroscoe it should suffice to clone the repository in which these comments are under Trilinos as
```
Trilinos/SCOREC
```
And then to specify
```
-DTrilinos_ENABLE_SCOREC:BOOL=ON
```
In the CMake configuration process

**Comment by bartlettroscoe** [comment]
If you access the PR #130, this should fix the configure of the SCOREC TriBITS package.  Sorry for the bad error message.  It should be fixed now in TriBITS.  I will snapshot to Trilinos updated TriBITS with better error message in these cases.

**Comment by ibaned** [comment]
The fix is in develop. We should hopefully know by tomorrow if it worked.

**Comment by mperego** [comment]
I rerun my nightly tests and it's working fine! Thanks @ibaned @bartlettroscoe

**Comment by ibaned** [comment]
Fantastic

**Comment by bartlettroscoe** [comment]
Sorry for the trouble.  SCOREC was exercising a use case that we never thought about (but happened to work).  If a package does not have subpackages I think it is more clear to have a CMakeLists.txt file that looks like the example in https://tribits.org/doc/TribitsDevelopersGuide.html#packagedir-cmakelists-txt.  The new checks that I am about the snapshot to Trilinos report this much better I think.

**Comment by mperego** [comment]
@bartlettroscoe  No worries, thanks for helping with that!
