### ISSUE TITLE
How to load gmsh files

### ISSUE THREAD

**Issue by YetAnotherMinion** [SCOREC/core#13]
Which file format to I need to save the mesh and geometry description in Gmsh in order to read them in? I see in the source that you can load `dmg` files and `tess` files using PUMI, but I do not see either of these filetypes as an option to save in Gmsh dialog.

I need someway to load a geometry entity that has tags on it so I can iterate over the mesh enties, get their classifications, and look up what boundary conditions they have. If there is a file format where I can edit by hand the tags that entities have that would be ideal.

Any pointers to the relevant documentation or tutorials would be a great help.

**Comment by ibaned** [comment]
You may have no choice but to use the "null" model. It will create model entities if they don't already exists as the code looks for them, (this means no other info like CAD topology and curvature show up, but its enough to set boundary conditions).

    #include "gmi_null.h"
    gmi_register_null();
    gmi_model* g = gmi_load(".null");

Basically, Gmsh's geometry seems to only exist in their input file, which has a format that looks way too advanced for me to just casually code a parser for it. I don't see a way to save it in a more usable format if thats where it comes from.

You can also make future work easier by saving the null model into dmg form:

    gmi_write_dmg(g, "mymodel.dmg");

**Comment by YetAnotherMinion** [comment]
Is there a snippit that shows how to create a specific type of ModelEntity for vertices.

I have a `apf::MeshEntity* e` what functions do I call to convert this to a gmi_ent* so that I can set the tag on the entitity and look it up later. I am not seeing this exact process.

I have seen in other codes reinterpret cast done between ModelEntity and gmi_ent, but do not know if that is a good idea to use here.

```C++
//create a brand new mesh using same methods as old assign 1 code

apf::MeshEntity* e = some_vert;
apf::ModelEntity* model_ent = m->toModel(e); // I am hoping this creates a new vertex

//?????? Set ModelEntity tag here to some integer key that will stick around on mesh entity

//later I iterate over all the vertices
apf::MeshIterator = m->begin(0);
while((e = m->iterate(it))) {
  int my_boundary_condition_identifier = getModelTag (ModelEntity *e);
  /* but documentation seems to indicate that getModelTag returns get the dimension-unique model 
entity identifier which does not sound what I want, since I want one number on every vertex telling
 me if it is fixed */
}
```
These tags are trivial to add on the mesh entity level. But I am looking to put one on the geometry for the edges and vertices. It would be nice if I could have a square in the geometry model and add a different tag to each of the four edges.

Is there an order I need to create the geometry model entities, or will the software be able to figure out that a bunch of adjacent mesh edges are all along the same geometric edge when I call ` apf::deriveMdsModel(m)`

**Comment by ibaned** [comment]
Those were a lot of questions for an issue comment

1) geometric "tag"s are not the same as mesh "tag"s. The confusion of terminology predates my work, what is important now is that, first, a geometric tag is an integer identifier which you can query but not change. Second, we don't yet support attaching data in the same style as mesh tags.

2) You need to set up a separate association system to go from these integer identifiers to boundary condition specifications.

3) If you are using Gmsh mesh files, you should not mix that with deriveMdsModel. Properly configured, Gmsh will output equal-order entities, i.e. triangles on a CAD surface, mesh edges on CAD edges. Based on that, the resulting mesh is properly classified. There is no derivation process, it is either specified in the mesh file or not. Also you don't need to create the geometric entities with the null model, the internal calls to findModelEntity will create them.

4) The "tag" identifiers should be based on the geometry definition into Gmsh. I think its input file specifies the IDs for model entities, but we really rarely use Gmsh input.

**Comment by YetAnotherMinion** [comment]
I apologize for not being more clear above. I had already abandoned the idea of using Gmsh in the previous comment and was looking for a canonical way to attach tags to the geometry definition.
Right now I generate the test meshes for each of my test cases programmatically, using the same code as in assign 1. I can attach tags to the mesh entity all day long in that controlled generation routine, but then I must modify the routine to have different tag distributions.

My solver code internally reads tags with specific assumed names ( shared by defines) and casts the results to a globally visible enum. This enum is fed into a singleton mapping class that is instantiated outside of any analysis code and passed into my solver. In the assembly process, each mesh entity tag is read, and the mapping class is used to find a specific function pointer to apply boundary conditions or compute which ones are fixed. This way I can keep the same tagging, and just manipulate the constructor of the mapping singleton class to add a bunch of different functions to the mapping with key values. This singleton class is the sketchiest config file, as you have to keep track of which integer tags are on which mesh entities, and then write functions, then dynamically link the compiled version of the class into the solver at runtime to get the tagging.

I pass the mesh entity into these functions, so I can only add a boundary force to some element faces and not others. However this relies on tight, undocumented coupling between the physical size and layout of the generated mesh and the boundary condition mapping.

I am trying to avoid using a compiled C++ program dynamically linked as a library as my version of geometry config file.

You rarely use Gmsh input, but when you do.. how? I will jump through hoops backwards to use Gmsh if possible since it is the correct way to handle a geometry based definition. All I need is to be able to assign integers in some interactive way to the model entities, or even the mesh entities if necessary in a predictable tag name. Everything else is taken care of once I can get it to that point.

There has to be a better way.

**Comment by ibaned** [comment]
We usually end up with some kind of mapping from geometric entities to boundary condition descriptions. The tools that do this best (Simmetrix geometric models) are not open source. We've implemented the equivalent mapping as simple text file formats in various combinations.

As an example, we work with a code called Albany, for which I created this custom format for associating geometric ID integers with human-readable strings:

https://github.com/gahansen/Albany/blob/master/examples/LCM/SCOREC/Elasticity/traction_assoc.txt

The configuration file for Albany then points to that associations file:

https://github.com/gahansen/Albany/blob/master/examples/LCM/SCOREC/Elasticity/inputT.xml#L38

And describes boundary conditions using the readable strings:

https://github.com/gahansen/Albany/blob/master/examples/LCM/SCOREC/Elasticity/inputT.xml#L5
