### ISSUE TITLE
Installing core on AMOS with bgclang

### ISSUE THREAD

**Issue by bgranzow** [SCOREC/core#132]
This issue is intended to track progress in installing pumi on the RPI blue gene Q w/ the bgclang compiler.

I am starting with the simple config:
```
cmake .. \
-DCMAKE_C_COMPILER:FILEPATH=mpiclang \
-DCMAKE_CXX_COMPILER:FILEPATH=mpiclang++11 \
-DCMAKE_INSTALL_PREFIX:PATH=/gpfs/u/home/PGES/PGESgnzw/scratch/bgq/core/install-opt \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DENABLE_ZOLTAN:BOOL=OFF \
2>&1 | tee config_log
```

configure and running `make` run to completion, however `make install` returns the error 

```
CMake Error at test/cmake_install.cmake:45 (file):
  file RPATH_CHANGE could not write new RPATH:

    /gpfs/u/home/PGES/PGESgnzw/scratch/bgq/core/install-opt/lib

  to the file:

    /gpfs/u/home/PGES/PGESgnzw/scratch/bgq/core/install-opt/bin/verify

  No valid ELF RPATH or RUNPATH entry exists in the file;
Call Stack (most recent call first):
  cmake_install.cmake:81 (include)
```

which I think is strange because shared libs are turned off. This error goes away when I use the cmake option `CMAKE_SKIP_RPATH`, but I am not sure this correctly installs the package.

**Comment by bgranzow** [comment]
@ibaned, will SCOREC/core install correctly if skip rpath is turned on?

**Comment by cwsmith** [comment]
I believe it will.

**Comment by bgranzow** [comment]
@cwsmith wrote:
> I believe it will.

Cool. Do you have any idea why CMake is trying to do this in the first place, when `-DBUILD_SHARED_LIBS:BOOL=OFF` ?

**Comment by ibaned** [comment]
Its not CMake, its the build helpers I wrote.
I think at some point I changed it to always set RPATH things even if static libraries were being built:
https://github.com/ibaned/cmake_bob/blob/master/bob.cmake#L35
The rationale was a scenario where even though your code was configured to build statically, some dependency of yours was a shared library, and so you could still have your executable point to it. However, it looks like RPATH altogether isn't supported on BG/Q.

**Comment by bgranzow** [comment]
@ibaned, thanks for the explanation.

**Comment by bgranzow** [comment]
I was able to build SCOREC/core, link to Trilinos for the Zoltan dependency and run the split executable on a small mesh to go from 1 to 4 parts. Looks pretty good. @cwsmith, would there be interest in an install instruction page on the wiki?
