### ISSUE TITLE
shape correction loop

### ISSUE THREAD

**Issue by bgranzow** [SCOREC/core#135]
There are now two high level calls to adapt the mesh in ma:
`adapt` and `adaptVerbose`.

Recent changes to mesh adapt have introduced an iterative shape correction loop into the call to the regular `adapt` method. Was this intended?

**Comment by mortezah** [comment]
I use `adaptVerbose` for debug purposes. It is very similar to `adapt` except for the following two changes:
1) it outputs the mesh at different steps of the adaptation
2) it attempts to correct the shapes at the end of each adapt iteration. (`adapt` only attempts correction once after adapt iterations are done.)

The shape-correction was always iterative. The only difference is that now it prints out some extra information about the state of shape-correction.

**Comment by bgranzow** [comment]
I see. Thanks for the info!
