### ISSUE TITLE
measure Sim-based mesh

### ISSUE THREAD

**Issue by yangf4** [SCOREC/core#137]
I am using the executable measureAnisoStats to measure the Simmetrix-based mesh (I modified the code and let it take Simmetrix-based mesh). The mesh is quite simple. It is a pure-tet mesh. Then I got an error:
fabs(denom) > 1e-10 failed at /fasttmp/yangf4/codes/SCOREC/core/core/mth/mthQR.cc + 228

at this line:
https://github.com/SCOREC/core/blob/master/mth/mthQR.cc#L228

The call stack of this error is as following:

PCU_ALWAYS_ASSERT(fabs(denom) > 1e-10);
get_wilkinson_shift
mth::eigenQR
apf::eigen
orthogonalEigenDecompForSymmetricMatrix
ma::LogAnisoSizeField::getTransform
ma::getMetricWithMaxJacobian
ma::measureTetQuality
ma::measureElementQuality
ma::getLinearQualitiesInMetricSpace
ma::getStats

Any idea? What does this error mean?

**Comment by yangf4** [comment]
The size and frame fields come from V_size:
1. create the size and frame field
2. query associated size field by using V_size
3. set value for the size and frame fields
4. use the size and frame fields for the following measurement

**Comment by bgranzow** [comment]
The error is telling you the QR algorithm for finding the eigendecomposition of your matrix is failing. I'd advocate printing out whatever matrix (presumably some 3x3 matrix) you're trying to eigen-decompose. If it's not symmetric, you're gonna have a bad time.

https://github.com/SCOREC/core/blob/master/mth/mthQR.h#L69

**Comment by yangf4** [comment]
Thanks to @bgranzow 

The issue is that V_size returns all-zero matrix in case of isotropic size field.

This has been fixed. I am going to close this issue.
