### ISSUE TITLE
Build Failure on OSX

### ISSUE THREAD

**Issue by JaredCrean2** [SCOREC/core#139]
I have been helping @siavashadpey install my solver on his computer, but we ran into trouble building Pumi.

When building commit (the merge commit before the one in #138)

```
commit 063ad65589003b5e426eb7653cba1b66ebded3ab
Merge: 1324ac6 81da53b
Author: Nightly Bot <donotemail@scorec.rpi.edu>
Date:   Thu Feb 1 00:17:40 2018 -0500

    Merging develop into master
```

which builds successfully on Ubuntu 16.04, the following error occurs:

```
/Users/Sia/.julia/v0.4/PumiInterface/deps/core/mds/apfMDS.cc: In function ‘void apf::deriveMdlFromManifold(apf::Mesh2*, bool*, int, int (*)[5], apf::GlobalToVert&, std::map<int, apf::MeshEntity*>&)’:
/Users/Sia/.julia/v0.4/PumiInterface/deps/core/mds/apfMDS.cc:892:8: error: ‘uint’ was not declared in this scope
   for (uint i = 0; i < mesh->count(0); ++i) {
        ^~~~
/Users/Sia/.julia/v0.4/PumiInterface/deps/core/mds/apfMDS.cc:892:8: note: suggested alternative: ‘rint’
   for (uint i = 0; i < mesh->count(0); ++i) {
        ^~~~
        rint
/Users/Sia/.julia/v0.4/PumiInterface/deps/core/mds/apfMDS.cc:892:20: error: ‘i’ was not declared in this scope
   for (uint i = 0; i < mesh->count(0); ++i) {
                    ^
/Users/Sia/.julia/v0.4/PumiInterface/deps/core/mds/apfMDS.cc:892:20: note: suggested alternative: ‘pi’
   for (uint i = 0; i < mesh->count(0); ++i) {
                    ^
                    pi
make[2]: *** [mds/CMakeFiles/mds.dir/apfMDS.cc.o] Error 1
make[1]: *** [mds/CMakeFiles/mds.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

The output of `uname -a` for his system is:

```
Darwin SSMac 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```

The config file is the same as #138.  I don't have any experience building Pumi on OSX, so I'm not sure what to suggest.

**Comment by tobinw** [comment]
This looks like a problem with GLIBC on OSX: [see here](https://stackoverflow.com/questions/43892984/gcc-5-6-and-7-on-osx-do-not-support-uint?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

According the [standard](http://pubs.opengroup.org/onlinepubs/9699919799/) for C integers that typedef is supposed to exist in stdint.h

Since uint is a defined in a standard C-header it isn't technically a C++ type (though the types underlying the typedef are) and this particular file is a C++ file. I would think the preferred solution to this should be using `unsigned` instead of `uint`.

**Comment by ibaned** [comment]
@tobinw I don't see `uint` anywhere in the [POSIX](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/stdint.h.html) or [C++](http://en.cppreference.com/w/cpp/header/cstdint) documentation. `unsigned` is the way to go.

**Comment by tobinw** [comment]
see 287a59e185f24506827ed5cb7f3b1c1cf134f483

**Comment by tobinw** [comment]
A cursory check doesn't reveal any other occurrences of `uint` in the codebase. So hopefully this resolves the issue.

**Comment by cwsmith** [comment]
I assume this is resolved. Please reopen if not.
