### ISSUE TITLE
Are Numberings on nodes or Entities?

### ISSUE THREAD

**Issue by YetAnotherMinion** [SCOREC/core#14]
When I try to number mesh edges on a linear mesh, I get a segmentation fault. Is the numbering on nodes or is it on the field itself. If it is on nodes then the error makes sense, because there are no nodes on edges in a linear mesh. 

How do I stick an integer to mesh entities like edges so that when I change the shape functions I can still look up the same tag from the actual entity obtained from the mesh iterator over a certain dimension? Do I have to do this outside of the mesh by using an externally applied map to all of the entities?

I am still on the quest to attach boundary conditions to a mesh generated programmatically so I know where all of the edges are.

**Comment by ibaned** [comment]
The short answer is they are on nodes. In particular, though, nodes are not really objects in their own right, where they are is defined entirely by the FieldShape being used. When a Numbering is made from a field it uses the field's FieldShape, other calls use the Mesh's FieldShape, and so on.

If you are going to want consistency across shape function changes, I would suggest using an apf::MeshTag (mesh->createIntTag), which is on entities and is not affected by shape. The implementation of Numberings and Fields is build on MeshTags.

**Comment by YetAnotherMinion** [comment]
This worked. Thanks!
