### ISSUE TITLE
hard coded simmetrix license paths break tests

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/core#140]
The tests partition_sim, countBL_cut_mesh, and countBL_part_mesh all have hard coded license paths.  Please replace these with something that works on all systems (i.e. read the environment variable like the rest of the tests that use simmetrix).

**Comment by yangf4** [comment]
fix:
https://github.com/SCOREC/core/commit/97edab1bbcdc4f3ccc35fbbb2795075397a83f63
