### ISSUE TITLE
Albany build broken

### ISSUE THREAD

**Issue by ibaned** [SCOREC/core#142]
@maxrpi 

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=67947

The TriBITS build for MeshAdapt likely needs to be updated if there are new files.

**Comment by ibaned** [comment]
@ikalash

**Comment by mortezah** [comment]
just pushed a commit which adds the new file to pkg_tribits.cmake.
Please let me know if there are still problems.

PS1: I cannot see the link http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=67947
PS2: @AjinkyaDahale

**Comment by ibaned** [comment]
Oh, sorry about the link, I forgot it was internal.
Here is a public link that shows the same:

https://my.cdash.org/viewBuildError.php?buildid=1381691

Thanks @mortezah !

**Comment by AjinkyaDahale** [comment]
Just noticed I also had a mention here! I'm sorry I didn't know about this place to add the files to. Hopefully @mortezah's doing so fixed the issue entirely?

**Comment by ibaned** [comment]
Yea its fixed
