### ISSUE TITLE
measureAnisoStats doesn't compatible with Simmetrix-based mesh

### ISSUE THREAD

**Issue by yangf4** [SCOREC/core#146]
In detail, it fails at this line (changeMdsDimension):
https://github.com/SCOREC/core/blob/master/test/measureAnisoStats.cc#L254

I can provide a sim-based mesh for testing purpose.

**Comment by tobinw** [comment]
Since a Simmetrix mesh is not an MDS mesh I wouldn't expect the call to apf::changeMDSDimension() to succeed. Only MDS meshes support having their dimensionality changed with this function.

[This](https://github.com/SCOREC/core/commit/20aee6e9ac55c75eb658767a4ce20eb43af763e3#diff-3c4f726cec0c6ee35d0b3a225fdb8f8a) commit added the call to get wireframe meshes.

**Comment by tobinw** [comment]
The quickest/dirtiest fix would be to turn those lines off when using simmetrix with and ifdef.

**Comment by tobinw** [comment]
Oh this just occurred to me.  You could also convert the simmetrix mesh to an mds mesh using 

```
Mesh2* createMdsMesh(gmi_model* model, Mesh* from);
```

from [here](https://github.com/SCOREC/core/blob/master/mds/apfMDS.h#L77). Just wrap the call that loads the initial simmetrix mesh [here](https://github.com/SCOREC/core/blob/master/test/measureAnisoStats.cc#L124).

**Comment by tobinw** [comment]
As a final alternative you could remove the mesh dimension reduction and use your post-processing tools to visualize only the edges and edge tag information.

**Comment by yangf4** [comment]
Thank you @tobinw 

@mortezah  I am wondering why we need dimension reduction here? It seems to me that Paraview has a very easy way to visualize only edges.

**Comment by mortezah** [comment]
I do that to be able to visualize metric edge lengths in paraview.

**Comment by mortezah** [comment]
it seems that with this line commented out https://github.com/SCOREC/core/blob/master/test/measureAnisoStats.cc#L254
I still get the correct edge length visualization. 
So if that line is causing problems for simx meshes you can get rid of it.

**Comment by yangf4** [comment]
OK. That is good.   Thanks @mortezah

**Comment by yangf4** [comment]
fix
https://github.com/SCOREC/core/commit/f50c388da77d3ea1753cb263808432abb87738b6
