### ISSUE TITLE
How to set field values over mesh element?

### ISSUE THREAD

**Issue by YetAnotherMinion** [SCOREC/core#15]
Is there a way to set the values over a vector field using the same numbering mapping to nodes on mesh elements as returned by 

```C++
apf::getElementNumbers(apf::Numbering*, apf::MeshEntity*, apf::NewArray<int> & )
```
I have created a vector field and zeroed it. Now I want to modify the field components for each node on the field shape function. The element node mapping returned by getElementNumbers directly corresponds to my vector of displacements, which I now want to write to each node using the vector field. What is the best way to go from the global element mapping to the individual nodes of the vector field?

It looks like the inverse of what I am trying to do exists in the: 

``` C++ 
int FieldDataOf<T>::getElementData(MeshEntity* entity, NewArray<T>& data)
 ```
Where it aligns the nodes into the correct order and then retrieves the values from the field. Will running this in reverse give the same ordering as we get when retrieving the numberings?

**Comment by ibaned** [comment]
I'm still a bit confused what you're trying to do, but here is what I understood. You are operating on a single element at any given moment, and have computed field values for each element node, now you want to write them to the nodes. The reason there isn't a function for this already is that elements share nodes, so unless you have a proof that your mathematics will produce the same value for a shared node regardless of which element you're in, you will need to come up with a way to combine all the different incoming values. Maybe if you describe at a very high level where this is coming from it will be easier.

**Comment by YetAnotherMinion** [comment]
Paraview can render the vector fields and warp the mesh according to these vector fields. I have a solution vector of displacements, stresses, and strains and want to visually display them. The solution vector is how I guarantee that the values are the same, I am only interested in the same nodes on the mesh that I solve the FEA model for. I want to end up with output in the vtu files of 
`<DataArray type="Float64" Name="StressField" NumberOfComponents="3" format="ascii">`
I was looking for a quick and convenient way to write out this information so I can get automatic coloring interpolation and visual mesh deformation using the scale factor to exaggerate the deformation until the human eye could detect it.

**Comment by ibaned** [comment]
if you create a nodal apf::Field to store the displacement, it will automatically be written to the vtu files in a way that Paraview will accept it for its warp filter. Specifically, you can use apf::createFieldOn, apf::VECTOR. Also, you can get your stresses and strains to show up by putting them in "IP" (integration point) fields, using apf::getIPShape as the shape.

**Comment by YetAnotherMinion** [comment]
I am getting a null pointer for dimension 2 integration order of 4, which is the same integration order I am using in my subclasses of apf::Integrator. Dimension 2 and integration order of 2 or 3 works fine. I am not sure why apf::Integrator works while IPshape does not?

**Comment by bgranzow** [comment]
https://github.com/SCOREC/core/blob/master/apf/apfShape.cc#L779

Integration orders for 2D meshes stop at 3rd order accuracy, which is
why you get a null pointer.

**Comment by bgranzow** [comment]
That's not to say we don't support higher order integration rules,
that's just how the IPShape is currently coded.

**Comment by ibaned** [comment]
here you go: https://github.com/SCOREC/core/commit/6346643cba60d4a3cb1e34afa370bd1c71a0326a

we have to explicitly instantiate things so they can be singletons so they can be serialized consistently

**Comment by YetAnotherMinion** [comment]
Ok thanks! Can you comment briefly on how the IPShapes work, I am seeing four pieces of each field that I create. For example I do this right now just to see what everything looks like

```C++
this->stress_field = apf::createField(this->m, "StressField", apf::VECTOR, apf::getIPShape(2, 3));
apf::zeroField(this->stress_field);
```

Then I see in paraview 
![fields](https://cloud.githubusercontent.com/assets/8005290/9476802/b578da38-4b3c-11e5-8f4c-f986b975e138.png)

What are the four parts? and how will having four separate parts affect my ability to display the stress across the entire thing in paraview?

**Comment by ibaned** [comment]
Paraview has no understanding of integration points, so we copied the behavior that one sees when loading Exodus files: four integration points per element results in four cell data arrays. Basically, you can display each integration point as though that were the constant value over the element.

**Comment by YetAnotherMinion** [comment]
So when I have 4th order accurate I should see 9 parts. I am not familiar with Exodus files. I was just planning to compute the stresses at the nodes, and then use the mapping shape functions to interpolate the values if ever needed, but for the display this would not be necessary. My understanding is that evaluating the secondary variables at the integration points is only required when I am doing my numerical integration of the error estimators over the domain. That is why I needed the 4th order accuracy so I could show the proper convergence of the quadratic meshes by using a stress that varies by the third order (easily implementable in my code as a linear body force). That way I could state that my error estimator was exact since it was integrating at most third order functions.

**Comment by ibaned** [comment]
Yea, one part per integration point will show up. I'm going to close this since the original question seems to have been covered.

**Comment by YetAnotherMinion** [comment]
Ok the original problem is not solved. The suggested apf::creaeFieldOn is exactly a wrapper around what I was doing before:

```C++
Field* createFieldOn(Mesh* m, const char* name, int valueType)
{
  return createField(m,name,valueType,m->getShape()); 
}
```

I was doing `apf::createField(this->m, "name", apf::VECTOR, this->m->getShape())` before.
What I want to do is identify the values of the numbering that the specific field node is on. I need some way to connect the local node numberings to the global numbering of DOFs in the solution vector. 

I have array "node_mapping" which for a given element tells me which global dof it is. This is indexed by the local node numbers

```
				local node #   					Global dof #
node_mapping[         0           ]      =			37
node_mapping[         1           ]      =			38
node_mapping[         2           ]      =			61
node_mapping[         3           ]      =			62
node_mapping[         4           ]      =			63
node_mapping[         5           ]      =			66
node_mapping[         6           ]      =			67
node_mapping[         7           ]      =			68
node_mapping[         8           ]      =			69
node_mapping[         9           ]      =			90
```

All I need from the Field is to get the list of nodes on a dimension, so I go
```C++
if(this->f->hasNodesIn(dimension) {
  for(uint32_t ii = 0; ii < this->f->countNodesOn(e);++ii ) {
    int local_node_num =  this->f->magicMethodTakingFieldAndEnitityAndTellingMeWhatLocalNodeNumberIAmOn(int this_dimension_node_index, e)
   //then I can go to node_mapping and get displacement
   int global_dof = node_mapping[local_node_num];
   //from here I lookup the value I want to set on the field
   double tmp_value = this->solution[global_dof];
   apf::Vector3 tmp_vec(tmp>value, 0., 0.);
   apf::setVector(this->f, e, ii, tmp_vec);
  }
}
```

**Comment by ibaned** [comment]
this is going to be influenced by how you created "node_mapping", and whether this is in parallel. The answer is pretty obvious though: number your nodes. These two functions are usually the ones used:

https://github.com/SCOREC/core/blob/master/apf/apfNumbering.h#L104
https://github.com/SCOREC/core/blob/master/apf/apfNumbering.h#L113

just use apf::getNumber to get the number...

anyway those two functions build local numberings.
I don't know whether your global DOF numbers are different than local node numbers
because you're in parallel, but if thats the case then you can use apf::makeGlobal to get
a global numbering from a local one.

https://github.com/SCOREC/core/blob/master/apf/apfNumbering.h#L188

so now you have maps from nodes (entity pointers) to local numbers,
and from nodes to global numbers....

**Comment by YetAnotherMinion** [comment]
When I say local node numbering I mean the ordering of the nodes on that mesh element only.
Like so
```
          /*This is ordering of shape functions used below
          *      ^n
          *      |
          *   4--7--3
          *   |  |  |
          *   8  9--6--->e
          *   |     |
          *   1--5--2
          *
          *   indices are just above minus one
          */
```

**Comment by ibaned** [comment]
This is very much the wrong way to copy data back from a solution array to a field. Why iterate over all the elements and handle all the nodes of that element ? the vertex and edge nodes will be assigned multiple times for no good reason. its important to understand "affecting" versus "associated" nodes here. the vertex nodes (1,2,3,4) are "associated" to the vertex entities, even though they "affect" the quadrilateral entity. the code from your previous comment was actually more correct than what you're thinking: for every dimension that has nodes *associated* to its entities, process the associated nodes only. In the case of the quadrilateral, only node (9) is associated to it. There is a local numbering for associated nodes, so for the quadrilateral, "affecting" node (9) is actually "associated" node (0). that local integer is what gets passed to apf::getNumber as "int node":

https://github.com/SCOREC/core/blob/master/apf/apfNumbering.h#L67

that is how you map from nodes to numbers, and index into an array that came back from a linear solver.

**Comment by YetAnotherMinion** [comment]
^^That makes so much more sense. Implementing now.

**Comment by YetAnotherMinion** [comment]
That was the way to do it. Thank you for your speedy help!

**Comment by YetAnotherMinion** [comment]
When all you have is a hammer, every problem looks like a nail
