### ISSUE TITLE
non-manifold support of querying adjacent regions of a given edge

### ISSUE THREAD

**Issue by yangf4** [SCOREC/core#150]
I would like to get a set of regions adjacent to a given edge. But I got an error here:
https://github.com/SCOREC/core/blob/master/gmi_sim/gmi_sim.cc#L198

In my case, I do have a non-manifold model. But I am wondering if we can extend this function to support non-manifold model? What is the barrier?

**Comment by yangf4** [comment]
@mortezah 
@onkarsahni

**Comment by yangf4** [comment]
@mortezah   I am using Simmetrix mesh adaptation. Can you remove this constraint?

**Comment by mortezah** [comment]
@yangf4  I updated that functions so now it should work for non-manifold (multi-region) models.

Let me know if there are any problems.

**Comment by yangf4** [comment]
It works. Thank you @mortezah 

I am closing this issue.
