### ISSUE TITLE
what is the proper way to attach data with random-size to a mesh? 

### ISSUE THREAD

**Issue by yangf4** [SCOREC/core#152]
I have a data whose size is N*12. N is irrelevant to the number of entities of the mesh. I am wondering what is the proper way to attach this data to the mesh? 

This data comes from PHATSA and needs to be written to the "restart" file. 

The reason why I want to attach it to the mesh is that the chef pre-processor can read it from the mesh and write it to the "restart" files for PHASTA. I am thinking a similar way as this code:
https://github.com/SCOREC/core/blob/master/phasta/phRestart.cc#L329-L340

**Comment by maxrpi** [comment]
Is N constant for a given mesh?On May 27, 2018 2:48 PM, Fan <notifications@github.com> wrote:I have a data whose size is N*12. N is irrelevant to the number of entities of the mesh. I am wondering what is the proper way to attach this data to the mesh?
This data comes from PHATSA and needs to be written to the "restart" file.
The reason why I want to attach it to the mesh is that the chef pre-processor can read it from the mesh and write it to the "restart" files for PHASTA. I am thinking a similar way as this code:
https://github.com/SCOREC/core/blob/master/phasta/phRestart.cc#L329-L340
