### ISSUE TITLE
Compile-time output suppression

### ISSUE THREAD

**Issue by jacobmerson** [SCOREC/core#154]
Copying this over from https://github.com/tobinw/biotissue/issues/95

@tobinw 

We should be able to suppress all output to stdout at compile time. We should also have verbosity levels, but this should be done cleanly rather than through #ifdefs

Possibly a set of preprocessor macros like:

     V0(std::cout << "Verbosity level 0");
     V1(std::cout << "Verbosity level 1");

E.g. writing output for mesh reordering is not always wanted. (in biotissue/amsi we operate in a corner case where we have many meshes and it generates a lot of noise to stdout to print reordering stats)

**Comment by cwsmith** [comment]
One idea for this would be to create a no-op macro that replaces printf, cout, and friends at compile time.  I.e., [something like this](https://stackoverflow.com/a/5765197):

```C
#ifdef IGNORE_PRINTF
#define printf(fmt, ...) (0)
#endif
```

Clearly if there is any 'computation' in print statements there will be all sorts of problems - but that would just be exposing a bad practice.

**Comment by timetravellers** [comment]
Sorry about that...the idea is as follows:

A header looks like this:
```c++
#ifndef VERBOSITY_H_
  #ifdef VERBOSE_1
    #define V1(out) out
  #else
    #define V1(out) while(false);
  #endif
#endif
```

Usage looks like this:

```c++
V1(std::cout<<"Print something only when I want verbose outputs\n";)
V1( // do some computation only needed when verbose output needed
     std::cout<<"print something that needs computation\n";)
```

Multiple levels of verbosity can be added as wanted in the verbosity header file.

**Comment by cwsmith** [comment]
At the moment, IIRC, core has over 700 or so printf/cout calls.  We could try a fancy perl or sed regex find/replace...

**Comment by cwsmith** [comment]
[XSDK policy M11](https://figshare.com/articles/xSDK_Community_Package_Policies/4495136) says:

> M11​. No package should have hardwired print or I/O statements that cannot be turned off through a
programmatic interface ; output should never be hard-wired to stdout or stderr. It is recommended
that packages provide a way for users to turn on output and allow them to direct where it goes. Also,
packages may print to stdout by default but only on one process (i.e., root rank “0”). But packages
may also be completely silent by default (and require that users turn on outputting in the appropriate
way).

This branch https://github.com/cwsmith/core/tree/cws/control_print_stmts attempts to satisfy M11.  In the `lion` directory (previously was used for compressing io) is an interface for conditional print statements:
https://github.com/cwsmith/core/blob/7d3e2e2fc195568ecabe3990017e68e12e9dd7b0/lion/lionPrint.h

I've created a PR for discussion of this design: #183
