### ISSUE TITLE
apf::Field Reductions on Partition Boundaries

### ISSUE THREAD

**Issue by JaredCrean2** [SCOREC/core#159]
I have an apf::Field where each partition writes values to the field (including the mesh entities on the partition boundary that it might not own), and I want to make the field consistent in parallel by taking the *minimum* of the values on all partitions.  `apf::accumulate` almost does this, except that it sums rather than takes the minimum.  It looks like [accumulateFieldData](https://github.com/SCOREC/core/blob/master/apf/apfFieldData.cc#L84) could be modified to take a reduction operation as an argument.

I need something like this for my current research, so I am willing to do the work on this.  If you are amenable to generalizing `apf::accumulate` in this way, I can spell out my proposed approach in greater detail.

**Comment by JaredCrean2** [comment]
@cwsmith what do you think?

**Comment by cwsmith** [comment]
From a brief review of the code it sounds like we should define an `apfSharedReduction` that takes the different operators and them implement the current `accumulate` API using it.  Is that what you had in mind?

**Comment by JaredCrean2** [comment]
That's exactly what I was thinking.  Prototype implementation is [here](https://github.com/SCOREC/core/pull/160)

It defines an abstract `ReductionOp` type and then a few implementations for sum, min, and max.  I put these in `apf.h` because they need to be visible to functions in `apf.cc`, but they do clutter up the file.  Is there a better place for them?  They can't go in `apfFieldData.h` because then they wouldn't be visible in `apf.h` (`apf.h` is included by `apfFieldData.h`). 

The modified `accumulateFieldData` into `reduceFieldData` by adding a 4th argument that takes a `ReduceOp` and applies it to all the values at a node.  This requires doing a little more parallel communication, but avoids the need to do a second communication to broadcast the result back to the non-owner processes.
