### ISSUE TITLE
Verified Lagrange Quadratic Shape functions?

### ISSUE THREAD

**Issue by YetAnotherMinion** [SCOREC/core#16]
Have the second order Lagrange shape functions and their gradients been checked in any unit-tests?
I need to verify that they are actually correct, so if they have not been tested I will go ahead and write some tests for them.

**Comment by ibaned** [comment]
Well they get used in one major application and for the course homeworks. I probably checked them with some quick sampling back when I put them in place, but any testing you want to do to convince yourself they're sound would be appreciated.

**Comment by ibaned** [comment]
I should mention there is *some* nightly testing going on.

https://github.com/SCOREC/core/blob/master/test/shapefun.cc

Makes sure they are interpolating and that the volume of a sample element is properly integrated

**Comment by zaidedan** [comment]
There are also unit tests for 2nd order lagrange edges, tets, and triangles
as part of testing mesh curving.

https://github.com/SCOREC/core/blob/master/test/bezier1.cc#L250



On Thu, Aug 27, 2015 at 9:03 AM, Dan Ibanez <notifications@github.com>
wrote:

> I should mention there is *some* nightly testing going on.
>
> https://github.com/SCOREC/core/blob/master/test/shapefun.cc
>
> Makes sure they are interpolating and that the volume of a sample element
> is properly integrated
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SCOREC/core/issues/16#issuecomment-135417390>.
>



-- 
Dr. Daniel W. Zaide (偉明),
Researcher, Rensselaer Polytechnic Institute
B.A.Sc. University of Toronto (2007)
M.S.E, M.S. Ph.D., University of Michigan (2009,2011,2012)
www.danielzaide.com <http://www.danielzaide.com>

**Comment by zaidedan** [comment]
Give me a few hours and I'll update the shapefun.cc to handle second order
lagrange with some sort of test. Thats probably easiest.

On Thu, Aug 27, 2015 at 9:09 AM, Daniel Zaide <dan.zaide@gmail.com> wrote:

> There are also unit tests for 2nd order lagrange edges, tets, and
> triangles as part of testing mesh curving.
>
> https://github.com/SCOREC/core/blob/master/test/bezier1.cc#L250
>
>
>
> On Thu, Aug 27, 2015 at 9:03 AM, Dan Ibanez <notifications@github.com>
> wrote:
>
>> I should mention there is *some* nightly testing going on.
>>
>> https://github.com/SCOREC/core/blob/master/test/shapefun.cc
>>
>> Makes sure they are interpolating and that the volume of a sample element
>> is properly integrated
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/SCOREC/core/issues/16#issuecomment-135417390>.
>>
>
>
>
> --
> Dr. Daniel W. Zaide (偉明),
> Researcher, Rensselaer Polytechnic Institute
> B.A.Sc. University of Toronto (2007)
> M.S.E, M.S. Ph.D., University of Michigan (2009,2011,2012)
> www.danielzaide.com <http://www.danielzaide.com>
>



-- 
Dr. Daniel W. Zaide (偉明),
Researcher, Rensselaer Polytechnic Institute
B.A.Sc. University of Toronto (2007)
M.S.E, M.S. Ph.D., University of Michigan (2009,2011,2012)
www.danielzaide.com <http://www.danielzaide.com>

**Comment by YetAnotherMinion** [comment]
I was thinking of the ones for the quadratic quadrilateral that I wrote, My stiffness matrix routines are not symmetric for the quad case and are symmetric for the linear quadrilateral so I was wondering if I had messed up when I wrote the second order Lagrange quadratic, since they were only added 18 days ago

**Comment by YetAnotherMinion** [comment]
The nodal values pass. It is the gradients I am most worried about, since that is what we use to compute the element stiffness matrix

**Comment by zaidedan** [comment]
Give me a bit, I'm working on a test for everything, ever. Will make adding
shape function tests in the future easier.

On Thu, Aug 27, 2015 at 10:08 AM, Another Minion <notifications@github.com>
wrote:

> The nodal values pass. It is the gradients I am most worried about, since
> that is what we use to compute the element stiffness matrix
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SCOREC/core/issues/16#issuecomment-135446044>.
>



-- 
Dr. Daniel W. Zaide (偉明),
Researcher, Rensselaer Polytechnic Institute
B.A.Sc. University of Toronto (2007)
M.S.E, M.S. Ph.D., University of Michigan (2009,2011,2012)
www.danielzaide.com <http://www.danielzaide.com>

**Comment by ibaned** [comment]
Although its not the most general test, if I wanted to test gradients I'd make an element with strange node positions (not axis-aligned, curved edges) then put an analytic field on it, for example a scalar field f = 2x + 5y or something, and evaluate the gradient at several points (apf::getGrad). if that doesn't always return (2,5,0), you know something is wrong

**Comment by YetAnotherMinion** [comment]
How exactly do we change the position of the nodes on the edges for a quadratic element? What do I have to change in this code to specify the location of all nodes

```C++

	/*Batman element*/
	gmi_register_null();
	gmi_model* g = gmi_load(".null");
	apf::Mesh2* m = apf::makeEmptyMdsMesh(g, 2, false);
	//apf::changeMeshShape(m, apf::getLagrange(2));


	apf::MeshEntity** vertices = new apf::MeshEntity*[4];
	for(uint32_t counter = 0; counter < 4; counter++) {
		vertices[counter] = m->createVert(0);
	}
	/*this element is flipped upside down around x axis*/
	apf::Vector3 tmp_vec(1.35,2.36,0.0);
	m->setPoint(vertices[0], 0, tmp_vec);
	tmp_vec.x() = 2.57; tmp_vec.y() = 2.70;
	m->setPoint(vertices[1], 0, tmp_vec);
	tmp_vec.x() = 2.51; tmp_vec.y() = 1.75;
	m->setPoint(vertices[2], 0, tmp_vec);
	tmp_vec.x() = 1.64; tmp_vec.y() = 1.28;
	m->setPoint(vertices[3], 0, tmp_vec);

	// tmp_vec.x() = 2.09; tmp_vec.y() = 2.36;
	// m->setPoint(vertices[4], 0, tmp_vec);
	// tmp_vec.x() = 2.73; tmp_vec.y() = 2.25;
	// m->setPoint(vertices[5], 0, tmp_vec);
	// tmp_vec.x() = 2.01; tmp_vec.y() = 1.72;
	// m->setPoint(vertices[6], 0, tmp_vec);
	// tmp_vec.x() = 1.15; tmp_vec.y() = 1.77;
	// m->setPoint(vertices[7], 0, tmp_vec);

	// tmp_vec.x() = 1.90; tmp_vec.y() = 2.05;
	// m->setPoint(vertices[8], 0, tmp_vec);

	apf::buildElement(m, NULL, apf::Mesh::QUAD, vertices);

	apf::deriveMdsModel(m);
	m->acceptChanges();
	m->verify();
	apf::writeVtkFiles("batman_elm", m);
	delete[] vertices;

	m->destroyNative();
	apf::destroyMesh(m);
```

**Comment by zaidedan** [comment]
your shape functions appear to pass my preliminary tests

On Thu, Aug 27, 2015 at 11:06 AM, Another Minion <notifications@github.com>
wrote:

> How exactly do we change the position of the nodes on the edges for a
> quadratic element? What do I have to change in this code to specify the
> location of all nodes
>
>     /*Batman element*/
>     gmi_register_null();
>     gmi_model* g = gmi_load(".null");
>     apf::Mesh2* m = apf::makeEmptyMdsMesh(g, 2, false);
>     //apf::changeMeshShape(m, apf::getLagrange(2));
>
>
>     apf::MeshEntity** vertices = new apf::MeshEntity*[4];
>     for(uint32_t counter = 0; counter < 4; counter++) {
>         vertices[counter] = m->createVert(0);
>     }
>     /*this element is flipped upside down around x axis*/
>     apf::Vector3 tmp_vec(1.35,2.36,0.0);
>     m->setPoint(vertices[0], 0, tmp_vec);
>     tmp_vec.x() = 2.57; tmp_vec.y() = 2.70;
>     m->setPoint(vertices[1], 0, tmp_vec);
>     tmp_vec.x() = 2.51; tmp_vec.y() = 1.75;
>     m->setPoint(vertices[2], 0, tmp_vec);
>     tmp_vec.x() = 1.64; tmp_vec.y() = 1.28;
>     m->setPoint(vertices[3], 0, tmp_vec);
>
>     // tmp_vec.x() = 2.09; tmp_vec.y() = 2.36;
>     // m->setPoint(vertices[4], 0, tmp_vec);
>     // tmp_vec.x() = 2.73; tmp_vec.y() = 2.25;
>     // m->setPoint(vertices[5], 0, tmp_vec);
>     // tmp_vec.x() = 2.01; tmp_vec.y() = 1.72;
>     // m->setPoint(vertices[6], 0, tmp_vec);
>     // tmp_vec.x() = 1.15; tmp_vec.y() = 1.77;
>     // m->setPoint(vertices[7], 0, tmp_vec);
>
>     // tmp_vec.x() = 1.90; tmp_vec.y() = 2.05;
>     // m->setPoint(vertices[8], 0, tmp_vec);
>
>     apf::buildElement(m, NULL, apf::Mesh::QUAD, vertices);
>
>     apf::deriveMdsModel(m);
>     m->acceptChanges();
>     m->verify();
>     apf::writeVtkFiles("batman_elm", m);
>     delete[] vertices;
>
>     m->destroyNative();
>     apf::destroyMesh(m);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SCOREC/core/issues/16#issuecomment-135463037>.
>



-- 
Dr. Daniel W. Zaide (偉明),
Researcher, Rensselaer Polytechnic Institute
B.A.Sc. University of Toronto (2007)
M.S.E, M.S. Ph.D., University of Michigan (2009,2011,2012)
www.danielzaide.com <http://www.danielzaide.com>

**Comment by ibaned** [comment]
after calling m->acceptChanges, change the shape to be your second-order Lagrange shape (with apf::changeMeshShape), then use m->getDownward(quad, 1, edges) to get the edges, and use m->setPoint(edges[i], 0, x) to move the mid-edge nodes. m->setPoint(quad, 0, x) for the mid-quad node.

**Comment by zaidedan** [comment]
I just pushed a new shape function test, that tries to test everything it
can.

https://github.com/SCOREC/core/blob/master/test/shapefun2.cc

It takes four shape function types, and for every entity type they are
defined on, checks the jacobian, the volume, and a point location on a
reference element, and makes sure it gives the same result as the base,
first order mesh for two locations in parameter space.

On Thu, Aug 27, 2015 at 11:09 AM, Dan Ibanez <notifications@github.com>
wrote:

> after calling m->acceptChanges, change the shape to be your second-order
> Lagrange shape (with apf::changeMeshShape), then use m->getDownward(quad,
> 1, edges) to get the edges, and use m->setPoint(edges[i], 0, x) to move the
> mid-edge nodes. m->setPoint(quad, 0, x) for the mid-quad node.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SCOREC/core/issues/16#issuecomment-135463867>.
>



-- 
Dr. Daniel W. Zaide (偉明),
Researcher, Rensselaer Polytechnic Institute
B.A.Sc. University of Toronto (2007)
M.S.E, M.S. Ph.D., University of Michigan (2009,2011,2012)
www.danielzaide.com <http://www.danielzaide.com>

**Comment by YetAnotherMinion** [comment]
I tested the gradients with [this](https://gist.github.com/YetAnotherMinion/5d09e143d695336f83d5), and they passed. I guess the problem lies in my computation of the nodal stiffness matrices somewhere, although I use the same code looping over all of the nodes, all that is changed is the mesh shape functions to a higher order.

**Comment by zaidedan** [comment]
I tested your functions as well, by putting the field as the mesh shape and
evaluating its area and jacobian. I also tested every other interpolating
shape function while I was at it. Either way, good to know.

On Thu, Aug 27, 2015 at 5:12 PM, Another Minion <notifications@github.com>
wrote:

> I tested the gradients with this
> <https://gist.github.com/YetAnotherMinion/5d09e143d695336f83d5>, and they
> passed. I guess the problem lies in my computation of the nodal stiffness
> matrices somewhere, although I use the same code looping over all of the
> nodes, all that is changed is the mesh shape functions to a higher order.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SCOREC/core/issues/16#issuecomment-135556100>.
>



-- 
Dr. Daniel W. Zaide (偉明),
Researcher, Rensselaer Polytechnic Institute
B.A.Sc. University of Toronto (2007)
M.S.E, M.S. Ph.D., University of Michigan (2009,2011,2012)
www.danielzaide.com <http://www.danielzaide.com>
