### ISSUE TITLE
copy constructors for apf::mesh and apf::Numbering

### ISSUE THREAD

**Issue by timetravellers** [SCOREC/core#162]
I need to copy a mesh and numbering.

I did not find a convenient way of copying an apf numbering. Does anything exist? Or should I implement something and submit a pull request?

For the mesh I can use `apf::createMdsMesh(model, mesh)` which works for my use case, however it seems like there should be a function `apf::copyMesh` which either does the same, or copies all of the underlying fields as well.

**Comment by cwsmith** [comment]
Does the copied numbering need to exist on the copied mesh or on the original mesh?

If the new numbering is needed on the copied mesh than `convert`:

https://github.com/SCOREC/core/blob/5198f7de40b78bc96a79f688d7b2aaae61c614a6/apf/apfConvert.h#L23-L28

should work.  Note, I have only seen this used for mds -> simmetrix, but it should work fine for mds -> mds.

**Comment by timetravellers** [comment]
I tried using the convert function which seems to crash because my mesh already has fields on it e.g.
convert calls:

https://github.com/SCOREC/core/blob/d2fbb260332408b4938762bd4cb5a69933ac7651/apf/apf.cc#L124-L128
which in turn calls:
https://github.com/SCOREC/core/blob/d2fbb260332408b4938762bd4cb5a69933ac7651/apf/apfFieldData.cc#L13-L16

Is there a known work around?

**Comment by cwsmith** [comment]
I'm not sure why clone is not implemented.  @tobinw, any insight into this?  Assuming there are no gotcha's implementing it would be the 'right' thing to do.

It looks like the conversion functions for numberings:

https://github.com/SCOREC/core/blob/3c004b6247561164fb32b7332dc9870bcf5cc4c9/apf/apfConvert.cc#L168

is a simple iteratation over the mesh and copy and should work.

**Comment by tobinw** [comment]
No idea why ```FieldData::clone()``` is unimplemented offhand other than it hasn't been needed yet possibly.

I can definitely take a look at this later in the week but I'm currently recovering from a wrist injury which makes typing take FOREVER.

**Comment by timetravellers** [comment]
I need this to move forward with what I am working on, so I will implement and submit a pull request.

**Comment by timetravellers** [comment]
As a note for something that needs to be fixed before this gets closed. The `convertNumbering` and `convertGlobalNumbering` functions do not properly set the field of the numbering.

https://github.com/SCOREC/core/blob/d2fbb260332408b4938762bd4cb5a69933ac7651/apf/apfConvert.cc#L168-L212

**Comment by timetravellers** [comment]
Also, the convert function does not deal with tags. I will add in this functionality to my pull request tomorrow.

**Comment by cwsmith** [comment]
merged
