### ISSUE TITLE
Ghosts and Copies

### ISSUE THREAD

**Issue by JaredCrean2** [SCOREC/core#164]
This question came out of the debugging process for #161, which got reverted because it doesn't work correctly for meshes with ghost entities.

Questions:
  1) Can a `MeshEntity*` be both on a partition boundary and a ghost?
  2) Can a `MeshEntity*` have `apf::Matches` and be a ghost?
  2) If so, do ghosts keep track of their copies (what is the output of `shr->getCopies(e, copies)`, where `shr` is an `apf::Sharing*`)?

**Comment by cwsmith** [comment]
@JaredCrean2 I'm going to revert #161 while we resolve this.

**Comment by seegyoung** [comment]
> Can a MeshEntity* be both on a partition boundary and a ghost?
A ghost is an off-part entity copied on local part. A part boundary entity is any entity shared by  multiple parts. So the answer is YES. For instance, a part boundary entity "e" shared by parts "x" & "y" can be a ghost on part "z".

> Can a MeshEntity* have apf::Matches and be a ghost? If so, do ghosts keep track of their copies (what is the output of shr->getCopies(e, copies), where shr is an apf::Sharing*)?
Currently, we do not support ghosting for matched mesh.

Please let me know if you have any further question.

**Comment by JaredCrean2** [comment]
I see, thanks for the clarification.  I think I know what the problem is now.  I will update the branch from #161  in the next day or two.
