### ISSUE TITLE
Questions on coordinates/parameters functions

### ISSUE THREAD

**Issue by kumargp** [SCOREC/core#166]
I will need these functions in future. I want to check if these functions exist in core, before developing it ?.
1. Do core has function for computing  barycentric coordinates?

> Morteza's comment: 
> " getParam gives you the parametric coordinates of the point on the "model boundary". That is different from the barycentric coordiantes on a triangle."

  Are there general algorithms for the following:
2. To get parameters of the plane formed by a triangular face
3. To help calculate the intersection point of a plane by a ray
4. Or, better, to check if a line segment intersects a triangular face.

**Comment by tobinw** [comment]
Computing the barycentric coordinates... from what? Global coords?

**Comment by kumargp** [comment]
The coordinates from getPoint() is used to make vectors relative to the first vertex. Then area/volume is calculated.

**Comment by tobinw** [comment]
So my understanding is you have a global coordinate (the "first" vertex in canonical ordering) plus a displacement vector and you want to get the barycentric coordinates at that offset point? In general that just means that we have a global coordinate and wanting to invert the usual barycentric->euclidean mapping we work with in FEA. 

In general this is not a simple inversion, in particular cases it can be relatively (mathematically) simple to compute, but unless I'm wrong pumi/core has no general mechanism to perform this inversion. I have previously used some functions from SCOREC/core/ma to calculate barycentric coordinates for points lying inside linear tetrahedrons where I could guarantee the point lay inside the tet, but the interface isn't public-facing.

**Comment by kumargp** [comment]
Thanks. I will check the function.
About barycentric coordinate, yes, one of the points will be outside the element for most of the searches. The "first" point (I wrote) is not strictly true. You know, it is taking difference to get vectors, so it is w.r.t the subtracted point.

I have (and Eisung has) implementation for this. I was trying to check if I am repeating any existing capability. In general,  when I implement it, it can be customized. In this case, the calculation is first checking if any of the 3 values is negative. If so, return. This will save 2/3 of the computation on the average.

**Comment by cwsmith** [comment]
I assume this is resolved. Please reopen if not.
