### ISSUE TITLE
compilation on RSA

### ISSUE THREAD

**Issue by yangf4** [SCOREC/core#171]
I have some trouble when compiling the core code on RPI RSA.

I am using mvapich2. Before configuring, I have module loaded the following:
  1) mpi/mvapich2-2.0a-gcc44/2            3) zoltan/mvapich2-2.0a-gcc44/3.7          5) cmake/3.9.1
  2) parmetis/mvapich2-2.0a-gcc44/4.0.2   4) simmetrix/simModSuite/12.0-180811 (T)

And my configuring file is like:

cmake .. \
  -DCMAKE_C_COMPILER="mpicc" \
  -DCMAKE_CXX_COMPILER="mpicxx" \
  -DSIM_MPI="mvapich2-2.0.1_1" \
  -DCMAKE_PREFIX_PATH="/gpfs/u/software/amd64-rhel6/modulefiles/.gcc/6.2.0_1/.mvapich2/2.0.1_1/parmetis;/gpfs/u/software/amd64-rhel6/modulefiles/.gcc/6.2.0_1/.mvapich2
/2.0.1_1/zoltan;/gpfs/u/software/amd64-rhel6/simmetrix/12.0-180811/lib/x64_rhel6_gcc44/" \
  -DENABLE_ZOLTAN=ON \
  -DCMAKE_INSTALL_PREFIX=$PWD/install/ \
  -DENABLE_SIMMETRIX=True \
  -DENABLE_FIELDSIM=True \
  -DSIM_PARASOLID=True \
  -DPCU_COMPRESS=True \
  -DPUMI_FORTRAN_INTERFACE=ON \
  -DCMAKE_Fortran_COMPILER="mpif90" \
  ..

But when I tried to compile the core code, I have the following error:

-- ENABLE_ZOLTAN: ON
CMake Error at cmake/FindParmetis.cmake:12 (message):
  parmetis include dir not found
Call Stack (most recent call first):
  cmake/FindZoltan.cmake:20 (find_package)
  zoltan/CMakeLists.txt:23 (find_package)

Can anybody help me out on this? Thank you in advance.

**Comment by cwsmith** [comment]
The `CMAKE_PREFIX_PATH` is incorrect:

Using the `module show` command I see that `[ZOLTAN|PARMETIS]_INSTALL_DIR` is set and the simmetrix module sets `CMAKE_PREFIX_PATH`.  

```
$ module show parmetis/mvapich2-2.0a-gcc44/4.0.2 
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   /gpfs/u/software/x86-rhel6/modulefiles/parmetis/mvapich2-2.0a-gcc44/4.0.2:
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
whatis("ParMETIS 4.0.2 built with mvapich2-2.0a-gcc44 compilers for the Intel cluster ")
prereq_any("mpi/mvapich2-2.0a-gcc44")
setenv("PARMETIS_INSTALL_DIR","/gpfs/u/software/x86-rhel6/parmetis/mvapich2-2.0a-gcc44/4.0.2/")

module show zoltan/mvapich2-2.0a-gcc44/3.7
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   /gpfs/u/software/x86-rhel6/modulefiles/zoltan/mvapich2-2.0a-gcc44/3.7:
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
whatis("Zoltan 3.7 built with mvapich2-2.0a-gcc44 compilers for the Intel cluster ")
prereq_any("mpi/mvapich2-2.0a-gcc44")
setenv("ZOLTAN_INSTALL_DIR","/gpfs/u/software/x86-rhel6/zoltan/mvapich2-2.0a-gcc44/3.7")

module show simmetrix/simModSuite/12.0-180811 
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   /gpfs/u/software/amd64-rhel6/modulefiles/simmetrix/simModSuite/12.0-180811.lua:
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
help([[Simmetrix SimModSuite version 12.0-180811
]])
whatis("Name: Simmetrix SimModSuite")
whatis("Module: simmetrix/simModSuite/12.0-180811")
whatis("Description: Simmetrix SimModSuite C++ libraries")
whatis("Version: 12.0-180811")
whatis("URL: http://www.simmetrix.com/")
whatis("Keyword: simmetrix")
add_property("state","testing")
family("simmetrix")
prepend_path("LD_LIBRARY_PATH","/gpfs/u/software/amd64-rhel6/simmetrix/12.0-180811/lib/x64_rhel6_gcc44/acisKrnl")
prepend_path("LD_LIBRARY_PATH","/gpfs/u/software/amd64-rhel6/simmetrix/12.0-180811/lib/x64_rhel6_gcc44/psKrnl")
prepend_path("CMAKE_PREFIX_PATH","/gpfs/u/software/amd64-rhel6/simmetrix/12.0-180811")
prepend_path("CMAKE_PREFIX_PATH","/gpfs/u/software/amd64-rhel6/simmetrix/12.0-180811/lib/x64_rhel6_gcc44")
prepend_path("CMAKE_PREFIX_PATH","/gpfs/u/software/amd64-rhel6/simmetrix/12.0-180811/lib/x64_rhel6_gcc44/acisKrnl")
prepend_path("CMAKE_PREFIX_PATH","/gpfs/u/software/amd64-rhel6/simmetrix/12.0-180811/lib/x64_rhel6_gcc44/psKrnl")
setenv("SIM_LICENSE_FILE","/gpfs/u/software/amd64-rhel6/simmetrix/license/license.txt")
setenv("SIM_INSTALL_DIR","/gpfs/u/software/amd64-rhel6/simmetrix/12.0-180811")
setenv("P_SCHEMA","/gpfs/u/software/amd64-rhel6/simmetrix/12.0-180811/lib/x64_rhel6_gcc44/psKrnl/schema")

```

So, based on that passing:

```
-DCMAKE_PREFIX_PATH="${ZOLTAN_INSTALL_DIR};${PARMETIS_INSTALL_DIR};${CMAKE_PREFIX_PATH}"
```

Should work.  If not (I'm not 100% on the use of semicolons and how `${CMAKE_PREFIX_PATH}` will expand from the simmetrix module), then try removing the `-DCMAKE_PREFIX_PATH` arg from the cmake command and run

```
export CMAKE_PREFIX_PATH=${ZOLTAN_INSTALL_DIR};${PARMETIS_INSTALL_DIR};${CMAKE_PREFIX_PATH}
```
in your terminal before running cmake .

**Comment by yangf4** [comment]
Changing CMAKE_PREFIX_PATH doesn't work. I still get the same error. Then I tried to export. This was what I got:

[MCFDfnyn@rsa35 rsa_build]$ export CMAKE_PREFIX_PATH=${ZOLTAN_INSTALL_DIR};${PARMETIS_INSTALL_DIR};${CMAKE_PREFIX_PATH}
-bash: /gpfs/u/software/x86-rhel6/parmetis/mvapich2-2.0a-gcc44/4.0.2/: No such file or directory
-bash: /gpfs/u/software/x86-rhel6/zoltan/mvapich2-2.0a-gcc44/3.7: is a directory

**Comment by cwsmith** [comment]
Whoops.  There are semicolons in the `export` command that need to be colons:

```
export CMAKE_PREFIX_PATH=${ZOLTAN_INSTALL_DIR}:${PARMETIS_INSTALL_DIR}:${CMAKE_PREFIX_PATH}
```

**Comment by yangf4** [comment]
I still get the same error when configuring: 
CMake Error at cmake/FindParmetis.cmake:12 (message):
  parmetis include dir not found
Call Stack (most recent call first):
  cmake/FindZoltan.cmake:20 (find_package)
  zoltan/CMakeLists.txt:23 (find_package)

After I echo $CMAKE_PREFIX_PATH, I got: 
[MCFDfnyn@rsa35 rsa_build]$ echo $CMAKE_PREFIX_PATH
/gpfs/u/software/x86-rhel6/zoltan/mvapich2-2.0a-gcc44/3.7:/gpfs/u/software/x86-rhel6/parmetis/mvapich2-2.0a-gcc44/4.0.2/:/gpfs/u/software/x86-rhel6/zoltan/mvapich2-2.0a-gcc44/3.7:/gpfs/u/software/x86-rhel6/parmetis/mvapich2-2.0a-gcc44/4.0.2/:/gpfs/u/software/x86-rhel6/zoltan/mvapich2-2.0a-gcc44/3.7:/gpfs/u/software/x86-rhel6/parmetis/mvapich2-2.0a-gcc44/4.0.2/:/gpfs/u/software/amd64-rhel6/simmetrix/12.0-180811/lib/x64_rhel6_gcc44/psKrnl:/gpfs/u/software/amd64-rhel6/simmetrix/12.0-180811/lib/x64_rhel6_gcc44/acisKrnl:/gpfs/u/software/amd64-rhel6/simmetrix/12.0-180811/lib/x64_rhel6_gcc44:/gpfs/u/software/amd64-rhel6/simmetrix/12.0-180811

But it seems to me that we don't have such directory "/gpfs/u/software/x86-rhel6/parmetis/".

**Comment by cwsmith** [comment]
Thanks @yangf4.  I'll check to see if the install was moved.  If it does not still exist I'll reinstall it.

**Comment by cwsmith** [comment]
The following module commands should get you set up:

module load gcc/6.2.0_1
module load mvapich2
module load parmetis/4.0.3 zoltan/3.8

These newer modules apppend to `CMAKE_PREFIX_PATH`, so you can skip running the `export` command and passing `-DCMAKE_PREFIX_PATH` to the `cmake` command.

I removed many old modules that have newer LMod modules defined in the `/gpfs/u/software/amd64-rhel6/modulefiles` directory.

**Comment by cwsmith** [comment]
an openmpi stack is now available:

`module load gcc/6.3.0_1 openmpi/2.1.1_1 parmetis zoltan pumi`
