### ISSUE TITLE
Adding Chef option to skip adaptation of the boundary layer mesh

### ISSUE THREAD

**Issue by hapfang** [SCOREC/core#177]
The current Chef adapt seems to adapt the entire mesh as long as a size field is provided. When there is boundary layer (BL) mesh, the Chef adapt will automatically do the adaptation of BL as well. This is not always desired because sometimes the user would want to preserve the BL structure (to better resolve certain flow physics), and only adapt the mesh outside the BL region. It will be great if Chef could provide users the option whether or not to adapt the BL region.

**Comment by KennethEJansen** [comment]
Not sure if my memory is correct but I thought at one point this was controlled by element topology.  If the boundary layer was left as wedges then the wedges would not be adapted and only the tets would get adapted.  

Jun did you try this with a wedge BL mesh and if yes, did it adapt the wedges too?

**Comment by hapfang** [comment]
Yes Ken, I think you are right. The Chef adapt wouldn't adapt the prism-cell BL mesh. However, I encountered a redistancing issue on the mixed mesh. Have to look into it tomorrow.

**Comment by KennethEJansen** [comment]
It is likely possible, though not ideal, to tetrahedronize after each adapt if we cannot make the redistancing work better on mixed meshes.  Certainly some of Meredith’s more recent work was restricted to all tet meshes so we will have to look at how hard that is to make work on mixed meshes vs. having an extra tetrahedronizing step.

---------------------------------------------------------------- 
Kenneth E. Jansen, Professor 
Ann and H.J. Smead Department of Aerospace Engineering Sciences
ECAE 161                                   OFFICE (303) 492-4359 
429 UCB                                      FAX  (303) 492-4990 
University of Colorado at Boulder          jansenke@colorado.edu 
Boulder, CO, 80309-0429        http://www.colorado.edu/aerospace 
----------------------------------------------------------------

**Comment by KennethEJansen** [comment]
Thanks Gopan.   However, this version is not using Simmetrix adapt, rather it is using SCOREC adapt.

We are still working on getting Simmetrix adapt to work with modern SCOREC/core tools (we have an ancient version that does work).

If you have a working code with examples we will take a look to see if that can accelerate our progress down that path.  I think Jun has been looking at Fan’s work in that area that he grabbed about 6 months ago.  If there has been progress it might make sense for us to take a look at the more up-to-date work.

Best regards,
 
---------------------------------------------------------------- 
Kenneth E. Jansen, Professor 
Ann and H.J. Smead Department of Aerospace Engineering Sciences
ECAE 161                                   OFFICE (303) 492-4359 
429 UCB                                      FAX  (303) 492-4990 
University of Colorado at Boulder          jansenke@colorado.edu 
Boulder, CO, 80309-0429        http://www.colorado.edu/aerospace 
----------------------------------------------------------------

**Comment by kumargp** [comment]
Hi Ken, Thanks for the info. No, I don't have the code. I am exploring Simmetrix capabilities for mesh creation and adaptation, whether the GUI has implemented those, and if GUI can be used for complex mesh creation etc.

**Comment by cwsmith** [comment]
Closing this issue.  [Ken's response](https://github.com/SCOREC/core/issues/177#issuecomment-419726450) is correct.  There is a `splitAllLayerEdges` flag in meshadapt and chef but that is specific to uniform refinement.  https://github.com/SCOREC/core/commit/611272d2ae46ca1c6868ca0a5866585c0a43afcb
