### ISSUE TITLE
Chef hangs on BGQ after "mesh expanded; mesh migrated"

### ISSUE THREAD

**Issue by skinnerr** [SCOREC/core#178]
- The mesh: 461,522,792 tets on 16k parts, which is the result of performing a uniform refinement of an unadapted/unrefined original all-tet mesh.

- I plan on running a simulation using this mesh on 2k nodes on BGQ, however...

- Partitioning from 16k to 128k with Chef hangs. I first tried this on Cetus with 2048 nodes for 60 minutes. No errors were printed and the last things written to output were as follows; the last lines of the *.output file were written in the first 10 minutes of the job, i.e. Chef printed nothing in the last 50 minutes of the job:
>planned Zoltan split factor 8 to target imbalance 1.010000 in 1.085291 seconds
>mesh expanded from 16384 to 131072 parts in 1.954304 seconds
>mesh migrated from 16384 to 131072 in 17.862693 seconds
>[end of *.output file]

- I had encountered a similar issue when I was partitioning the original mesh from 256 to 16k (split factor = eight) in the first place. I experienced the same hang (after "mesh expanded; mesh migrated") when I used 512 nodes at 32 processes/node. However, when I then ran on 1024 nodes at 16 processes/node, the entire job finished in 20 minutes successfully.

- Thus, to address my current issue of partitioning from 16k to 128k (similary, split factor = eight), I submitted a 4096-node job on Mira and it also hung with the same behavior after "mesh expanded; mesh migrated" (I killed it after 4hr 30min). Note this means 32 parts/node, unlike the 16 parts/node that solved my problem earlier.

- Since I intend on running on a most 2k nodes, it seems strange that I would need to submit a 4x-larger 8k node job just to partition the mesh. Ken agrees this is strange behavior.

Happy to provide more details on request here or via Slack.

If this sounds familiar (e.g. a bug that's already been fixed), let me know. I have been using Riccardo's BGQ executable which may not be the *most* recent version of Chef.

**Comment by skinnerr** [comment]
I will give information on the path, the next line of output, and my adapt.inp when ALCF is returned to service after today's maintenance period.

**Comment by skinnerr** [comment]
Additionally, I'll offer an example below of what I would expect the output to look like if Chef did not hang. When Chef hangs as I've experienced it, it only prints the first two lines of the following.
```
mesh expanded from 2048 to 16384 parts in 1.137093 seconds
mesh migrated from 2048 to 16384 in 10.539007 seconds
planned Zoltan balance to target imbalance 1.030000 in 13.003503 seconds
Zoltan balanced to 1.030000 in 15.177518 seconds
mesh reordered in 0.234836 seconds
generated output structs in 0.713312 seconds
solution written in 14.629614 seconds
mesh bz2:mdsMesh_bz2/ written in 16.259543 seconds
geombc file written in 14.270672 seconds
geombc file written in 52.998426 seconds
mesh verified in 754.641829 seconds
Fri Jul 13 00:48:15 UTC 2018
```

**Comment by KennethEJansen** [comment]
Ryan,

Cameron and I met and discussed this.  From the logs it looks like you are getting partitioners that are different than what you are requesting and this is likely due to your use of a very old, possibly hacked up version of chef that we used for the HighLift Prediction workshop.  Please try your runs with current versions of software.  I know Jun has more recent versions that you can try.  I might too. YOu should also learn to build your own if you don’t already know how.  Riccardo can probably show you.  In general, it can be very dangerous to use random versions of software that you don’t know what hacks have been applied.
---------------------------------------------------------------- 
Kenneth E. Jansen, Professor 
Ann and H.J. Smead Department of Aerospace Engineering Sciences
ECAE 161                                   OFFICE (303) 492-4359 
429 UCB                                      FAX  (303) 492-4990 
University of Colorado at Boulder          jansenke@colorado.edu 
Boulder, CO, 80309-0429        http://www.colorado.edu/aerospace 
----------------------------------------------------------------

**Comment by skinnerr** [comment]
I cloned SCOREC/core and built my own up-to-date version of Chef on Cetus. I had to comment out the assert on line 70 of `phiotimer.cc` regarding a `clock_gettime(CLOCK_MONOTONIC,t);` error. This current version of Chef runs now, but is encountering the exact same out-of-memory issues as described at the beginning of this ticket. So far, I have tried partitoning 16k to 64k parts on 1k nodes of Cetus, and it dies in the same place as before (just after "mesh expanded; mesh migrated") with the error `***Memory allocation failed for gk_mcoremalloc: ptr. Requested size: 519440192 bytes   Current memory used:     8494292 bytes`. I have submitted a 2k node job and will report back with the results.

When I compiled this up-to-date version, I cloned this GitHub repo and then set up my environment per `/home/skinnerr/SCOREC-core/compilation/env_mira_XL_cws`, ran cmake with `/home/skinnerr/SCOREC-core/compilation/doConfigure_mira_XL_OptG`, and then did the usual make.

To clarify, the only thing I have changed that warrants this post is running a current `master` version of the Chef executable, instead of one that may have been hacked up for HLPW3 two years ago.

**Comment by cwsmith** [comment]
Re: phiotimer.cc

The following logic will select the correct timer on the BGQ:
https://github.com/SCOREC/core/blob/d2fbb260332408b4938762bd4cb5a69933ac7651/phasta/CMakeLists.txt#L73-L76

What is the git hash of your scorec/core source?

What is the path to your build?

**Comment by skinnerr** [comment]
Got it, thanks for clarification on timer and memory usage, Cameron.

Chef run directory path: /projects/TRAssembly_2/skinnerr/NGC/series14.7.0/mesh_32M/64kUR-16kUR-Chef-DDES-ts122000

Git hash: f12a2cfa9aeb72e188a8c6c23f734534598f58fa

My 2k-node job on Cetus also died with a memory error, which seems to be expected due to requesting more than 512MB or memory. I've submitted a 4k-node job on Mira and we'll see when it gets through the queue.

**Comment by cwsmith** [comment]
According to the table, if you have `BG_MAPCOMMONHEAP=1` set in your job's environment, then your 4Ki node job will place 16 processes per node at you'll have at least 941MB per process.  I'm surprised it failed.  Do you have `BG_MAPCOMMONHEAP=1` being passed to runjob in your scripts?

**Comment by skinnerr** [comment]
That may be the answer. I was not passing `BG_MAPCOMMONHEAP`, but have resubmitted my 4Ki node job with that environment variable set. I'll update you when it has run.

**Comment by cwsmith** [comment]
IIRC, that setting cannot simply be exported, it needs to be passed to `runjob` or `qsub` with some `--env` flag:

https://www.alcf.anl.gov/user-guides/running-jobs-bgq#environment-variables

**Comment by skinnerr** [comment]
Yep, that's what I've done. Sorry, I could have been more explicit. That's the website I looked at just now too. Will update once job runs.

**Comment by skinnerr** [comment]
Even with `BG_MAPCOMMONHEAP=1` set in my following runjob command, I observe the same crash.
```
runjob -n $processes -p $processpernode --block $COBALT_PARTNAME --verbose=INFO --envs BG_MAPCOMMONHEAP=1 --envs SIM_LICENSE_FILE=/home/mrasquin/Simmetrix/license.txt --envs BG_SHAREDMEMSIZE=64MB --envs PAMID_VERBOSE=1 --envs PAMI_MAX_COMMTHREADS=0 --envs PAMID_ASYNC_PROGRESS=0 --envs PAMID_CONTEXT_POST=1 --envs BG_THREADMODEL=1 --envs BG_COREDUMPONERROR=1 :     $executable $file
```
I am traveling now but will be back on Monday and will look into whether any of these other options might be conflicting and limiting memory usage by a process. If anything stands out, please let me know. In the meantime, I have submitted another 4k-node job with `partitionMethod rib` set in `adapt.inp`.

**Comment by skinnerr** [comment]
After reading documentation online, it doesn't look like there are any issues with conflicting BGQ arguments in the call to `runjob`.

A slip-up on my part, I did today realize that `RecursiveUR 1` was set in my `adapt.inp` up to this point, which I have since fixed (I had already done the desired UR in a previous, successful Chef step as discussed at the beginning of this ticket). With `RecursiveUR 0` set now, I still run into the familiar memory allocation error after "mesh expanded; mesh migrated" when running on both 2Ki and 4Ki nodes. The behavior is also unchanged when I set `LocalPtn 1` (this is what disabled global partitioning, right?), though it does reduce the size of the memory request that results in an error from 519MB to 508MB. Keep in mind this all occurs with `--envs BG_MAPCOMMONHEAP=1` set in the call to `runjob`.

Jun was kind enough to take a look at my case at ALCF. He said that the memory issue I'm encountering seems "really unexpected" after looking over my case at `/projects/TRAssembly_2/skinnerr/NGC/series14.7.0/mesh_32M/64kUR-16kUR-Chef-DDES-ts122000`, but couldn't pinpoint anything out of the ordinary with my set-up or workflow. This echoes Cameron's "I'm surprised it failed," above.

If I'm interpreting them correctly, all the diagnostic messages that print (at least on Cetus, see `/projects/TRAssembly_2/skinnerr/NGC/series14.7.0/mesh_32M/64kUR-16kUR-Chef-DDES-ts122000/1639780.error`) say that the maximum memory usage for processes is only around 10MB before the ~508-519MB is requested. As you say above, Cameron, the 4Ki node job will place 16 processes per node (meaning at least 941MB memory per process). I don't understand why it can't take advantage of all that memory that theoretically exists. Would anything (e.g. my environment) impact the amount of memory available to my processes here?

After a week of trying to figure this out I am at a loss and would like to sit down with you (Cameron and/or Ken) over Slack, or at least get a second opinion on trying to get the desired end-result, e.g., see if you are able to get a successful partition of this case going, starting from my files but working in your own environment(s). Getting that end result (the 64k-partitioned mesh) is the final goal, as I will run at that part count.

**Comment by cwsmith** [comment]
The `RecursiveUR` flag is only used with adaptStategy 6 (`adaptLevelSet(...)`)... for some reason.  I thought it was deprecated.
```
/home/skinnerr/SCOREC-core/core (master)$ grep -ri recursiveur .
./phasta/phAdapt.cc:    ma::Input* ma_in = ma::configureMatching(m, in.recursiveUR);
./phasta/phAdapt.cc:    ma::Input* ma_in = ma::configureMatching(m, in.recursiveUR);
./phasta/phInput.cc:  in.recursiveUR = 1;
./phasta/phInput.cc:  intMap["RecursiveUR"] = &in.recursiveUR;
./phasta/phInput.h:    int recursiveUR;
```

`adaptFlag 0` is listed in `1639780.adapt.inp` so there is no UR happening with this run.

Job 1639780 (`/projects/TRAssembly_2/skinnerr/NGC/series14.7.0/mesh_32M/64kUR-16kUR-Chef-DDES-ts122000/1639780.error`)
ran with 2Ki nodes which would give each process between 463-493MB; less than the ~508MB being requested.

@skinnerr Are you available to debug within your session on Mira before 3pm eastern today?  If not, I'll be available tomorrow afternoon.

**Comment by cwsmith** [comment]
The doxygen documentation for the chef balancing input parameters was updated to indicate that they ignore the setting of the `LocalPtn` flag. 
 https://github.com/SCOREC/core/commit/c9ba43e4b86404ea398333fbff774e9193116c2e

**Comment by skinnerr** [comment]
Cameron and I sat down over Slack and talked through the issues. The current thinking is that because `partitionMethod graph` uses so much memory, it is generally not recommended for target part counts over 32k. Even with `LocalPtn 0`, the setting of `prePhastaBalanceMethod` can still uses a bunch of memory because local balancing is an oxymoron; balancing has to be global. Thus if you have `prePhastaBalanceMethod graph`, even with `LocalPtn 0`, it will ask for a ton of memory, resulting in the crashes we have seen.

Riccardo was kind enough to run some tests on Theta last night, to get some insight as to whether this was a BGQ-specific memory issue, e.g. us not being able to access all the memory that is theoretically available per process. Riccardo did not do solution migration in order to start simple. The results of his runs are:

0. Settings common to all: 16k to 64k parts, 256 nodes of Theta (750 MB memory / process)
1. `preAdaptBalanceMethod none, prePhastaBalanceMethod graph, partitionMethod graph`. This died after "mesh expanded; mesh migrated," probably due to memory based on experience but no output to that effect.
2. `preAdaptBalanceMethod none, prePhastaBalanceMethod none, partitionMethod rib`. This succeeded (wall time was 4 minutes) but resulted in a 70% max vertex load imbalance of the partitioned mesh. Note that `rib` (http://www.cs.sandia.gov/zoltan/ug_html/ug_alg_rib.html) has very low memory consumption but can result in high imbalance like here.

Cameron has suggested I try the following settings in `adapt.inp` to get good balance for 16k to 64k parts (both jobs submitted to Mira on 4k nodes currently, 16 processes/node = 1GB memory / process):
1. `preAdaptBalanceMethod none, prePhastaBalanceMethod parma-gap, partitionMethod rib`. This one should work, hopefully, since neither has huge memory requirements. If this one exceeds the allocation time, we can either try increasing the runtime or tweak the allowed imbalance to 10% from the default of 3-5% with `elementImbalance 1.10, vertexImbalance 1.10`
2. `preAdaptBalanceMethod none, prePhastaBalanceMethod none, partitionMethod graph`. This one is a little riskier, but by just trying graph partitioning, we should hopefully get a good balance.

I will be updating this ticket with results.

**Comment by skinnerr** [comment]
Approach #1 is successful, with the following balance. How important is the max vertex load imbalance, e.g. how much of a hit in performance does this translate into, even though the entity imbalance is very good?
> PARMA_STATUS postGap entity imbalance <v e f r>: 1.05 1.03 1.03 1.05
> max vertex load imbalance of partitioned mesh = 1.444399

**Comment by cwsmith** [comment]
Very strange that phasta's measure of imbalance (`max vertex load imbalance`) differs so much from ParMA's (`PARMA_STATUS `...) .  

It looks like parma took 30 seconds:

```
/projects/TRAssembly_2/skinnerr/NGC/series14.7.0/mesh_32M/64kUR-16kUR-Chef-DDES-ts122000 $ grep balanced 1641679.output | awk '{sum+=$(NF-1)} END {print sum}'
30.2626
```

More of the log from job is pasted below:

```
PUMI Git hash 2.1.0
PUMI version 2.1.0 Git hash f12a2cfa9aeb72e188a8c6c23f734534598f58fa
"geom.smd" and "geom.spj" loaded in 0.729576 seconds
mesh bz2:../16kUR-16k-Chef-A0-DDES-ts122000/122000/mdsMesh_bz2/ loaded in 3.408658 seconds
number of tet 461522792 hex 0 prism 0 pyramid 0
mesh entity counts: v 78449082 e 540773585 f 923847296 r 461522792
mesh verified in 3.707006 seconds
fields read and attached in 0.577948 seconds
planned RIB factor 4 in 0.408517 seconds
mesh expanded from 16384 to 65536 parts in 0.877666 seconds
mesh migrated from 16384 to 65536 in 7.749359 seconds
PARMA_STATUS preRefine disconnected <max avg> 46 1.258
PARMA_STATUS preRefine neighbors <max avg> 56 17.746
PARMA_STATUS preRefine smallest side of max neighbor part 1
PARMA_STATUS preRefine num parts with max neighbors 1
PARMA_STATUS preRefine empty parts 0
PARMA_STATUS preRefine small neighbor counts 1:48086 2:33584 3:29206 4:26010 5:24182 6:21982 7:20426 8:19638 9:18406 10:17614
PARMA_STATUS preRefine weighted vtx <tot max min avg> 110242474.0 2033.0 1058.0 1682.167
PARMA_STATUS preRefine weighted edge <tot max min avg> 630415650.0 10651.0 6009.0 9619.379
PARMA_STATUS preRefine weighted face <tot max min avg> 981759547.0 15726.0 9319.0 14980.462
PARMA_STATUS preRefine weighted rgn <tot max min avg> 461522792.0 7204.0 4367.0 7042.279
PARMA_STATUS preRefine owned bdry vtx <tot max min avg> 26004669 1302 0 396.800
PARMA_STATUS preRefine shared bdry vtx <tot max min avg> 57798061 1522 518 881.928
PARMA_STATUS preRefine model bdry vtx <tot max min avg> 1032153 353 0 15.749
PARMA_STATUS preRefine sharedSidesToElements <max min avg> 0.434 0.142 0.251
PARMA_STATUS preRefine entity imbalance <v e f r>: 1.21 1.11 1.05 1.02
... 
PARMA_STATUS gap balanced in 12 steps to 1.059251 in 1.623760 seconds
PARMA_STATUS postGap disconnected <max avg> 9 0.042
PARMA_STATUS postGap neighbors <max avg> 34 17.101
PARMA_STATUS postGap smallest side of max neighbor part 1
PARMA_STATUS postGap num parts with max neighbors 2
PARMA_STATUS postGap empty parts 0
PARMA_STATUS postGap small neighbor counts 1:43022 2:27024 3:24168 4:21880 5:21624 6:20202 7:19788 8:18702 9:18100 10:17326
PARMA_STATUS postGap weighted vtx <tot max min avg> 108077368.0 1729.0 1492.0 1649.130
PARMA_STATUS postGap weighted edge <tot max min avg> 624543355.0 9812.0 8217.0 9529.775
PARMA_STATUS postGap weighted face <tot max min avg> 978053582.0 15446.0 12450.0 14923.913
PARMA_STATUS postGap weighted rgn <tot max min avg> 461522792.0 7390.0 5741.0 7042.279
PARMA_STATUS postGap owned bdry vtx <tot max min avg> 24701088 1190 0 376.909
PARMA_STATUS postGap shared bdry vtx <tot max min avg> 54329374 1190 501 829.000
PARMA_STATUS postGap model bdry vtx <tot max min avg> 1014662 352 0 15.483
PARMA_STATUS postGap sharedSidesToElements <max min avg> 0.363 0.129 0.235
PARMA_STATUS postGap entity imbalance <v e f r>: 1.05 1.03 1.03 1.05
STATUS vtx imbalance target 1.050 reached
mesh reordered in 0.450596 seconds
max vertex load imbalance of partitioned mesh = 1.444399
ratio of sum of all vertices to sum of owned vertices = 1.377675
max region (3D) or face (2D) load imbalance of partitioned mesh = 1.049376
ph::getGrowthCurves: warning! not implemented for MDS mesh
All attribute-based initial conditions, if any, are ignored due to request for SolutionMigration
generated output structs in 0.623576 seconds
solution written in 12.243843 seconds
mesh bz2:mdsMesh_bz2/ written in 15.712443 seconds
geombc file written in 7.199532 seconds
mesh verified in 1.144735 seconds
Wed Sep 19 18:34:16 UTC 2018
```

**Comment by skinnerr** [comment]
Approach 2 was also successful. Hooray! Looks like the issue was graph balancing after the partitioning step.

**Comment by cwsmith** [comment]
Would you please post the parma and phasta imbalance stats for approach 2?

**Comment by skinnerr** [comment]
Here's a summary of the imbalance stats for approaches 1 and 2. Note that approach 2 uses Zoltan.

Approach 1: `preAdaptBalanceMethod none, prePhastaBalanceMethod parma-gap, partitionMethod rib`
> PARMA_STATUS postGap entity imbalance <v e f r>: 1.05 1.03 1.03 1.05
> max vertex load imbalance of partitioned mesh = 1.444399
> ratio of sum of all vertices to sum of owned vertices = 1.377675
> max region (3D) or face (2D) load imbalance of partitioned mesh = 1.049376

Approach 2: `preAdaptBalanceMethod none, prePhastaBalanceMethod none, partitionMethod graph, LocalPtn 1`
>planned Zoltan split factor 4 to target imbalance 1.010000 in 2.012681 seconds
>max vertex load imbalance of partitioned mesh = 1.444399
>ratio of sum of all vertices to sum of owned vertices = 1.321235
>max region (3D) or face (2D) load imbalance of partitioned mesh = 1.027508

**Comment by cwsmith** [comment]
Closing this issue.  I've opened a new issue for the balance measure mismatch #182 .
