### ISSUE TITLE
field not showing up until data is written

### ISSUE THREAD

**Issue by YetAnotherMinion** [SCOREC/core#18]
Creating a new field on a mesh, then attempting to write it to a file is a segfault.
Minimal working example
```C++
apf::Field* node_f = apf::createField(m, "nodeField", apf::SCALAR, m->getShape());
apf::writeVtkFiles("batman_elm", m);
```
then 
```
expected tag "nodeField_ver" on entity type 0
Aborted (core dumped)
```

But if you zero the field `apf::zeroField(node_f);` then no segfault.
I could not find the place in the documentation that indicates the need to write data to a field to
make it appear, so this issue is more of a heads up that the behavior of Field is not very clear if
you are only working from the doxygen.

**Comment by zaidedan** [comment]
We are aware of this. There are lots of examples in the code where it seg
faults without properly setting up data. Why would you want to write a
field you just created and haven't initialized?

On Thu, Aug 27, 2015 at 4:09 PM, Another Minion <notifications@github.com>
wrote:

> Creating a new field on a mesh, then attempting to write it to a file is a
> segfault.
> Minimal working example
>
> apf::Field* node_f = apf::createField(m, "nodeField", apf::SCALAR, m->getShape());apf::writeVtkFiles("batman_elm", m);
>
> then
>
> expected tag "nodeField_ver" on entity type 0
> Aborted (core dumped)
>
> But if you zero the field apf::zeroField(node_f); then no segfault.
> I could not find the place in the documentation that indicates the need to
> write data to a field to
> make it appear, so this issue is more of a heads up that the behavior of
> Field is not very clear if
> you are only working from the doxygen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SCOREC/core/issues/18>.
>



-- 
Dr. Daniel W. Zaide (偉明),
Researcher, Rensselaer Polytechnic Institute
B.A.Sc. University of Toronto (2007)
M.S.E, M.S. Ph.D., University of Michigan (2009,2011,2012)
www.danielzaide.com <http://www.danielzaide.com>

**Comment by YetAnotherMinion** [comment]
From the Doxygen there is no hint at all of this interaction. I guess this issue is a feature request for more documentation. Just a one line addition to the comment in the source that a field must be initialized before any other parts of the code touches it would be a nice thing to have for all of us remote users.

**Comment by bgranzow** [comment]
does std::vector need documentation saying it
will seg fault if you try to access elements of range?

**Comment by zaidedan** [comment]
Oh Okay. The assumption is though that the user will initialize it right
after doing it, its why it doesn't zero right away. We could set the field
to just zero upon creation, but most people would just then go and set it
again.

The more worry-some behavior are things where invalid behavior gives a
valid response, and there are a few examples of those.
Segmentation faults are actually a positive thing in a lot of cases, they
are much easier to debug then math or iterator errors, and they are an
indicator that you have forgotten to do something. For example, in your
case, the segmentation fault told you you needed to initialize it before
trying to access its values.



On Thu, Aug 27, 2015 at 4:26 PM, Another Minion <notifications@github.com>
wrote:

> From the Doxygen there is no hint at all of this interaction. I guess this
> issue is a feature request for more documentation. Just a one line addition
> to the comment in the source that a field must be initialized before any
> other parts of the code touches it would be a nice thing to have for all of
> us remote users.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SCOREC/core/issues/18#issuecomment-135544907>.
>



-- 
Dr. Daniel W. Zaide (偉明),
Researcher, Rensselaer Polytechnic Institute
B.A.Sc. University of Toronto (2007)
M.S.E, M.S. Ph.D., University of Michigan (2009,2011,2012)
www.danielzaide.com <http://www.danielzaide.com>

**Comment by YetAnotherMinion** [comment]
I am not complaining about the behavior, it is fine and made me go and fix things. Its is just that I had no idea why it was reporting about a tag on entities was not found the first time I found this.

**Comment by zaidedan** [comment]
Thank you Amadej,

Perhaps we will add this to a FAQ of common mistakes. Where in the code do
you think this should be documented? makeField? apf::createField?
FieldBase? FieldOf?

On Thu, Aug 27, 2015 at 4:36 PM, Another Minion <notifications@github.com>
wrote:

> I am not complaining about the behavior, it is fine and made me go and fix
> things. Its is just that I had no idea why it was reporting about a tag on
> entities was not found the first time I found this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SCOREC/core/issues/18#issuecomment-135548922>.
>



-- 
Dr. Daniel W. Zaide (偉明),
Researcher, Rensselaer Polytechnic Institute
B.A.Sc. University of Toronto (2007)
M.S.E, M.S. Ph.D., University of Michigan (2009,2011,2012)
www.danielzaide.com <http://www.danielzaide.com>

**Comment by bgranzow** [comment]
I'm unable to reproduce your behavior of a seg-fault
with a simple example

<pre>
#include <gmi_mesh.h>
#include <apfMDS.h>
#include <apfMesh2.h>
#include <apf.h>
#include <PCU.h>

int main(int argc, char** argv)
{
  assert(argc==3);
  MPI_Init(&argc,&argv);
  PCU_Comm_Init();
  gmi_register_mesh();
  apf::Mesh2* m = apf::loadMdsMesh(argv[1],argv[2]);
  m->verify();
  apf::Field* node_f = apf::createField(m, "nodeField", apf::SCALAR, m->getShape());
  apf::writeVtkFiles("batman_elm", m);
  m->destroyNative();
  apf::destroyMesh(m);
  PCU_Comm_Free();
  MPI_Finalize();
}
</pre>

The above code doesn't seg-fault on any of the meshes that
I tried. Outputting to VTK files simply ignores the created field.
This is expected behavior

https://github.com/SCOREC/core/blob/master/apf/apfVtk.cc#L40

and probably wouldn't be a bad thing to include in the
documentation.

**Comment by zaidedan** [comment]
The more likely issue then is that his mesh does not have all of its nodes
set, which occurs if you changeMeshShape with project = False

On Thu, Aug 27, 2015 at 4:49 PM, Brian Granzow <notifications@github.com>
wrote:

> I'm unable to reproduce your behavior of a seg-fault
> with a simple example
>
> #include
> #include
> #include
> #include
> #include
>
> int main(int argc, char** argv)
> {
>   assert(argc==3);
>   MPI_Init(&argc,&argv);
>   PCU_Comm_Init();
>   gmi_register_mesh();
>   apf::Mesh2* m = apf::loadMdsMesh(argv[1],argv[2]);
>   m->verify();
>   apf::Field* node_f = apf::createField(m, "nodeField", apf::SCALAR, m->getShape());
>   apf::writeVtkFiles("batman_elm", m);
>   m->destroyNative();
>   apf::destroyMesh(m);
>   PCU_Comm_Free();
>   MPI_Finalize();
> }
>
> The above code doesn't seg-fault on any of the meshes that
> I tried. Outputting to VTK files simply ignores the created field.
> This is expected behavior
>
> https://github.com/SCOREC/core/blob/master/apf/apfVtk.cc#L40
>
> and probably wouldn't be a bad thing to include in the
> documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SCOREC/core/issues/18#issuecomment-135551433>.
>



-- 
Dr. Daniel W. Zaide (偉明),
Researcher, Rensselaer Polytechnic Institute
B.A.Sc. University of Toronto (2007)
M.S.E, M.S. Ph.D., University of Michigan (2009,2011,2012)
www.danielzaide.com <http://www.danielzaide.com>

**Comment by YetAnotherMinion** [comment]
My Mesh is generated programmatically. It is very likely that I am producing a horribly malformed mesh, I just don't know any better when generating it.https://github.com/YetAnotherMinion/FEP/blob/master/a4/src/MeshBuilder.cc#L377 is how I do it

**Comment by bgranzow** [comment]
you can use mesh->verify() to do a sanity check of your mesh...
https://github.com/SCOREC/core/blob/master/apf/apfMesh.h#L305

this 077070c1e9e682f2bbde66daebc1749627c67319 answers the original question though.

**Comment by zaidedan** [comment]
This code generates your mesh. Not sure why you needed a numbering to start


gmi_register_null();
  gmi_model* g = gmi_load(".null");
  apf::Mesh2* mesh = apf::makeEmptyMdsMesh(g, 2, false);

  apf::MeshEntity* verts[4];
  /*this element is flipped upside down around x axis*/
  apf::Vector3 tmp_vec(1.35,2.36,0.0), p(0,0,0);
  verts[0] = mesh->createVertex(0,tmp_vec,p);
  tmp_vec.x() = 2.57; tmp_vec.y() = 2.70;
  verts[1] = mesh->createVertex(0,tmp_vec,p);
  tmp_vec.x() = 2.51; tmp_vec.y() = 1.75;
  verts[2] = mesh->createVertex(0,tmp_vec,p);
  tmp_vec.x() = 1.64; tmp_vec.y() = 1.28;
  verts[3] = mesh->createVertex(0,tmp_vec,p);

  apf::MeshEntity* e = apf::buildElement(mesh,0, apf::Mesh::QUAD, verts);

  apf::deriveMdsModel(mesh);
  mesh->acceptChanges();
  mesh->verify();

  apf::changeMeshShape(mesh, apf::getLagrange(2));


  apf::Downward down;
  mesh->getDownward(e, 1, down);
  tmp_vec.x() = 2.09; tmp_vec.y() = 2.36;
  mesh->setPoint(down[0], 0, tmp_vec);
  tmp_vec.x() = 2.73; tmp_vec.y() = 2.25;
  mesh->setPoint(down[1], 0, tmp_vec);
  tmp_vec.x() = 2.01; tmp_vec.y() = 1.72;
  mesh->setPoint(down[2], 0, tmp_vec);
  tmp_vec.x() = 1.15; tmp_vec.y() = 1.77;
  mesh->setPoint(down[3], 0, tmp_vec);
  /*set the center node*/
  tmp_vec.x() = 1.90; tmp_vec.y() = 2.05;
  mesh->setPoint(e, 0, tmp_vec);
  apf::createFieldOn(mesh,"fieldOfDreams",apf::SCALAR);
  apf::writeVtkFiles("batman",mesh);

On Thu, Aug 27, 2015 at 5:03 PM, Brian Granzow <notifications@github.com>
wrote:

> Closed #18 <https://github.com/SCOREC/core/issues/18>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SCOREC/core/issues/18#event-394465641>.
>



-- 
Dr. Daniel W. Zaide (偉明),
Researcher, Rensselaer Polytechnic Institute
B.A.Sc. University of Toronto (2007)
M.S.E, M.S. Ph.D., University of Michigan (2009,2011,2012)
www.danielzaide.com <http://www.danielzaide.com>

**Comment by YetAnotherMinion** [comment]
The numbering has a special name, SECRET_BUILDER_NUMBERING, which is a global constant used in the unittesting of the the mesh builder functions. Its a dirty hack, but I need it to ensure that tags going on mesh entities are going on the right elements. That numbering is a function of the position of the each element, allowing me to reverse calculate it. That code will never be used by anyone else ever again so... it stays a dirty hack.

**Comment by zaidedan** [comment]
Either way, I was able to build your mesh and output it to file, so theres
that.

On Thu, Aug 27, 2015 at 5:18 PM, Another Minion <notifications@github.com>
wrote:

> The numbering has a special name, SECRET_BUILDER_NUMBERING, which is a
> global constant used in the unittesting of the the mesh builder functions.
> Its a dirty hack, but I need it to ensure that tags going on mesh entities
> are going on the right elements. That numbering is a function of the
> position of the each element, allowing me to reverse calculate it. That
> code will never be used by anyone else ever again so... it stays a dirty
> hack.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SCOREC/core/issues/18#issuecomment-135557283>.
>



-- 
Dr. Daniel W. Zaide (偉明),
Researcher, Rensselaer Polytechnic Institute
B.A.Sc. University of Toronto (2007)
M.S.E, M.S. Ph.D., University of Michigan (2009,2011,2012)
www.danielzaide.com <http://www.danielzaide.com>

**Comment by ibaned** [comment]
I will only say a couple of things about this issue.

1) there is a piece of code very specifically created to prevent this behavior, so your mesh is almost certainly broken in some way.

https://github.com/SCOREC/core/blob/master/apf/apfVtk.cc#L22

2) we are not a Silicon Valley project with millions of venture vapor-dollars to pay interns to document our API. the documentation *will* be out of date. manage your expectations.
