### ISSUE TITLE
RPATH issues

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/core#186]
Hi Cameron, with the latest SimModSuite for BGQ, I can successfully build all PUMI apps. However, the following error is encountered when I do make install. Any suggestion?

```
-- Up-to-date: /home/fang/SCOREC_develop/build-bgq-xl_14.0-181003dev/install/include/ph.h
-- Installing: /home/fang/SCOREC_develop/build-bgq-xl_14.0-181003dev/install/bin/verify
CMake Error at test/cmake_install.cmake:40 (file):
  file RPATH_CHANGE could not write new RPATH:

    /home/fang/SCOREC_develop/build-bgq-xl_14.0-181003dev/install/lib

  to the file:

    /home/fang/SCOREC_develop/build-bgq-xl_14.0-181003dev/install/bin/verify

  No valid ELF RPATH or RUNPATH entry exists in the file;
Call Stack (most recent call first):
  cmake_install.cmake:76 (include)
  


make: *** [install] Error 1
```

@hapfang

**Comment by jacobmerson** [comment]
I think rpath is normally only involved when you are doing dynamic linking. You may want to verify that everything is set to static link.

**Comment by cwsmith** [comment]
@jacobmerson is correct.  RPATH and static linking does not make sense.

A quick hack is to pass `-DCMAKE_SKIP_RPATH=ON` to cmake.

**Comment by hapfang** [comment]
You are right. `-DCMAKE_SKIP_RPATH=ON` is indeed a workaround for the error above. Thanks again.
