### ISSUE TITLE
osx build fails with brew gcc

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/core#188]
From @balay:

Building pumi@develop for xsdk on OSX with brew gcc fails.

The spack log is attached.
[pumi-develop-spack-build.out.gz](https://github.com/SCOREC/core/files/2478642/pumi-develop-spack-build.out.gz)

**Comment by cwsmith** [comment]
I reproduced the error on my laptop:

- installed gcc 8.2 via brew:
```
brew install gcc
brew update gcc
```

- added gcc 8.2 to spack
`spack compiler add /usr/local/Cellar/gcc/8.2.0`
- set `gcc@8.2.0` as the default compiler in `~/.spack/darwin/packages.yaml`
- added packages installed externally of spack in `~/.spack/darwin/packages.yaml` (perl, cmake, python, etc.)
- install pumi (and deps)
```
spack install -v pumi@develop
```

**Comment by cwsmith** [comment]
@balay Please try the build again.  The `uint` error is fixed and [a linking error](https://github.com/SCOREC/core/commit/23a0811eb27e4dc008fde7abe4a83879255294ac) you would have eventually hit.

**Comment by balay** [comment]
Thanks! build on osx with brew gcc works now.

BTW: I see the push is on `develop` branch. However spack has:

```
    version('develop', branch='master')
```

So perhaps the following fix in spack?

```
diff --git a/var/spack/repos/builtin/packages/pumi/package.py b/var/spack/repos/builtin/packages/pumi/package.py
index 0e23420c8..b7becc721 100644
--- a/var/spack/repos/builtin/packages/pumi/package.py
+++ b/var/spack/repos/builtin/packages/pumi/package.py
@@ -38,7 +38,8 @@ class Pumi(CMakePackage):
     homepage = "https://www.scorec.rpi.edu/pumi"
     git      = "https://github.com/SCOREC/core.git"
 
-    version('develop', branch='master')
+    version('develop', branch='develop')
+    version('master', branch='master')
     version('2.1.0', commit='840fbf6ec49a63aeaa3945f11ddb224f6055ac9f')
 
     variant('zoltan', default=False, description='Enable Zoltan Features')
```

**Comment by cwsmith** [comment]
Great.  Thanks for testing again.

Every night the `develop` branch is merged into `master` if it passes regression tests under a few build configs.  So, we should keep 'master' as the branch name spack uses. I like the idea of renaming to the spack version to 'master' instead of 'develop' for consistency.  Does that go against any spack-isms that you are aware of?

**Comment by balay** [comment]
I think as far as spack is concerned:
`develop > master > release-versions [for eg: 3.1 >  2.1 > 1.00]`

but its not clear to me if `version('develop', branch='master')` is a good idea..

spack uses `develop` for  development branch  in git and `master` for release branch in git.

PETSc uses master/maint for this purpose. But I don't see a provision for:
```
version('maint', branch='maint')
```
with: `develop > master > maint > release-number` support in spack

@davydden would have a better answer

I don't see any version tags in pumi - but there is:
```
    version('2.1.0', commit='840fbf6ec49a63aeaa3945f11ddb224f6055ac9f')
```
This commit is in master.  So pumi is using the same `develop/master` model as spack - so I think you should list both(develop and master) versions in pumi/package.py - as my above patch does..

**Comment by davydden** [comment]
Currently, version comparison in Spack is: develop > 1.2.3 > something (including master, trunk, etc). I have been pushing changes to change that for about two years https://github.com/spack/spack/pull/1983 maybe a stronger demand from package developers can help, but I am not sure...

**Comment by balay** [comment]
@davydden, thanks for the correction. So only 'develop' is significant in spack - and not 'master'

**Comment by davydden** [comment]
> So only 'develop' is significant in spack - and not 'master'

As of now, yes.

**Comment by cwsmith** [comment]
@balay I'd prefer to keep the 'develop' spack version pointed at the scorec/core master branch.  I don't want to expose spack users to the instabilities of the develop branch.  To move forward with this I've created a PR that documents the mismatch.  https://github.com/spack/spack/pull/9577

**Comment by balay** [comment]
Sure Thanks!
