### ISSUE TITLE
integrate process only works on mesh dim which may be different from the analysis dim

### ISSUE THREAD

**Issue by jacobmerson** [SCOREC/core#190]
The example here is a 1d beam/truss element in 3d space. We want to integrate over 1D elements. Currently I work around this issue by replicating the `Integrator::process(Mesh* m)` code locally and process each element.

To reduce code duplication I want to propose the following change in core, which leaves the current api in tact, but adds a default argument to the process call.

e.g.
 
`Integrator::process(Mesh* m, int dim=-1)`

if the dim is `-1` the current behavior is maintained, otherwise we integrate over the user supplied dimension.

@cwsmith @wrtobin if you have no issues with this approach I will submit a pull request.

**Comment by cwsmith** [comment]
Seems like a decent approach; please submit the PR.

**Comment by wrtobin** [comment]
Yeah it maintains the API and adds functionality while reducing code duplication so I'm all for it.
