### ISSUE TITLE
Matrix Field Gradient and Divergence

### ISSUE THREAD

**Issue by jacobmerson** [SCOREC/core#201]
I am working on implementing the gradient of a 3x3 matrix field as needed for one of my projects. I am open to recommendations for the layout of the resulting 3rd order tensor if anyone has recommendations or preferences.

**Comment by cwsmith** [comment]
Is the idea to add this to core?

I suspect that the layout (memory and variable ordering) is somewhat application dependent, especially if it is being computed/used in a hot loop.
