### ISSUE TITLE
What is the purpose of getNodeXi member of a shape function

### ISSUE THREAD

**Issue by YetAnotherMinion** [SCOREC/core#21]
I was looking at the getNodeXi function and I noticed that it is set to return Vector(0,0,0) in the base class, and then is never overloaded by the child classes. I thought that perhaps the getNodeXi would give the location of each node for a FieldElement. However when I implemented this function for the quadratic Lagrange shape function I started failing the unit tests for shapefun2 and bezierMesh. The failing tests do not directly call getNodeXi, so before I went down the path of debugging, I thought I would ask what the intended purpose of getNodeXi is. If it needs to be implemented, I will be happy to implement it, and make the tests pass. Otherwise I would like to know how to get the location of the nodes in Xi space for a fieldshape or field element.

Here is my implementation for LagrangeQuadratic.

```cpp
    void getNodeXi(int et, int node, Vector3& xi)
    {
      switch(node) {
        case 0:
          xi = Vector3(-1,-1, 0);
          break;
        case 1:
          xi = Vector3( 1,-1, 0);
          break;
        case 2:
          xi = Vector3( 1, 1, 0);
          break;
        case 3:
          xi = Vector3(-1, 1, 0);
          break;
        case 4:
          xi = Vector3( 0,-1, 0);
          break;
        case 5:
          xi = Vector3( 1, 0, 0);
          break;
        case 6:
          xi = Vector3( 0, 1, 0);
          break;
        case 7:
          xi = Vector3(-1, 0, 0);
          break;
        case 8:
          xi = Vector3( 0, 0, 0);
          break;
        default:
          fail("node index not found");
          break;
      }
    }
```

**Comment by ibaned** [comment]
The reason it has very little code in it is that the "int node" argument is actually indexing the *interior* nodes of the entity. So, for quadratic Lagrange, the only valid queries are interior node #0 of a vertex, or interior node #0 of an edge, i.e. the mid-edge node. I may be forgetting all the code I've written, but I don't think there is a function for indexing over all the nodes in the closure. Most Finite Element code starts with the Xi of a quadrature point as input and evaluates shape functions, so this otherwise simple functionality has so far been left out.

**Comment by ibaned** [comment]
Could you give some background on why you're making this query in your code ? I know its a simple one but it would be a bunch of new tables somewhere so I'd like to know the use case.

**Comment by YetAnotherMinion** [comment]
I was looking for a way to display the stress and strain fields using Paraview. In order to use the built in rendering/warp vector, I need to find the stress and strain for the element nodes in global coordinate space. This way I can write the output.I looked at using the IPShape field to store the output variables, but it creates many different fields and I can only warp vector or color with one of them. Thus I was motivated to evaluate the secondary variables at the node points.

I can create a table in my application code to give me the locations of the nodes for all of my supported shape functions, but I wanted to see if there was a feature of the API that would do this for me. getNodeXi sounded exactly like what I wanted to do, but I understand now the intended use. Thanks for the quick response!
