### ISSUE TITLE
Chef build failure on XC40 Theta with the SimModSuite 12.0-190105

### ISSUE THREAD

**Issue by hapfang** [SCOREC/core#210]
I was trying to build a Chef on the Theta machine (Cray XC40) with the SimModSuite 12.0-190105. A linking error is encountered with the following message 
```
[ 98%] Linking CXX static library libph.a
[100%] Linking CXX static library libcrv.a
[100%] Built target crv
[100%] Built target ph
Scanning dependencies of target chef
[100%] Building CXX object test/CMakeFiles/chef.dir/__/phasta/chef.cc.o
[100%] Linking CXX executable chef
/home/fang/dependencies/simmodsuites/12.0-190105/lib/x64_rhel7_gcc48/libSimModel.a(ioutil.o): In function `sgethostbyname(char const*, char*, hostent*)':
ioutil.cc:(.text+0x6ed): warning: Using 'gethostbyname_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /home/fang/SCOREC_develop/theta-deps/install-gnu/lib/libmetis.a(error.c.o): undefined reference to symbol '__tls_get_addr@@GLIBC_2.3'
/lib64/ld-linux-x86-64.so.2: error adding symbols: DSO missing from command line
/usr/bin/sha1sum: a.out: No such file or directory
collect2: error: ld returned 1 exit status
test/CMakeFiles/chef.dir/build.make:130: recipe for target 'test/chef' failed
make[3]: *** [test/chef] Error 1
CMakeFiles/Makefile2:6518: recipe for target 'test/CMakeFiles/chef.dir/all' failed
make[2]: *** [test/CMakeFiles/chef.dir/all] Error 2
CMakeFiles/Makefile2:6530: recipe for target 'test/CMakeFiles/chef.dir/rule' failed
make[1]: *** [test/CMakeFiles/chef.dir/rule] Error 2
Makefile:1681: recipe for target 'chef' failed
make: *** [chef] Error 2
```
The warning in the first 2 lines are likely not fatal as I saw them before even in my successful build. As for the error "undefined reference to symbol '__tls_get_addr@@GLIBC_2.3'", the closest answer I can find online is as follows 
_I ran into a similar issue building a code on a Cray xc40/50 system. My issue was that, since Cray has to change every last thing from a default, you have to pass an extra flag to the compiler wrappers. (The compiler wrappers are cc, CC and ftn for C, C++, and Fortran.) The flag you need to pass, -dynamic is documented in the man page for the wrappers. You can tell the underlying compiler to link statically or dynamically but without passing this flag to the wrapper you're out of luck.(https://stackoverflow.com/questions/28198965/how-to-resolve-tls-get-addrglibc-2-3-error-on-compiling-gcc-itself)_
I am not sure how to properly pass `-dynamic ` to the compiler wrappers. Does anyone know how to do that? Or there is a better fix and suggestion I could try?

**Comment by cwsmith** [comment]
Has a core build with simmodsuite worked before for you?

There is an wiki page on this that may or may not be helpful.
https://github.com/SCOREC/core/wiki/Build-on-ALCF-Theta

**Comment by hapfang** [comment]
Thanks Cameron. The CMake option `-DCMAKE_EXE_LINKER_FLAGS="-dynamic " ` helps resolve the issue.
