### ISSUE TITLE
compiling core after STK API update

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/core#218]
> I am having problems compiling core. These are the types of the errors I am getting:
> 
> /home/marioju/projects/scorec/stk/apfSTK.cc: In function \u2018T* apf::makeStkQPField(const char*, unsigned int, apf::StkMetaData*) [with T = stk::mesh::Field<double, apf::QPDimTag, stk::mesh::Cartesian3d>; apf::StkMetaData = stk::mesh::MetaData]\u2019:
> /home/marioju/projects/scorec/stk/apfSTK.cc:205:11: error: no matching function for call to \u2018put_field_on_mesh(apf::StkQPVectorField&, stk::mesh::Part&, int, unsigned int&, NULL)\u2019
>        NULL);
> 
> /home/marioju/projects/scorec/stk/apfSTK.cc: In function \u2018T* apf::makeStkQPField(const char*, unsigned int, apf::StkMetaData*) [with T = stk::mesh::Field<double, apf::QPDimTag, stk::mesh::Cartesian3d, stk::mesh::Cartesian3d>; apf::StkMetaData = stk::mesh::MetaData]\u2019:
> /home/marioju/projects/scorec/stk/apfSTK.cc:225:11: error: no matching function for call to \u2018put_field_on_mesh(apf::StkQPTensorField&, stk::mesh::Part&, int, int, const unsigned int&, NULL)
> 
> I am using gcc 4.8.5 version in rhel7. 
> 
> The latest commit for core than I am using is:
> commit 1608ce39c44cd482f665b64971b7916d9bb6d885
> 
> and for Trilinos:
> commit 5c9a2ec8019b310b5b74a22e23fcbea11486f781
> 
> Anyone knows how I can solve this problem?

_Originally posted by @mjuha in https://github.com/SCOREC/core/pull/215#issuecomment-473300469_

**Comment by mjuha** [comment]
I solved the problem of compilation adding the following lines to my configure script:

-D ENABLE_STK:BOOL=OFF
-D ENABLE_STK_MESH:BOOL=OFF \

But it creates problem compiling Albany.

**Comment by cwsmith** [comment]
@mjuha Is this a clean build of core, trilinos, and albany?  IIUC, there is at least one 'nightly' albany build with core that is building correctly and passing tests.  

Would you please share your full trilinos, albany, and core cmake commands?  Maybe @maxrpi can spot something quickly.

**Comment by cwsmith** [comment]
@mjuha Please keep the discussion in this issue.  I delete your latest comment in the PR as the PR points to this issue.

**Comment by mjuha** [comment]
It is a fresh install.
Trilinos:
#!/bin/sh
  #
  export TRILINOS_HOME=/home/marioju/projects/albany/Trilinos
  BUILD_DIR=`pwd`
  INSTALL_DIR=/home/marioju/projects/albany/install/Trilinos/MPI_REL
  BOOST_DIR=/home/marioju/projects/albany/tpls
  YAMLDIR=/home/marioju/projects/albany/tpls
  SUPERLU_DIR=/home/marioju/projects/albany/tpls/SuperLU_4.3
  LIB_DIR=/home/marioju/projects/albany/tpls
  MPI_BASE_DIR=/usr/lib64/openmpi/bin
  NETCDF=/home/marioju/projects/albany/tpls
  HDFDIR=/home/marioju/projects/albany/tpls
  PARMETISDIR=/home/marioju/projects/albany/tpls/parmetis-4.0.3
  LABLAS_LIBRARIES="-lblas -llapack"
#  SIM_INCLUDE=/usr/local/etc/SimModSuite/11.0-171006/include
#  SIM_LIB=/usr/local/etc/SimModSuite/11.0-171006/lib/x64_rhel7_gcc48
#  SIM_INCLUDE=$SIM_INSTALL_DIR/include
#  SIM_LIB=$SIM_INSTALL_DIR/lib/x64_rhel7_gcc48

  cmake \
      -Wno-dev \
      -D Trilinos_CONFIGURE_OPTIONS_FILE:FILEPATH=$TRILINOS_HOME/sampleScripts/AlbanySettings.cmake \
      -D Trilinos_ENABLE_SCOREC:BOOL=OFF \
      -D STK_HIDE_DEPRECATED_CODE:BOOL=OFF \
      -D Trilinos_WARNINGS_AS_ERRORS_FLAGS="" \
      -D CMAKE_BUILD_TYPE:STRING=NONE \
      -D CMAKE_CXX_FLAGS:STRING="-O3 -march=native -DNDEBUG" \
      -D CMAKE_C_FLAGS:STRING="-O3 -march=native -DNDEBUG" \
      -D CMAKE_Fortran_FLAGS:STRING="-O3 -march=native -DNDEBUG" \
      -D Trilinos_ENABLE_ALL_PACKAGES=OFF \
      -D Trilinos_WARNINGS_AS_ERRORS_FLAGS="" \
      -D Trilinos_ENABLE_Teuchos=ON \
      -D Trilinos_ENABLE_Shards=ON \
      -D Trilinos_ENABLE_Sacado=ON \
      -D Trilinos_ENABLE_Epetra=ON \
      -D Trilinos_ENABLE_EpetraExt=ON \
      -D Trilinos_ENABLE_Ifpack=ON \
      -D Trilinos_ENABLE_AztecOO=ON \
      -D Trilinos_ENABLE_Amesos=ON \
      -D Trilinos_ENABLE_Anasazi=ON \
      -D Trilinos_ENABLE_Belos=ON \
      -D Trilinos_ENABLE_ML=ON \
      -D Trilinos_ENABLE_Phalanx=ON \
      -D Trilinos_ENABLE_MiniTensor=ON \
      -D Trilinos_ENABLE_ROL=ON \
      -D Trilinos_ENABLE_NOX=ON \
      -D Trilinos_ENABLE_Stratimikos=ON \
      -D Trilinos_ENABLE_Thyra=ON \
      -D Trilinos_ENABLE_Rythmos=ON \
      -D Trilinos_ENABLE_Stokhos=OFF \
      -D Trilinos_ENABLE_Piro=ON \
      -D Trilinos_ENABLE_Teko=ON \
      -D Trilinos_ENABLE_STKIO=ON \
      -D Trilinos_ENABLE_STKMesh=ON \
      -D Trilinos_ENABLE_Tpetra=ON \
      -D Trilinos_ENABLE_Kokkos=ON \
      -D Trilinos_ENABLE_Tempus=ON \
      -D Tempus_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
      -D Kokkos_ENABLE_Pthread=OFF \
      -D HAVE_INTREPID_KOKKOSCORE=ON \
      -D Trilinos_ENABLE_Ifpack2=ON \
      -D Trilinos_ENABLE_Zoltan2=ON \
      -D Trilinos_ENABLE_MueLu=ON \
      -D Trilinos_ENABLE_STKTransfer=OFF \
      -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
      -D Tpetra_INST_INT_LONG_LONG:BOOL=ON \
      -D Tpetra_INST_INT_INT:BOOL=ON \
      -D Tpetra_INST_DOUBLE:BOOL=ON \
      -D Tpetra_INST_FLOAT:BOOL=OFF \
      -D Tpetra_INST_COMPLEX_FLOAT:BOOL=OFF \
      -D Tpetra_INST_COMPLEX_DOUBLE:BOOL=OFF \
      -D Tpetra_INST_INT_LONG:BOOL=OFF \
      -D Tpetra_INST_INT_UNSIGNED:BOOL=OFF \
      \
      -D Trilinos_ENABLE_Intrepid2=ON \
      \
      -D Trilinos_ENABLE_Amesos2=ON \
      -D Amesos2_ENABLE_KLU2=ON \
      -D Amesos2_ENABLE_SuperLUDist=OFF \
      -D Amesos2_ENABLE_Epetra=OFF \
      \
      -D Trilinos_ENABLE_SEACAS=ON \
      -D Trilinos_ENABLE_SEACASIoss=ON \
      -D Trilinos_ENABLE_SEACASExodus=ON \
      -D SEACAS_ENABLE_SEACASSVDI=OFF \
      -D Trilinos_ENABLE_SEACASFastq=OFF \
      -D Trilinos_ENABLE_SEACASBlot=OFF \
      -D Trilinos_ENABLE_SEACASPLT=OFF \
      \
      -D TPL_ENABLE_Matio=OFF \
      -D TPL_ENABLE_X11=OFF \
 \
      -D TPL_ENABLE_MPI:BOOL=ON \
      -D MPI_BASE_DIR:PATH=$MPI_BASE_DIR \
  \
      -D TPL_ENABLE_Pthread:BOOL=OFF \
  \
      -D TPL_ENABLE_Boost:BOOL=ON \
      -D TPL_ENABLE_BoostLib:BOOL=ON \
      -D TPL_ENABLE_BoostAlbLib:BOOL=ON \
      -D Boost_INCLUDE_DIRS:PATH=$BOOST_DIR/include \
      -D Boost_LIBRARY_DIRS:PATH=$BOOST_DIR/lib \
      -D BoostLib_INCLUDE_DIRS:PATH=$BOOST_DIR/include \
      -D BoostLib_LIBRARY_DIRS:PATH=$BOOST_DIR/lib \
      -D BoostAlbLib_INCLUDE_DIRS:PATH=$BOOST_DIR/include \
      -D BoostAlbLib_LIBRARY_DIRS:PATH=$BOOST_DIR/lib \
  \
      -D TPL_ENABLE_Netcdf:STRING=ON \
      -D Netcdf_INCLUDE_DIRS:PATH=$NETCDF/include \
      -D Netcdf_LIBRARY_DIRS:PATH=$NETCDF/lib \
  \
      -D TPL_ENABLE_HDF5:STRING=ON \
      -D HDF5_INCLUDE_DIRS:PATH=$HDFDIR/include \
      -D HDF5_LIBRARY_DIRS:PATH=$HDFDIR/lib \
  \
      -D TPL_ENABLE_Zlib:STRING=ON \
      -D Zlib_INCLUDE_DIRS:PATH=$HDFDIR/include \
      -D Zlib_LIBRARY_DIRS:PATH=$HDFDIR/lib \
  \
      -D TPL_ENABLE_BLAS:STRING=ON \
      -D TPL_ENABLE_LAPACK:STRING=ON \
      -D TPL_BLAS_LIBRARIES:STRING="$LABLAS_LIBRARIES" \
      -D TPL_LAPACK_LIBRARIES:STRING="$LABLAS_LIBRARIES" \
  \
      -D TPL_ENABLE_ParMETIS:STRING=ON \
      -D ParMETIS_INCLUDE_DIRS:PATH="${PARMETISDIR}/include" \
      -D ParMETIS_LIBRARY_DIRS:PATH="${PARMETISDIR}/lib" \
  \
      -D TPL_ENABLE_yaml-cpp=ON \
      -D yaml-cpp_INCLUDE_DIRS=$YAMLDIR/include \
      -D yaml-cpp_LIBRARY_DIRS=$YAMLDIR/lib \
  \
      -D TPL_ENABLE_SuperLU:STRING=ON \
      -D SuperLU_INCLUDE_DIRS:PATH="${SUPERLU_DIR}/include" \
      -D SuperLU_LIBRARY_DIRS:PATH="${SUPERLU_DIR}/lib" \
  \
      -D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR \
      -D Trilinos_EXTRA_LINK_FLAGS:STRING="-L${HDFDIR}/lib -lnetcdf -lhdf5_hl -lhdf5 -lz -lgfortran -Wl,-rpath,/home/marioju/projects/albany/tpls/lib" \
  \
      -D Trilinos_ENABLE_Moertel:BOOL=OFF \
      -D Trilinos_ENABLE_TriKota:BOOL=OFF \
      -D HAVE_INTREPID_KOKKOSCORE:BOOL=OFF \
      -D Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF \
      -D Amesos2_ENABLE_SuperLU:BOOL=ON \
  \
  $EXTRA_ARGS \
  ${TRILINOS_HOME}

SCOREC:
cmake .. \
  -DCMAKE_C_COMPILER="mpicc" \
  -DCMAKE_CXX_COMPILER="mpicxx" \
  -DCMAKE_INSTALL_PREFIX="/home/marioju/projects/scorec/install" \
  -DENABLE_STK:BOOL=OFF \
  -DENABLE_STK_MESH:BOOL=OFF \
  -DENABLE_SIMMETRIX=True \
  -DSCOREC_CXX_WARNINGS:BOOL=OFF \
  -DSIMMETRIX_LIB_DIR="$SIM_INSTALL_DIR/lib/x64_rhel7_gcc48;$SIM_INSTALL_DIR/lib/x64_rhel7_gcc48/psKrnl" \
  -DSIMMETRIX_INCLUDE_DIR="$SIM_INSTALL_DIR/include" \
  -DSIM_PARASOLID=True \
  -DSIM_MPI="openmpi110" \
  -DMETIS_LIBRARY="/home/marioju/projects/albany/tpls/parmetis-4.0.3/lib/libmetis.a" \
  -DMETIS_INCLUDE_DIR="/home/marioju/projects/albany/tpls/parmetis-4.0.3/include" \
  -DPARMETIS_LIBRARY="/home/marioju/projects/albany/tpls/parmetis-4.0.3/lib/libparmetis.a" \
  -DPARMETIS_INCLUDE_DIR="/home/marioju/projects/albany/tpls/parmetis-4.0.3/include" \
  -DZOLTAN_LIBRARY="/home/marioju/projects/albany/install/Trilinos/MPI_REL/lib/libzoltan.a" \
  -DZOLTAN_INCLUDE_DIR="/home/marioju/projects/albany/install/Trilinos/MPI_REL/include" \
  -DTrilinos_PREFIX:PATH=/home/marioju/projects/albany/install/Trilinos/MPI_REL \
  -DENABLE_ZOLTAN=ON

ALBANY:
export TRI_DIR=/home/marioju/projects/albany/install/Trilinos/MPI_REL
export ALB_DIR=/home/marioju/projects/albany/Albany
export ALBANY_SCOREC_DIR=/home/marioju/projects/scorec/install
export ALBANY_SCOREC_DIR=/home/marioju/projects/scorec/install/lib
cmake \
 -D ALBANY_TRILINOS_DIR=${TRI_DIR} \
 -D ALBANY_SCOREC_DIR=${ALBANY_SCOREC_DIR} \
 -D SCOREC_LIB=${ALBANY_SCOREC_LIB} \
 -D ENABLE_SCOREC:BOOL=ON \
 -D ENABLE_LCM:BOOL=ON \
 -D ENABLE_CTM:BOOL=OFF \
 -D ENABLE_AMP:BOOL=ON \
 -D ENABLE_ANISO:BOOL=OFF \
 -D ENABLE_OMEGA_H:BOOL=OFF \
 -D ENABLE_QCAD:BOOL=OFF \
 -D ENABLE_LCM_SPECULATIVE:BOOL=OFF \
 -D ENABLE_LAME:BOOL=OFF \
 -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
 -D ENABLE_DEBUGGING:BOOL=OFF \
 -D ENABLE_CHECK_FPE:BOOL=ON \
 -D ENABLE_HYDRIDE:BOOL=OFF \
 -D ENABLE_FELIX:BOOL=OFF \
 -D ENABLE_MOR:BOOL=OFF \
 -D ENABLE_ALBANY_CI:BOOL=OFF \
 -D ENABLE_ASCR:BOOL=OFF \
 -D ENABLE_64BIT_INT:BOOL=ON \
 -D ENABLE_ALBANY_EPETRA_EXE:BOOL=ON \
../

**Comment by maxrpi** [comment]
Mario, I don't immediately see a problem with your cmake scripts, though if that's a cut and paste you've defined ALBANY_SCOREC_DIR twice and ALBANY_SCOREC_LIB zero times.
But assuming that was a typo in your comment, I can only say you should not have to disable STK to compile core. I assume you're aware of Trilinos issue #[4770](https://github.com/trilinos/Trilinos/issues/4470) and Dan's corresponding fix in [apf](https://github.com/SCOREC/core/commit/6aca3f2322c9f8c260eea4eea304199c8f7f7f56)? If your link can't find the correct symbol in trilinos, perhaps you're pointing at an older library somewhere else? The commit you list for Trilinos is certainly new enough to have it.

Tonight I did a fresh build of the Trilinos stack, with integrated core, and built a fresh copy of Albany against it. There were no real problems in test with just the crystal plasticity examples with minisolver failing. That said, **I don't compile with Simmetrix**.  However, for what it's worth here's a description of tonight's build.

I was working with the following environment:
```
Currently Loaded Modules:
  1) cmake/3.12.1-wfk2b7e     5) boost/1.68.0-6n3iupn           9) hdf5/1.10.2-eob4dby
  2) gcc/7.3.0-bt47fwr        6) metis/5.1.0-int64-qymyjwg     10) netcdf/4.6.1-7m62oeb
  3) mpich/3.2.1-niuhmad      7) parmetis/4.0.3-int64-ssgv6kc  11) simmetrix-simmodsuite/11.0-180619-a4mef7a
  4) openblas/0.3.2-nro36nb   8) zlib/1.2.11-ldu43ta
```
Note that althought simmodsuite is in my environment, **I'm not enabling Simmetrix**. I've been building core as a sub-package of Trilinos lately, and it works pretty seamlessly, so that's how I went. I've had problems building otherwise and had to hack cmake to fiddle manually with SCOREC_STANDALONE. To do the integrated build, I copied the `src` directory from core to the Trilinos directory and renamed it `SCOREC`. 

At this point I created my build directory and ran a cmake script close to yours with a few differences, viz:
```
 -D Trilinos_ENABLE_SCOREC:BOOL=ON \
 -D PCU_COMPRESS:BOOL=ON \
 -D SCOREC_DISABLE_STRONG_WARNINGS:BOOL=ON \
 -D Trilinos_ENABLE_EXPORT_MAKEFILES:BOOL=OFF \
 -D Trilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF \

```
My make now built both the native Trilinos packages I'd selected and core.

I then configure Albany with 
```
#!/bin/sh

export TRILINOS_INSTALL_DIR=/lore/maxim/trilinos_nightly/install

cmake \
 -D ALBANY_TRILINOS_DIR:FILEPATH="$TRILINOS_INSTALL_DIR" \
 -D ENABLE_SCOREC:BOOL=ON \
 -D ENABLE_LCM:BOOL=ON \
 -D ENABLE_CTM:BOOL=OFF \
 -D ENABLE_AMP:BOOL=ON \
 -D ENABLE_ANISO:BOOL=OFF \
 -D ENABLE_OMEGA_H:BOOL=OFF \
 -D ENABLE_QCAD:BOOL=OFF \
 -D ENABLE_LCM_SPECULATIVE:BOOL=OFF \
 -D ENABLE_LAME:BOOL=OFF \
 -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
 -D ENABLE_DEBUGGING:BOOL=OFF \
 -D ENABLE_CHECK_FPE:BOOL=ON \
 -D Albany_DEPRECATED_DECLARATIONS:BOOL=ON \
 -D ENABLE_HYDRIDE:BOOL=OFF \
 -D ENABLE_FELIX:BOOL=OFF \
 -D ENABLE_MOR:BOOL=OFF \
 -D ENABLE_ALBANY_CI:BOOL=OFF \
 -D ENABLE_ASCR:BOOL=OFF \
 -D ENABLE_64BIT_INT:BOOL=ON \
 -D ENABLE_ALBANY_EPETRA_EXE:BOOL=OFF \
 -D ENABLE_STK:BOOL=ON \
 .. \
 2>&1 | tee config_log

```
The whole build went pretty smoothly, not a lot of warnings. And as I said, make test came out clean.

Note again, if you're using Simmetrix, that may be a hurdle you need to clear on your own.

**Comment by cwsmith** [comment]
I assume this is no longer an issue and closing it.
