### ISSUE TITLE
Build Error on DCS with simmetrix

### ISSUE THREAD

**Issue by jacobmerson** [SCOREC/core#233]
I am not sure if the following issue is due to the lack of parasolid on DCS, or if it is due to a version bump to simmodsuite 15, but the `GAM_createFromNativeModel` function does not exist called here: https://github.com/SCOREC/core/blame/master/gmi_sim/gmi_sim.cc#L495

**Comment by cwsmith** [comment]
@KennethEJansen also saw this error on what I understand was an x86 system with the CAD kernels.

**Comment by cwsmith** [comment]
See #235
