### ISSUE TITLE
Writing tags to a mesh without having to convert to a field

### ISSUE THREAD

**Issue by a-jp** [SCOREC/core#250]
Hi,
Based on this post [tags/fields](https://gist.github.com/bgranzow/98087114166956646da684ed98acab02) I was trying to learn about tags and fields.  However, I do not seem to be able to get a tag written to a mesh,  I seem to have to always convert it to a field.  Is that intended?  If so, how to I store integer based fields?  I am using the following:

```c++
apf::MeshTag *create_int_tag(apf::Mesh *m, int dim)
{
	apf::MeshTag *tag = m->createIntTag("my_tag", 1); // 1 is size of tag
	apf::MeshEntity *elem;
	apf::MeshIterator *it = m->begin(dim);
	int vals[1];
	vals[0] = PCU_Comm_Self();
	while ((elem = m->iterate(it)))
		m->setIntTag(elem, tag, vals);
	m->end(it);
	return tag;
}
```
So firstly this never appears in the vtk output, secondly, if I try to adapt the **convert_my_tag**  function in the above link to be integer based so that I can see it in the vtk file, I can't because I don't seem to be able to write integer based values.  Is there something I'm doing wrong?  There does not seem to be an apf::INTEGER, do I always have to cast to double? It works fine if I do, but I wanted to check.

Finally, can I ask, is this following (which I'm using) the correct way to store a single double precision number per cell/element?

```c++
apf::createField(m, fieldName, apf::SCALAR, apf::getConstant(dim));
```
I found that in [this link](https://github.com/CEED/PUMI/blob/master/ma/maDBG.cc).  I am looking for something that will have ghost allocation automatically created and exchanged.  My code is a cell-entered (collocated) finite volume code.   I just want to store say pressure in every cell/element and be able to do parallel exchange on that variable automagically.
Thanks,
Andy

**Comment by jacobmerson** [comment]
I'm not a core developer, so take what I say with a grain of salt...but I think under the hood fields are actually stored on the mesh as tags, unless they are frozen in which case they are stored as arrays.

The underlying field infrastructure supports other types, however I think that only double fields are exposed to the user. @wrtobin has pull request #234 which deals with complex field support so he might be able to give some insight into what the current thought process is on how to bring field typing to the c-style apis.

In terms of writing tags to vtk it looks like we don't do it currently. You can look at the details of how we write out [here](https://github.com/SCOREC/core/blob/d9eeb2b028afd6182b4d3bc1063d3aae3a348760/apf/apfVtk.cc). I suspect adding the capability to write tags shouldn't be too challenging.

**Comment by cwsmith** [comment]
@jacobmerson is correct: fields are implemented with tags, and tags cannot be written to vtk without first converting them to fields 

As you discovered, fields don't support an storing integers and converting to a double is required.

The field call you pasted will associate a double with each element.  Here is another example use:
https://github.com/SCOREC/core/blob/59d03165714ac2c2069f4de6a3d08bd3ba041d20/test/create_mis.cc#L27-L29

Would you please expand a bit on what is needed with relation to ghosting and fields?  Do you need a parallel synchronization routine where owned elements update the field values for all their ghost copies?

**Comment by a-jp** [comment]
Thank you @jacobmerson and @cwsmith.  I'm fine to construct a field, just wanted to make sure I was getting expected results.

> Do you need a parallel synchronization routine where owned elements update the field values for all their ghost copies?

That's exactly right. I meant to say, if I do construct a field this way, and then construct ghost cells (which I'm having a segfault from so that will need to be a separate question), will the field be given an allocation within the ghost elements automatically, and will there be, on a suitable call to a synchronization routine, an exchange of the data?  Could you give me an example of the synchronization call that exchanged a SCALAR assuming the above is correct?

So to be clear:
```c++
 apf::createField(m,"colors",apf::SCALAR, 
                                         apf::getConstant(m->getDimension()));
```
is the way to allocate field data for elements if I'm trying to hijack PUMI for a cell-centered FVM code?

**Comment by cwsmith** [comment]
#245 has an example of scalar (`double`) field creation and sync

**Comment by cwsmith** [comment]
This seems to be resolved for now.  Please reopen if needed.
