### ISSUE TITLE
How to start with core after installation. 

### ISSUE THREAD

**Issue by ztdepztdep** [SCOREC/core#253]
Dear sir:
    I want to know how to start with core after installation. I found many test file in the test directory. Which one should be started with first.
Regards

**Comment by cwsmith** [comment]
Hello,

What would you like to do with core/pumi?

**Comment by ztdepztdep** [comment]
I am perform phase field simulation of solidification. I want to develop a 3D FVM code based on the pumi. Could you please give me some suggestions.

**Comment by cwsmith** [comment]
That sounds good.  

I'd suggest going through the wiki pages to learn about PUMI.  Please post any specific questions you have about PUMI features, the underlying concepts, or the APIs.

**Comment by cwsmith** [comment]
I'm going to close this issue.  Please feel free to open new issues with specific questions.
