### ISSUE TITLE
Parasolid Error when working with convert

### ISSUE THREAD

**Issue by jjcambar** [SCOREC/core#258]
When trying to use the convert utility this error arises:

fix_pyramids 1 attach_order 0 enable_log 0
native-model './pipe1-8_nat.x_t' model 'pipe1-8.smd' simmetrix mesh 'pipe1-8.sms' output mesh 'bz2:mdsMesh_bz2/'
Error: Code: 200 String: No license for feature parasolid
terminate called after throwing an instance of 'SimError*

I am using SimModeler 7.0 and SimModSuite 11.0-171006. SimModeler can be opened and used to generate the .sms and .smd files, however the convert utility is unable to locate the parasolid license.

**Comment by hapfang** [comment]
@cwsmith Hey Cameron, have you guys seen this error before? I don't remember if the parasolid feature really requires additional license or not.

**Comment by cwsmith** [comment]
Hello,
Do you have a Simmetrix license file path set with the environment variable `SIM_LICENSE_FILE`?  If so, run a `grep -i parasolid` in the file and you should get a hit for the `parasolid` feature.

**Comment by jjcambar** [comment]
The Simmetrix license file path is set in the environment and the file itself includes the simmodeler_parasolid feature.

**Comment by hapfang** [comment]
Joe, could you please show us how you set the Simmetrix license path?

**Comment by cwsmith** [comment]
@jjcambar That sounds like `SIM_LICENSE_FILE` is pointing at the simmodeler license file (`.lic` ?) instead of the simmodsuite license.

**Comment by jjcambar** [comment]
I set the Simmetrix license path with:

export SIM_LICENSE_FILE=/"path to license file"/simmetrix.lic

**Comment by hapfang** [comment]
Cameron is right. In your case, `SIM_LICENSE_FILE` is pointed to the Simmodeler license. Please contact the Simmetrix Inc for the SimModSuite license if you couldn't find it anywhere.

**Comment by jjcambar** [comment]
Thank you for your assistance. Will look into this.
