### ISSUE TITLE
pumi_mesh_load with multiple CPUs 

### ISSUE THREAD

**Issue by ztdepztdep** [SCOREC/core#259]
Dear sir:
     I want to load the serial "pipe.smb" into 5 CPUs. But how to partition it and send every part to these 5 CPUs. I load it with :
     pMesh mesh = pumi_mesh_load(g, "/home/ztdep/Downloads/core/pumi-meshes/pipe/pipe.smb", 1);
   but it gives me the error about:

==================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 8956 RUNNING AT linux-9owh
=   EXIT CODE: 134
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES

**Comment by cwsmith** [comment]
Take a look at the `split` or `zsplit` binaries; they are described here:
https://github.com/SCOREC/core/wiki/Partitioning

After that I'd suggest taking a look at the source code for `render.cc`  (https://github.com/SCOREC/core/blob/b384d6cef49cda83b8176d2ba860e3a8923ff572/test/render.cc).  It is one probably the simplest example of a tool that loads a partitioned mesh.

**Comment by cwsmith** [comment]
I should have provided a `pumi_mesh_load` specific example; the previous response uses the APF lower level interface.

Page 71, Section 12.1, of the pumi user's guide
https://scorec.rpi.edu/~seol/PUMI.pdf
 has an example program that loads a partitioned mesh.  The term 'part' refers to the set of mesh elements, and their closure (faces, edges, vertices) assigned to a process.  IIRC, the pumi_mesh_load interface can either partition a serial mesh (one `.smb` file = serial mesh) or load a mesh that is already partitioned (multiple `.smb` files = partitioned mesh).  Either way, if you want to partition to `N` processes, or load a mesh that has `N` parts, then you need to run with `N` MPI processes (i.e., `mpirun -np N <name of program> <arguments...>`).

**Comment by ztdepztdep** [comment]
> I should have provided a `pumi_mesh_load` specific example; the previous response uses the APF lower level interface.
> 
> Page 71, Section 12.1, of the pumi user's guide
> https://scorec.rpi.edu/~seol/PUMI.pdf
> has an example program that loads a partitioned mesh. The term 'part' refers to the set of mesh elements, and their closure (faces, edges, vertices) assigned to a process. IIRC, the pumi_mesh_load interface can either partition a serial mesh (one `.smb` file = serial mesh) or load a mesh that is already partitioned (multiple `.smb` files = partitioned mesh). Either way, if you want to partition to `N` processes, or load a mesh that has `N` parts, then you need to run with `N` MPI processes (i.e., `mpirun -np N <name of program> <arguments...>`).

Dear sir:
    Thanks. The probem is that  I want to load a serial mesh into 4 parts. but it cann't work. I run it with
   "mpiexec -np 4 main".
```
{
int main(int argc, char** argv)
MPI_Init(&argc, &argv);
pumi_start(); // equivalent to PCU_Comm_Init()
pGeom g = pumi_geom_load("/home/ztdep/Downloads/core/pumi-meshes/pipe/pipe.dmg", "mesh");
pMesh mesh = pumi_mesh_load(g, "/home/ztdep/Downloads/core/pumi-meshes/pipe/pipe.smb", 1);
}
```

**Comment by cwsmith** [comment]
Hmmm. The call to `pumi_mesh_load(...)` looks OK.

The following code:

``` C++
#include "mpi.h"                                                                                                                                                                                                                                                                 
#include "pumi.h"                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                 
int main(int argc, char** argv)                                                                                                                                                                                                                                                  
{                                                                                                                                                                                                                                                                                
  MPI_Init(&argc,&argv);                                                                                                                                                                                                                                                         
  pumi_start();                                                                                                                                                                                                                                                                  
  pGeom g = pumi_geom_load(argv[1], "mesh");                                                                                                                                                                                                                                     
  pMesh m = pumi_mesh_load(g, argv[2], 1);                                                                                                                                                                                                                                       
  pumi_geom_delete(g);                                                                                                                                                                                                                                                           
  pumi_mesh_delete(m);                                                                                                                                                                                                                                                           
  pumi_finalize();                                                                                                                                                                                                                                                               
  MPI_Finalize();                                                                                                                                                                                                                                                                
}
```

Runs successfully with either:

```
$ ./pumiLoadMesh /path/to/pipe.dmg /path/to/pipe.smb

=== mesh size and tag info ===
# global ent: v 784, e 3332, f 4438, r 1889

(p0) # local ent: v 784, e 3332, f 4438, r 1889

(p0) # own ent: v 784, e 3332, f 4438, r 1889

mesh shape: "Linear"
```

or, creating four parts:

```
$ mpirun -np 4 ./pumiLoadMesh /path/to/pipe.dmg /path/to/pipe.smb                                                                      

=== mesh size and tag info ===
# global ent: v 784, e 3332, f 4438, r 1889

(p0) # local ent: v 268, e 983, f 1179, r 463
(p1) # local ent: v 255, e 958, f 1192, r 488
(p2) # local ent: v 255, e 941, f 1158, r 471
(p3) # local ent: v 279, e 1000, f 1189, r 467

(p0) # own ent: v 268, e 983, f 1179, r 463
(p1) # own ent: v 95, e 624, f 1017, r 488
(p2) # own ent: v 142, e 725, f 1053, r 471
(p3) # own ent: v 279, e 1000, f 1189, r 467

mesh shape: "Linear"
```

**Comment by ztdepztdep** [comment]
> Hmmm. The call to `pumi_mesh_load(...)` looks OK.
> 
> The following code:
> 
> ```c++
> #include "mpi.h"                                                                                                                                                                                                                                                                 
> #include "pumi.h"                                                                                                                                                                                                                                                                
>                                                                                                                                                                                                                                                                                  
> int main(int argc, char** argv)                                                                                                                                                                                                                                                  
> {                                                                                                                                                                                                                                                                                
>   MPI_Init(&argc,&argv);                                                                                                                                                                                                                                                         
>   pumi_start();                                                                                                                                                                                                                                                                  
>   pGeom g = pumi_geom_load(argv[1], "mesh");                                                                                                                                                                                                                                     
>   pMesh m = pumi_mesh_load(g, argv[2], 1);                                                                                                                                                                                                                                       
>   pumi_geom_delete(g);                                                                                                                                                                                                                                                           
>   pumi_mesh_delete(m);                                                                                                                                                                                                                                                           
>   pumi_finalize();                                                                                                                                                                                                                                                               
>   MPI_Finalize();                                                                                                                                                                                                                                                                
> }
> ```
> 
> Runs successfully with either:
> 
> ```
> $ ./pumiLoadMesh /path/to/pipe.dmg /path/to/pipe.smb
> 
> === mesh size and tag info ===
> # global ent: v 784, e 3332, f 4438, r 1889
> 
> (p0) # local ent: v 784, e 3332, f 4438, r 1889
> 
> (p0) # own ent: v 784, e 3332, f 4438, r 1889
> 
> mesh shape: "Linear"
> ```
> 
> or, creating four parts:
> 
> ```
> $ mpirun -np 4 ./pumiLoadMesh /path/to/pipe.dmg /path/to/pipe.smb                                                                      
> 
> === mesh size and tag info ===
> # global ent: v 784, e 3332, f 4438, r 1889
> 
> (p0) # local ent: v 268, e 983, f 1179, r 463
> (p1) # local ent: v 255, e 958, f 1192, r 488
> (p2) # local ent: v 255, e 941, f 1158, r 471
> (p3) # local ent: v 279, e 1000, f 1189, r 467
> 
> (p0) # own ent: v 268, e 983, f 1179, r 463
> (p1) # own ent: v 95, e 624, f 1017, r 488
> (p2) # own ent: v 142, e 725, f 1053, r 471
> (p3) # own ent: v 279, e 1000, f 1189, r 467
> 
> mesh shape: "Linear"
> ```

It is great. It seems my lib has some problem. I tried to run with 
   `mpiexec -np 4 zsplit ./pipe.dmg ./pipe.smb dd 4`
It gives me the error code of "apf_zoltan compiled empty". Could you please give me some suggestions.

```
mesh ./pipe.smb loaded in 0.017707 seconds
number of tet 867 hex 0 prism 1022 pyramid 0
mesh entity counts: v 784 e 3332 f 4438 r 1889
APF FAILED: apf_zoltan compiled empty !
```

**Comment by ztdepztdep** [comment]
> Hmmm. The call to `pumi_mesh_load(...)` looks OK.
> 
> The following code:
> 
> ```c++
> #include "mpi.h"                                                                                                                                                                                                                                                                 
> #include "pumi.h"                                                                                                                                                                                                                                                                
>                                                                                                                                                                                                                                                                                  
> int main(int argc, char** argv)                                                                                                                                                                                                                                                  
> {                                                                                                                                                                                                                                                                                
>   MPI_Init(&argc,&argv);                                                                                                                                                                                                                                                         
>   pumi_start();                                                                                                                                                                                                                                                                  
>   pGeom g = pumi_geom_load(argv[1], "mesh");                                                                                                                                                                                                                                     
>   pMesh m = pumi_mesh_load(g, argv[2], 1);                                                                                                                                                                                                                                       
>   pumi_geom_delete(g);                                                                                                                                                                                                                                                           
>   pumi_mesh_delete(m);                                                                                                                                                                                                                                                           
>   pumi_finalize();                                                                                                                                                                                                                                                               
>   MPI_Finalize();                                                                                                                                                                                                                                                                
> }
> ```
> 
> Runs successfully with either:
> 
> ```
> $ ./pumiLoadMesh /path/to/pipe.dmg /path/to/pipe.smb
> 
> === mesh size and tag info ===
> # global ent: v 784, e 3332, f 4438, r 1889
> 
> (p0) # local ent: v 784, e 3332, f 4438, r 1889
> 
> (p0) # own ent: v 784, e 3332, f 4438, r 1889
> 
> mesh shape: "Linear"
> ```
> 
> or, creating four parts:
> 
> ```
> $ mpirun -np 4 ./pumiLoadMesh /path/to/pipe.dmg /path/to/pipe.smb                                                                      
> 
> === mesh size and tag info ===
> # global ent: v 784, e 3332, f 4438, r 1889
> 
> (p0) # local ent: v 268, e 983, f 1179, r 463
> (p1) # local ent: v 255, e 958, f 1192, r 488
> (p2) # local ent: v 255, e 941, f 1158, r 471
> (p3) # local ent: v 279, e 1000, f 1189, r 467
> 
> (p0) # own ent: v 268, e 983, f 1179, r 463
> (p1) # own ent: v 95, e 624, f 1017, r 488
> (p2) # own ent: v 142, e 725, f 1053, r 471
> (p3) # own ent: v 279, e 1000, f 1189, r 467
> 
> mesh shape: "Linear"
> ```

Thanks, I forgotten to linke with parmetis and zoltan. Now it give me some meaning ful results. But still have errors:PARMETIS ERROR: The sum of tpwgts for constraint #0 is not 1.0

```
 mpiexec -np 2 ./build/main 
PARMETIS ERROR: The sum of tpwgts for constraint #0 is not 1.0
=== mesh size and tag info === 
# global ent: v 784, e 3332, f 4438, r 1889
(p0) # local ent: v 784, e 3332, f 4438, r 1889
(p1) # local ent: v 0, e 0, f 0, r 0
(p0) # own ent: v 784, e 3332, f 4438, r 1889
mesh shape: "Linear"

```

**Comment by ztdepztdep** [comment]
recompile with pametis with 
"REALTYPEWIDTH to 64 in metis.h"
and it works now.
