### ISSUE TITLE
Does loadMdsFromANSYS supprot ANSYS_FLUENT Mesh

### ISSUE THREAD

**Issue by ztdepztdep** [SCOREC/core#264]
Dear sir:
    I want to load fluent mesh into the core. Does the function loadMdsFromANSYS support it?
Regards

**Comment by cwsmith** [comment]
It looks like a `.node` file and `.elem` file are required:
https://github.com/SCOREC/core/blob/b384d6cef49cda83b8176d2ba860e3a8923ff572/test/ansys.cc
I'm guessing Fluent can export that format.
