### ISSUE TITLE
Refining the mesh to keep at least two edges per geometry

### ISSUE THREAD

**Issue by erdemeren** [SCOREC/core#266]
Hello,

I was trying to use meshadapt to refine a mesh such that each line geometry would be represented by at least two edges. Ideally and more generally, I would need the mesh to keep at least a vertex within each geometry.

Could you describe how to achieve such a condition or provide an implementation to achieve that?

I tried to achieve this by a scalar field defined over vertices of the prior mesh to use as the return value for ma::IsotropicFunction::getValue(ma::Entity* v) calls. I thought the field was integrated over edge element and the edge is to be refined if the intergral is less than 0.5, but it didn't work. Also, I'm not sure how the field values are updated through meshadapt iterations and if I should update the field between the iterations.

Thank you,

**Comment by mortezah** [comment]
The easiest way to achieve this is to sub-class the `IdentitySizeField` class and implement the desired effect inside the member function `shouldSplit`. For example look at the `UniformRefiner` here https://github.com/SCOREC/core/blob/c33f4c4e3ed0656326952703f04a84a1b0dc9150/ma/maSize.h#L59

So in your application you can include `maSize.h` and do the following:

```
class ModelEdgeRefiner : public ma::IdentitySizeField
{
  ModelEdgeRefiner(Mesh* m): 
    IdentitySizeField(m)
  {
  }
  bool shouldSplit(Entity*)
  {
    // TODO: if entity is a mesh edge spanning a model edge return true
  }
};
```

Then you can setup adapt as follows

```
ma::Input* in = ma::configure(m);
in->sizeField = new ModelEdgeRefiner(m); // m is the mesh
// the rest of adapt setup
```

**Comment by erdemeren** [comment]
Defining a new sizefield worked perfectly:
```
bool shouldSplit(ma::Entity* edge) {
    apf::Downward d_v;
    mesh->getDownward(edge, 0, d_v);
    int dim_e = mesh->getModelType(mesh->toModel(edge));
    int dim_v0 = mesh->getModelType(mesh->toModel(d_v[0]));
    int dim_v1 = mesh->getModelType(mesh->toModel(d_v[1]));
    return (dim_e > dim_v0 and dim_e > dim_v1);
}
```
Thank you!
