### ISSUE TITLE
Which API return the global index of the ghost cell?

### ISSUE THREAD

**Issue by ztdepztdep** [SCOREC/core#267]
Friends:
     I have partitioned the mesh sucessfully with PUMI. On each CPU, i need to generate the ghost cells and the global index of the ghost cell are also needed for the FVM .
    Which API provide these functionalities.
Regards

**Comment by cwsmith** [comment]
Hello.  

I'd suggest calling one of the global numbering functions described in the pumi users guide before creating ghosts:
https://scorec.rpi.edu/~seol/PUMI.pdf

Alternatively, take a look at the example here: 

https://github.com/SCOREC/core/issues/245#issuecomment-532708443
https://github.com/SCOREC/core/blob/551d71589bc48af0dc5d348751bda95f782ee51c/test/constructThenGhost.cc

Note, this example relies on the `apfToPumi` branch.

**Comment by cwsmith** [comment]
I'm going to close this issue.  Please reopen it if needed.
