### ISSUE TITLE
Simmodsuite version error

### ISSUE THREAD

**Issue by daisy20170101** [SCOREC/core#269]
It turns out that 190921 also need three arguments here. 

#if SIMMODSUITE_MAJOR_VERSION <= 14 && SIMMODSUITE_MINOR_VERSION < 190928
      pPList l = EN_getMatchingEnts(ent, NULL);
#else
      pPList l = EN_getMatchingEnts(ent, NULL, 0);
#endif

Fix the error by changing it.

**Comment by cwsmith** [comment]
Thank you.  This was fixed in https://github.com/SCOREC/core/commit/916927bf24afb236754c49329b4fe5161f3cb42e.
