### ISSUE TITLE
Vertex motion in parallel

### ISSUE THREAD

**Issue by a-jp** [SCOREC/core#276]
I have a parallel distributed apf mesh, which I can convert to a pumi mesh.  Therefore I'm happy to use whatever API is required.  I would like to move the vertices of my mesh.  I have computed the new position.  I believe I should call ```setPoint``` and within that protect the call for each vertex with 
```
if (m->isOwned(vert))
  m->setPoint(vert, 0, newPos);
```

Could I ask for some help with parallel please.  What should I so to ensure this is all sync'd for parallel and I obtain the same "moved mesh" in serial and parallel?
Thanks,
Andy

**Comment by mortezah** [comment]
I believe that can be achieved by using synchronize

void apf::synchronize (Field *  f, Sharing * shr = 0) 

Where field would be the coordinate field.

**Comment by a-jp** [comment]
Ok thank you.  I've never had cause to obtain the coordinate field, always just used ```getPoint```.  How do I do that?  I have not used the sharing object explicitly before, again what would be the recommendation there for the vertex coordinates?  Do you know of a working example?

**Comment by mortezah** [comment]
You can use

mesh->getCoordinateField()

**Comment by a-jp** [comment]
Ok, that's easy... Can I just leave the default value for sharing?

**Comment by mortezah** [comment]
I think our comments crisscrossed. In general note that if you have meshes with matching entities the synchronize may cause issues. In that case one may be able to use a user-defined sharing to handle the problem.

**Comment by a-jp** [comment]
Sorry about that.... I don't know what:

> Note that if your mesh has matching entities this may cause problems.

Could you explain?

**Comment by mortezah** [comment]
Then, you probably dont have mesh with matching entities. 

But for future reference, in a mesh with matching entities there is a connection between verts of 2 or more model boundaries (think of a cube where two sides are matched meaning the verts on one side have the same coordinate as the verts on the other side except for a translation, this is sometimes used to handle problems with period bounday conditions.) The way this is handled in core is by a sharing object. Remote copies (a concept useful for partitioned meshes) is also handled by sharing object. But there is a significant difference between them. In the matching one the sharing object has to ensure coordinates are the same except for the translation but the remote one has to ensure coordinates are exactly the same. Now synchronize by default assumes the latter. So if the mesh has matched entities the end up getting the same coordinates after the call to synchronize.

**Comment by a-jp** [comment]
Ok thank you.  I do have a distributed parallel mesh of mixed elements, but I do not have period boundaries so I believe based on the above I can use the default sharing object.  Many thanks for the clarity.

**Comment by mortezah** [comment]
Yes, that's correct. 

Let me know if there is any issues.

**Comment by a-jp** [comment]
will do

**Comment by jacobmerson** [comment]
There is also the [`displaceMesh`](https://www.scorec.rpi.edu/~seol/scorec/doxygen/namespaceapf.html#a8f5fee4fb7d38918b96a0f19645d9009) function which can do what you are talking about (if you already have the values you want to displace by in a field. e.g. if you are doing an updated lagrangian analysis and you already have the displacements in a field.

**Comment by a-jp** [comment]
Ok thanks for that.  I assume the field should be a VECTOR3 type?

**Comment by cwsmith** [comment]
@a-jp I assume this can be closed?

**Comment by a-jp** [comment]
Yep. Thanks
