### ISSUE TITLE
Saving higher order Bezier meshes to smb

### ISSUE THREAD

**Issue by mortezah** [SCOREC/core#282]
This capability is needed in the near future.

**Comment by cwsmith** [comment]
@mortezah If it does not exist already, is this feature still needed?

**Comment by mortezah** [comment]
I think it would be good to have it as we move towards doing problems with highly curved meshes.

Saving higher order fields (coordinate field in this case) is relatively straightforward in pumi except for Bezier. I believe that's because of the way order of the Bezier fields is handled in the current implementation (as a global variable in the crv name space). I have thought about this a bit and I think I know how to fix this but never got the chance to finish it. But I still like to do that at some point.

**Comment by mortezah** [comment]
@cwsmith I am closing this issue for now. With the hack mentioned in my last comment saving higher-order meshes and reading the back works fine for now.
