### ISSUE TITLE
Any tools in core or test to mesh a 3D point cloud?

### ISSUE THREAD

**Issue by KennethEJansen** [SCOREC/core#283]
It looks like TetGen and Gmsh might be able to do what I want but, since I am more familiar with SCOREC/core I thought I would check in to see if anyone has put together a tool to do this.  Conversely if someone has an example of doing this with Gmsh or TetGen and getting the mesh back into mds that would work too.

The geometry is not convex so it would seem that constrained Delaunay is the best route.  I think I can get surface connectivity for my boundary out of MatLab (which gives me a constrained Delaunay of each of my boundaries).  Note I also have created classification of the points onto a topological box (8 model verts, 12 model edges, 6 model faces, and the remainder on the region).

**Comment by cwsmith** [comment]
I have not tried meshing a 3D point cloud before; any notes on the process/tools you find useful would be good to have for future reference.

This example will read a gmsh mesh:
https://github.com/SCOREC/core/blob/master/test/gmsh.cc
It will read in a SCOREC topological model (`.dmg`) which can be created from a GeomSim `.smd` using
https://github.com/SCOREC/core/blob/master/test/mdlConvert.cc .

**Comment by cwsmith** [comment]
Please reopen this if there are updates or questions.
