### ISSUE TITLE
SCOREC compilation error due to changes to STK Trilinos package

### ISSUE THREAD

**Issue by ikalash** [SCOREC/core#285]
SCOREC failed to compile in the Albany nightlies last night due to a change in the STK Trilinos package.  The old versions of the set_cell_topology and get_cell_topology routines have been deprecated.  There are alternates in Trilinos/packages/stk/stk_mesh/stk_mesh/base/MetaData.hpp; see discussion at the end of this issue https://github.com/trilinos/Trilinos/issues/6522 .  Could you please fix the problem.  @alanw0 is a STK developer and should be able to help if you have any issues/questions.

**Comment by cwsmith** [comment]
@alanw0 Do these changes https://github.com/SCOREC/core/pull/286/files make sense?  I'm new to STK.

**Comment by ikalash** [comment]
Thanks for doing this so fast, Cameron!  Your changes look good to me and I was able to compile the code with this branch of SCOREC.  We'd need all of the changes working in Albany in order to test that everything is good now.  Hopefully I'll have something ready tomorrow.

**Comment by cwsmith** [comment]
Thank you @ikalash.  The fixes have been merged to `develop` and should be in `master` by tomorrow morning.

**Comment by ikalash** [comment]
Great, thanks for fixing it @cwsmith !

**Comment by ikalash** [comment]
Seems this is still not in master.  @cwsmith , any idea on when it will get merged into master?  It is will take awhile, I might switch the nightlies to use develop for the time being.

**Comment by cwsmith** [comment]
@ikalash It is there now:
https://github.com/SCOREC/core/commits/master

**Comment by ikalash** [comment]
Oh ok great - thanks!
