### ISSUE TITLE
MeshAdapt: better metric quality

### ISSUE THREAD

**Issue by ibaned** [SCOREC/core#29]
we should use a single metric to measure anisotropic quality, and isotropic quality should not involve the size field at all.

**Comment by ibaned** [comment]
Look at the bigger picture. In this function:

https://github.com/SCOREC/core/blob/master/ma/maQuality.cc#L56

it is measuring six edges and one tetrahedron. right now the edges are measured using the Q at the center of each edge. We want to change that, so that edges will be measured using the Q at the center of the tetrahedron. So, `MetricSizeField::measure` should accept a Q value instead of interpolating it, that way we can do something like

```
Q = interpolateQ(tetrahedron);
for (edge (i) in edges)
  l[i] = measure(edge, Q);
V = measure(tetrahedron, Q);
```

As a consequence `measure` may not even need to be a method of `MetricSizeField`, because it accepts the metric so it doesn't need to access size field values anymore.

**Comment by mortezah** [comment]
what about the calls to measure in `shouldSplit(Entity* edge)` and `shouldCollapse(Entity* edge)`? Don't we want them to be evaluated using the single metric Q?

**Comment by ibaned** [comment]
Good question. For those calls, it is okay to use the metric interpolated at the center of the edge.

**Comment by mortezah** [comment]
so then, I will keep the `measure` method in `MetricSizeField` the way that it is and write a new one for the purposes of  quality measurements in "maQuality".

**Comment by ibaned** [comment]
That makes sense, the `MetricSizeField` method can call the standalone function.

**Comment by mortezah** [comment]
I just pushed to commits, one adding a new test case, and one implementing the above changes. I for the simple test case that I have, I do not see any differences in the final adapted meshes obtained by the old and new approaches. Could this be because we are using linear meshes?

**Comment by ibaned** [comment]
Thanks !

I think we will only notice a difference for size fields with high metric gradients, i.e. when the metrics at the four corners of the tetrahedron are very very different. This usually happens the size field comes from an error estimator.

The main part of this issue is done then (in commit eb6501f), so I guess we can close it for now.
