### ISSUE TITLE
Access MeshEntity without iterator

### ISSUE THREAD

**Issue by tuckerbabcock** [SCOREC/core#291]
Is there an API to access a MeshEntity of a given dimension with an index, instead of using an iterator?

**Comment by tuckerbabcock** [comment]
Nevermind, I believe that is what this function is for:
https://github.com/SCOREC/core/blob/bc34e3f7cfd8ab314968510c71486b140223a68f/mds/apfMDS.h#L193

**Comment by tuckerbabcock** [comment]
Looking at this note in the header for the above function:
https://github.com/SCOREC/core/blob/bc34e3f7cfd8ab314968510c71486b140223a68f/mds/apfMDS.h#L187-L193
It says to call `apf::reorderMdsMesh` after any mesh modification. Is that required if I modify entities of a different dimension than the entity I'm querying?

For a concrete example, I'd like to use `apf::getMdsEntity` to find two specific mesh vertices, and use them to construct a mesh edge, and then repeat by finding more vertices to construct another edge, and so on. Do I need to call `apf::reorderMdsMesh` between each edge construction?

**Comment by mortezah** [comment]
I don't know the answer to that questions. @cwsmith do you know anyone who is more familiar with mds implementations? Do you think Seegyoung would know the answer to this question?

**Comment by cwsmith** [comment]
This went offline for a few iterations.  The outcome was the following bottom-up mesh construction example put together by @mortezah.

'core/test/construct_bottom_up.cc' https://github.com/SCOREC/core/commit/d67acb7343730012a2bf8609a584653aa1f6a7c4 makes a pumi mesh using a bottom-up approach. It makes use of the following connectivity information:

1) Edge 2 Vertex Connectivity
2) Face 2 Edge Connectivity
3) Tet to Face Connectivity

**Comment by tuckerbabcock** [comment]
I think we can close this issue, the example put together by Morteza provides a template for what I was trying to accomplish.
