### ISSUE TITLE
Conversion of mesh entity between simModSuite and PUMI

### ISSUE THREAD

**Issue by eisungy** [SCOREC/core#295]
I have a question about conversion between simModSuite and PUMI.

I'm trying to create a field on each vertex so that I can see it on paraview through writeVtkFiles.

Below is my code snippet.

```
   udsF = apf::createPackedField(pumi_mesh, "UDSym", 1, NULL);

    apf::MeshIterator* it = pumi_mesh->begin(0);
    apf::MeshEntity* ment = pumi_mesh->iterate(it);
    std::cout<<"from iterator, available node code = "<<udsF->countNodesOn(ment)<<std::endl;
    pumi_mesh->end(it);

   // List mesh vertices in order
    pGEdgeEIter eit = M_orderedEdgeOnGEdgeIter(mesh, wallModelEdge, 1);
    while (pEdge e = GEdgeEIter_next(eit)) {
      pVertex vsim = E_vertex(e, 0);
      assert(vsim);
      apf::MeshEntity* vpumi = reinterpret_cast<apf::MeshEntity*>(vsim);
      std::cout<<" available node count = "<<udsF->countNodesOn(vpumi)<<std::endl;
```

For the first cout, I got 1, but for the second one, I got 0. I doubt the line,
```
  apf::MeshEntity* vpumi = reinterpret_cast<apf::MeshEntity*>(vsim);
```
, but I actually mimic a line in apfSIM.cpp of core.

Could you somebody help out this problem, please?

**Comment by mortezah** [comment]
`countNodesOn` expect a type (e.g., `apf::Mesh::VERTEX`) not a `MeshEntity`.

To get a type of mesh entity you can sue `apf::Mesh2::getType` api.

Also, I don't understand the second part of the code. In other words, if you already have a pumi mesh, why is it necessary to go back to the simmetrix mesh?

**Comment by eisungy** [comment]
Hi @mortezah 
Thank you for your comments. I'll take a carefully look at the types in the CORE source code.

As for your question about use of simmetrix mesh even with pumi mesh, ...
I have a wall curve that consists of multiples vertices. I need to tag an index on each vertex in order  along the curve. 

I can find a model edge of the wall curve from simmetrix mesh and pumi mesh. But for pumi mesh, then, I might need reverse classification to find mesh vertices classified on the model curve. Also I would need to use second order adjacency several times to find an adjacent mesh vertex.  Because I'm not quite familiar with detailed APIs in CORE and don't know how to find the function, so I decided to use `M_orderedEdgeOnGEdgeIter` from SimModSuite.

**Comment by eisungy** [comment]
@mortezah 

If I understand source code correctly, it appears field-related class has a wrapper member function for `countNodesOn` to have `MeshEntity`.

The relevant function definition is below.

https://github.com/SCOREC/core/blob/2472c570dc3a9e5acc23146288822733759558a1/apf/apfField.cc#L32

I see some examples in CORE as

https://github.com/SCOREC/core/blob/2472c570dc3a9e5acc23146288822733759558a1/pumi/pumi_numbering.cc#L134

https://github.com/SCOREC/core/blob/ecc64db4e488b64d39a7439d50f711e8cdc7f1c6/apf/apfArrayData.cc#L56

If `countNodesOn` does not have a problem, I wonder if  below line has no issue.
```
  apf::MeshEntity* vpumi = reinterpret_cast<apf::MeshEntity*>(vsim);
```
After I get a list of vertices in simmetrix mesh, I plan to tag indices on the corresponding vertices in PUMI mesh.

Thanks a lot!

**Comment by eisungy** [comment]
I figured out this. I didn't know how `Mesh2*` is generated from `Mesh*`. So I'm closing this issue now. 
Thank you, @mortezah
