### ISSUE TITLE
update Doxyfile

### ISSUE THREAD

**Issue by ibaned** [SCOREC/core#30]
doxygen seems to say that several variables are deprecated/obsolete

**Comment by mortezah** [comment]
I made one small update to Doxyfile.in. (removed the like adding canDynamicArray.h) 

There seems to be a lot of warnings in regard to the parameters of the methods not being documented. Do we want to fix those as well?

Also, Sqlite3 fails and I don't yet know how to fix that. Any ideas?

**Comment by ibaned** [comment]
Thanks @mortezah !

The warnings about undocumented parameters should, in theory, be worked through, but that will likely take a while. I don't consider that to be encompassed by this issue.

As for sqlite3, I don't recall seeing that failure, but feel free to post the error output here.
