### ISSUE TITLE
MFEM Parallel Pumi Mesh doesn't construct Nodes Gridfunction

### ISSUE THREAD

**Issue by tuckerbabcock** [SCOREC/core#300]
The MFEM class `ParPumiMesh` only constructs the `Nodes` `GridFunction` object for high order meshes:
https://github.com/mfem/mfem/blob/master/mesh/pumi.cpp#L682-L692

What code needs to change to construct the `Nodes` `GridFunction` for a linear mesh as well?

**Comment by mortezah** [comment]
If I recall correctly `ParPumiMesh` is made following the same design characteristics of `ParMesh` in mfem. For `ParMesh` in mfem, nodes are active only for higher orders. See for example here https://github.com/mfem/mfem/blob/dcd2ed5c413695113d0cee8767de2ed9a7df47bd/mesh/mesh.hpp#L168

**Comment by tuckerbabcock** [comment]
Thanks @mortezah. You are correct. There is an MFEM function `Mesh::EnsureNodes` that will create the `Nodes` object for a linear mesh if it is required.
