### ISSUE TITLE
API call help

### ISSUE THREAD

**Issue by tuckerbabcock** [SCOREC/core#301]
Hi,
I'm wondering what API calls to use to find the mesh elements that are classified in a given model region, that are also adjacent to a given model face. 

To illustrate, I'd like to find the dark grey elements shown in the picture. The elements of interest would be classified in the white region, and adjacent to the edges of the rotor. Note that my real problem would be a 3D mesh.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/19217934/79808083-967aa180-8321-11ea-9ee7-857fdaa3c091.png">

Thanks,

Tucker

**Comment by mortezah** [comment]
As far as I know, we don't have reverse classification. For example, you cannot get the list that contains all the mesh faces classified on a given model face. You will need to iterate over all mesh faces and individually check if they are classified on that model. If you will need to create such a list repeatedly, you might want to make that at the beginning of your application once and reuse it (just note that things might get a bit complicated in parallel, depending on your specific problem).

So for your specific case, you will iterate over mesh faces, `f`. Check the classification of the face `f`. If it is on your desired model face, then you can use `r_1 = getUpward(f,0)` and `r_2 = getUpward(f,1)` to get the two mesh regions adjacent to it and then check the classification for `r_1` and `r_2` to see which one is on your desired model entity.

**Comment by tuckerbabcock** [comment]
Hi @mortezah, thanks for the response. I guess I was looking for an `apf` version of `void pumi_gent_getRevClas (pGeomEnt g, std::vector<pMeshEnt>& ents)`, because I thought the reverse classification information was already kept in memory somewhere, but after looking at that function's source (and your comments) I believe I can implement what I'm looking for.

**Comment by jacobmerson** [comment]
If you use a simmetrix mesh under the hood, then you can get what you want using their APIs. Otherwise I have always done as @mortezah says and create my own reverse classification.

**Comment by tuckerbabcock** [comment]
Thanks Jacob and Morteza.
