### ISSUE TITLE
Require C++11 for builds

### ISSUE THREAD

**Issue by jacobmerson** [SCOREC/core#306]
Top level issue to discuss moving to requiring C++11.

Related: 
Pull Request: #305 
Issue: #298 
Branch: https://github.com/SCOREC/core/tree/c++11Required

Potential concerns:
1) We still need to run on hardware which doesn't support a C++11 compiler?
2) XSDK compatibility

Many popular C++ libraries for HPC already make this restriction e.g. Trillinos. Some libraries such as Kokkos are going further and are soon to start requiring C++14 (mentioned on the Kokkos slack).

**Comment by jacobmerson** [comment]
The following is a description of the C++ standards that the Kokkos team is committing to maintaining. I think this might be a reasonable thing to consider adopting for core as well since this implies that all of the major supercomputing centers will support compilers with these language features.

> The next release of Kokkos (3.3) will require C++14 as the minimum C++ standard. The develop branch does so since yesterday. Generally we are trying to move to a schedule of going to a C++standard as the minimum required 4 to 5 years after its ratification. Which means end of CY21 or early CY22 we would move to C++17. Thanks.

**Comment by cwsmith** [comment]
Good find.  Adopting this strategy for core makes sense.

**Comment by cwsmith** [comment]
C++11 is required with #345 .
