### ISSUE TITLE
Undefined reference from SCOREC when building Albany

### ISSUE THREAD

**Issue by ikalash** [SCOREC/core#312]
When we built Albany on top of a Trilinos with SCOREC enabled, we get errors that look like: 

```
[ 74%] Building CXX object src/LandIce/CMakeFiles/LandIce.dir/evaluators/LandIce_HydraulicPotential.cpp.o /home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos/build/install/lib/libapf.so.12.17: undefined reference to `vtable for apf::MixedVectorField'
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos/build/install/lib/libapf.so.12.17: undefined reference to `apf::getNedelec(int)'
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos/build/install/lib/libapf.so.12.17: undefined reference to `apf::getL2Shape(int, int)'
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos/build/install/lib/libapf.so.12.17: undefined reference to `apf::MixedVectorElement::curl(apf::Vector3 const&, apf::Vector3&)'
```
Could you please look into this / get this resolved?  I remember we had a similar problem about a year ago.

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=3314

**Comment by ikalash** [comment]
@RuixiongHu

**Comment by jacobmerson** [comment]
This looks like the stuff that @mortezah and @Samiullah-Malik just added.

**Comment by ikalash** [comment]
I can confirm that the issue has been resolved.  Thanks for doing this so fast!  @RuixiongHu you should be able to use master SCOREC VOTD for your development/runs from now on.
