### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/core#315]
Building develop 492ee54 with GCC 7.4 with `-fsanitize=address` results in several (`ctest`) tests failing.  The log is attached ( [LastTest.log](https://github.com/SCOREC/core/files/4962130/LastTest.log) ) and the errors are summarized below.

```
          6 - bezierRefine (Failed) - leak apf/apfFieldData.cc:265 
         19 - test_matrix_gradient (Failed) - multiple leaks from mds and apf `9919 byte(s) leaked in 59 allocation(s).`
         43 - collapse_2 (Failed) - multiple 'indirect' leaks in mds 
         46 - pipe_condense (Failed) - multiple 'indirect' leaks in mds 
         67 - ptnParma_cube (Failed) - indirect  leaks in model loading
         89 - adapt_fusion (Failed) - a few direct leaks within the adapt call
         93 - chefStream (Failed) - indirect  leaks in model loading
Errors while running CTest
```

**Comment by cwsmith** [comment]
@mortezah Would you please look at the adapt and bezier leaks when you get a chance?

**Comment by mortezah** [comment]
@cwsmith  I don't see any problem with `adapt_fusion`.

**Comment by mortezah** [comment]
@cwsmith  ignore my last comment. I think the the fix for `bezierRefine` also fixed the `adapt_fusion` :)

**Comment by jacobmerson** [comment]
@cwsmith things should be cleared up in PR #317
