### ISSUE TITLE
mfem adaptation example 

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/core#319]
The following instructions were run on the ALCF Cooley machine.

## Software versions

pumi: https://github.com/SCOREC/core/commit/e56f821656ed4e1edc76ef22f9f40ca8091e3756
mfem: https://github.com/mfem/mfem/tree/6222124d456fcf9b1ea217a47791efb5171748d0
simmetrix simmodsuite: 15.0-200714
simmetrix simmodeler: 9.0-200714-dev

## Spack install

using spack yaml files from `/home/cwsmith/atpesc20/cooley-spack`

```
cd ~/.spack
ln -s /home/cwsmith/atpesc20/cooley-spack linux
cd ~/atpesc20
git clone git@github.com:spack/spack.git
git checkout v0.15.3
git checkout -b atpesc20 # we are adding a simmetrix version
source setupSpack.sh
mkdir 15.0-200714
cd !$
../downloadSimModSuite.sh <user> <pass> 15.0-200714 64 no
../getSimModSuiteChecksums.py 15.0-200714 ./15.0-200714/
spack edit simmetrix-simmodsuite # add new version checksum
```

confirm that the constraints are sane

```
spec="mfem+pumi+examples+petsc ^pumi@master+zoltan simmodsuite=full ^zoltan+parmetis"
spack spec -I $spec
```

install - the mfem install will fail when it can't bring in the pumi deps.
 Spack mfem uses makefiles instead of cmake. We could manually add
 the transitive pumi deps to the mfem spack -or- switch the mfem spack package
 to cmake.

```
spack install $spec
```

### setup

```
git clone git@github.com:mfem/mfem.git
cd mfem
#https://github.com/mfem/mfem/tree/atpesc2020_pumi
git checkout aptesc2020_pumi
cd -
mkdir build-mfem-atpesc2020_pumi-cooley
cd !$
```

### env

```
soft add +gcc-8.2.0
soft add +mvapich2-2.2-gcc820

module use ~/atpesc20/spack_mfem_pumi/modules/linux-rhel7-haswell/ 
module load \
  cmake-3.17.3-gcc-8.2.0-zhtc32m \
  metis-5.1.0-gcc-8.2.0-4u4xmdm \
  parmetis-4.0.3-gcc-8.2.0-4wyozqb \
  simmetrix-simmodsuite-15.0-200714-gcc-8.2.0-5hgfryq \
  hypre-2.18.2-gcc-8.2.0-x7z4efo \
  pumi-master-gcc-8.2.0-siohxmx
```

### build

```
hypre=$HYPRE_ROOT
unset HYPRE_ROOT
metis=$METIS_ROOT
unset METIS_ROOT

cmake ../mfem \
-DCMAKE_BUILD_TYPE=Debug \
-DMFEM_USE_MPI=YES \
-DMFEM_USE_METIS_5=YES \
-DMFEM_DEBUG=YES \
-DMFEM_ENABLE_EXAMPLES=YES \
-DMFEM_ENABLE_MINIAPPS=YES \
-DMFEM_USE_PUMI=YES \
-DPUMI_DIR=/home/cwsmith/atpesc20/spack_mfem_pumi/linux-rhel7-haswell/gcc-8.2.0/pumi-master-siohxmxcyclhho4a76x3uljxw63pvsgl/ \
-DHYPRE_DIR=$hypre \
-DMETIS_DIR=$metis \
-DCMAKE_INSTALL_PREFIX=$PWD/install


make -j8
```

# run the adaptive upright case

- mesh adapt (ma) fails in parallel when the values of the adapt ratio are changed

```
mpirun -np 2 ./examples/pumi/pumi_upright_ex2p -p ~/atpesc20/mfem/data/pumi/geom/uprightNoRingGeomSim.smd -bf ~/atpesc20/mfem/data/pumi/geom/upright.def -m ~/atpesc20/mfem/data/pumi/parallel/upright/uprightNoRingGeomSim-2p5kg1/ -v 1 -ar 0.05

MeshAdapt: coarsened 156 edges in 0.040850 seconds
PARMA_STATUS elements balanced in 4 steps to 1.100000 in 0.071378 seconds
Error: Code: 60 String: General error
Error: Code: 60 String: General error
terminate called after throwing an instance of 'SimError*'
terminate called after throwing an instance of 'SimError*'
[cooleylogin2:mpi_rank_0][error_sighandler] Caught error: Aborted (signal 6)
[cooleylogin2:mpi_rank_1][error_sighandler] Caught error: Aborted (signal 6)

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 510697 RUNNING AT cooleylogin2
=   EXIT CODE: 134
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

- ma appears to work OK in serial 

```
./examples/pumi/pumi_upright_ex2p -p ~/atpesc20/mfem/data/pumi/geom/uprightNoRingGeomSim.smd -bf ~/atpesc20/mfem/data/pumi/geom/upright.def -m ~/atpesc20/mfem/data/pumi/serial/uprightNoRingGeomSim-5kg1.smb -v 1 -ar 0.5
```
- the adapt ratio setting needed to get a good mesh are unknown
- attempting to run `gdb` on the core files:
```
ulimit -c unlimited
```
fails with the following error: 
```
gdb: symbol lookup error: gdb: undefined symbol: PyUnicodeUCS4_FromEncodedObject`
```

**Comment by cwsmith** [comment]
@mortezah I'm going to build this up on SCOREC and/or figure out how to get gdb working on Cooley to see where the failure occurs.

**Comment by mortezah** [comment]
@cwsmith you send me the model/mesh?

Is small feature removal (I don't remember what it is called exactly in simmetrix) used while generating the mesh in simmetrix?

**Comment by cwsmith** [comment]
The model and mesh are in the mfem `atpesc2020_pumi` branch in the `data/pumi`directory.

**Comment by mortezah** [comment]
@cwsmith I don't see the model mentioned here https://github.com/mfem/mfem/blob/6222124d456fcf9b1ea217a47791efb5171748d0/examples/pumi/upright_ex2p.cpp#L62 on that branch.

**Comment by cwsmith** [comment]
@morteza This is the modelhttps://github.com/mfem/mfem/blob/atpesc2020_pumi/data/pumi/geom/uprightNoRingGeomSim.smdOn Aug 2, 2020 6:16 PM, Morteza <notifications@github.com> wrote:
@cwsmith I don't see the model mentioned here https://github.com/mfem/mfem/blob/6222124d456fcf9b1ea217a47791efb5171748d0/examples/pumi/upright_ex2p.cpp#L62 on that branch.
