### ISSUE TITLE
Nested calls to PCU_init

### ISSUE THREAD

**Issue by tuckerbabcock** [SCOREC/core#320]
Hi All,

I'm running into an issue where I believe I want to nest calls to `PCU_Comm_Init`, but this obviously gives me an error as it's not allowed. My use case is I have a finite element solver that each load a PUMI mesh. I had been calling `PCU_Comm_Init` before the solver loads the mesh, and calling `PCU_Comm_Free` when the solver is destructed. This worked well enough when I only needed to have one solver instance constructed at once, but if I construct a second solver while the first still exists, I get the nested calls to `PCU_Comm_init`.

I realize a more traditional approach is to place the calls to `PCU_Comm_Init`/`PCU_Comm_Free` in the `main` function of the executable file that runs the analysis. I was hoping to avoid requiring that, since PUMI is an optional dependency of my finite element solver and the mesh file to use is chosen at runtime, I'm hoping users don't have to change their executable file just because they want to use a PUMI mesh. Additionally, I may need each finite element solver to have it's own MPI communicator. As far as I can tell this isn't easily achievable with PCU since it looks like it stores the underlying `MPI_Comm` in a global variable, and doesn't support a concept like a `PCU_Comm`. Is this a correct interpretation of how PCU works?

Do you have suggestions for how to address this? A thought I had was to replace the `state` enum in `pcu.c` and related code with a reference counting style approach, in that `PCU_Comm_Init` would increment a number, `PCU_Comm_Free` would decrement it, and the existing checks for initialized would instead make sure that the number is positive (indicating more calls to `PCU_Comm_Init` than `PCU_Comm_Free`). This approach could potentially work to allow nested calls to `PCU_Comm_Init`, but I don't think it help with using separate communicators for each mesh.

Do you have any suggestions for how to move forward?

Thanks,

Tucker Babcock

**Comment by cwsmith** [comment]
Quick response:

- the state of PCU can be checked with https://github.com/SCOREC/core/blob/8439d928afcb95d88652f4812dcb62077ed958f6/pcu/PCU.h#L103

- the PCU communicator can be switched with https://github.com/SCOREC/core/blob/8439d928afcb95d88652f4812dcb62077ed958f6/pcu/PCU.h#L120

**Comment by tuckerbabcock** [comment]
Hi @cwsmith,

Thanks for the response. Looking at the documentation for `PCU_Switch_Comm` I believe it solves my problem.
