### ISSUE TITLE
conflicting declaration of pMesh between SimPartitionedMesh.h and pumi.h

### ISSUE THREAD

**Issue by eisungy** [SCOREC/core#328]
Hi. This might be already known issue or already resolved. But I couldn't find it in Github issues.

The issue is that when I include both `pumi.h` and `SimPartitionedMesh.h` together, I got below.

```
In file included from output_gkpsp2.h:17,
                 from output_gkpsp2.cc:1:
/home/esyoon/openlib/core-gcc-8.2.0-mpich-3.3/include/pumi.h:65:21: error: conflicting declaration \u2018typedef class apf::Mesh2* pMesh\u2019
 typedef apf::Mesh2* pMesh;
                     ^~~~~
In file included from /opt/simmetrix/simmodsuite/15.0-200811/include/SimPartitionedMesh.h:11,
                 from output_gkpsp2.h:5,
                 from output_gkpsp2.cc:1:
/opt/simmetrix/simmodsuite/15.0-200811/include/MeshTypes.h:28:22: note: previous declaration as \u2018typedef class SMesh* pMesh\u2019
 typedef class SMesh *pMesh;
                      ^~~~~
```

Could you tell me if there is workaround for this problem in user side, please? Thank you =)

**Comment by seegyoung** [comment]
PUMI API is supposed not to be used with Simmetrix. So please do not include them at the same time.

**Comment by eisungy** [comment]
@seegyoung 

Thank you very much for your quick answer. I'm using the routine converting Simmetrix Mesh to Pumi Mesh that needed SimPartitionedMesh.h. In addition, I also need to tag some information on the converted Pumi Mesh and try to utilize PUMI APIs, which results in the conflict.

So far, I was able to avoid the conflict by reading PUMI sources and using the underlying APIs from core. In some sense, it's a kind of copy & paste PUMI source code to avoid the typedef.

**Comment by eisungy** [comment]
This was just a reporting in user side, and wanted to confirm if I'm using PUMI correctly. I'll close this issue. Thank you.

**Comment by jacobmerson** [comment]
Shouldn't all of the PUMI interface be inside of a namespace? At least that way if you are using from C++ you won't have this issue? Adding it is a breaking change, but an easy fix from the client code...they can just use `using namespace pumi` at the top of their files.

Obviously this won't fix the issue if you are using PUMI from C, but I don't see the extern "C" anywhere, so even though it's written like a C interface I'm not sure it's used as one.
