### ISSUE TITLE
Compilation error w/ Apple clang 

### ISSUE THREAD

**Issue by bgranzow** [SCOREC/core#329]
```
/Users/bngranz/codes/scorec/ree/reeResidualFunctionals.cc:714:21: error: variable 'firstFace' is used uninitialized whenever 'for' loop exits because its condition is
      false [-Werror,-Wsometimes-uninitialized]
```

Might want to check the logic in this block
```
713     apf::MeshEntity* firstFace;
714     for (int i = 0; i < up.n; i++) {
715       if ( isOnDomainBoundary(mesh, up.e[i]) ) {
716         firstFace = up.e[i]; break;
717       }
718     }
719     faces.push_back(firstFace);
720     mesh->getUp(firstFace, up);
```

`firstFace` is not guaranteed to be initialized, but is used heavily later on in the code below

**Comment by cwsmith** [comment]
@Samiullah-Malik Would you please take a look at this?

**Comment by jacobmerson** [comment]
@cwsmith Sami graduated...but this error does indicate that our static analysis/compiler flags for our testing may not be adequate. I'm fairly confident that both clang and gcc should catch this with appropriate flags...

**Comment by cwsmith** [comment]
@bgranzow Thanks for reporting the bug.  It should be resolved now.  Please reopen the issue if there are still problems.

**Comment by bgranzow** [comment]
Thanks @cwsmith !
