### ISSUE TITLE
field_io test broken with gcc in release mode

### ISSUE THREAD

**Issue by jacobmerson** [SCOREC/core#360]

**Comment by cwsmith** [comment]
The `field_io` test reads an (1) input mesh, (2) adds a field, (3) writes the mesh with the attached field, (4) reads the mesh, and (5) verifies that the field matches.

Building with `-DCMAKE_BUILD_TYPE=Release` results in failed (5) field verification.
Building with `-DCMAKE_BUILD_TYPE=` results in successful (5) field verification.

After step (3) there are two meshes; one created by the release build (`releaseBuild`), `releaseMesh`, and another from the non-release build (`build`), `mesh`.
Modifying the test to skip steps (1-3) and passing both meshes to both builds produces the following field verification results:

| build/mesh | releaseMesh | mesh |
| --------------- | --------------- | --------------- |
| releasebuild | Fails | Passes |
| build | Passes | Passes |

**Comment by cwsmith** [comment]
The write with the release build appears to be broken and `valgrind` doesn't find any errors.  I'm checking the input to `pcu_write_doubles` now to see if it is getting the expected values.  If it does, then running the sanitizers will be my next step.

**Comment by cwsmith** [comment]
It looks like the result of `pcu_swap_doubles` is different between an release (left) and non-release (right) build.

```
  vtx 2 vec (1, 2, 3)                                             |  vtx 2 vec (1, 2, 3)                                               vtx 3 vec (1, 2, 3)                                             |  vtx 3 vec (1, 2, 3)                                             + +-- 39 lines: vtx 4 vec (1, 2, 3)-------------------------------|+ +-- 39 lines: vtx 4 vec (1, 2, 3)-------------------------------
  p 21 -0.50                                                      |  p 21 -0.50                                                        p 22 -0.50                                                      |  p 22 -0.50                                                        p 23 -0.50                                                      |  p 23 -0.50                                                      
  p 24 23.20                                                      |  p 24 23.20                                                        p 25 58.12                                                      |  p 25 58.12                                                        p 26 38.65                                                      |  p 26 38.65                                                      
  tmp 0 0x0.0e0bf0000e0bfp-1022                                   |  tmp 0 0x0.000000000e0bfp-1022                                     tmp 1 0x1.050400040504p-1019                                    |  tmp 1 0x0.000000040504p-1022                                      tmp 2 0x1.050400040504p-1019                                    |  tmp 2 0x0.000000040504p-1022                                    
  tmp 3 0x1.050400040504p-1019                                    |  tmp 3 0x0.000000040504p-1022                                      tmp 4 0x1.050400040504p-1019                                    |  tmp 4 0x0.000000040504p-1022                                      tmp 5 0x1.050400040504p-1019                                    |  tmp 5 0x0.000000040504p-1022                                    
  tmp 6 0x1.050400040504p-1019                                    |  tmp 6 0x0.000000040504p-1022                                      tmp 7 0x0.0e0bf0000e0bfp-1022                                   |  tmp 7 0x0.000000000e0bfp-1022                                     tmp 8 0x1.050400040504p-1019                                    |  tmp 8 0x0.000000040504p-1022                                    
  tmp 9 0x0.0e0bf0000e0bfp-1022                                   |  tmp 9 0x0.000000000e0bfp-1022                                   
  tmp 10 0x0.0e0bf0000e0bfp-1022                                  |  tmp 10 0x0.000000000e0bfp-1022                                  
  tmp 11 0x1.050400040504p-1019                                   |  tmp 11 0x0.000000040504p-1022                                   
  ```

**Comment by cwsmith** [comment]
This test fails with a release build and passes with a non-release build:

https://github.com/SCOREC/core/commit/e5498e04f9f1f75c880cdc72470c4adc672fc30e

A release build with `-g -fsanitize=undefined` does not produce any additional information (and still fails the test).

**Comment by cwsmith** [comment]
This should be fixed as of [830be9b](https://github.com/SCOREC/core/commit/830be9b64c6eac7287acd392bd5b44441cf0e604).

**Comment by jacobmerson** [comment]
@cwsmith does this mean that anyone who saved a mesh with release build has potentially corrupted data? We may want to put a big note or warning somewhere.

**Comment by cwsmith** [comment]
Yeah, if the older/other compilers optimized in the same way, then there certainly could be broken `smb` meshes in the wild.

Any thoughts on where to put the notice of the bug besides expecting the affected users to find it in this issue?

I'm thinking an `SMB_VERSION` increase to may make sense to aid future debugging of the problem.

https://github.com/SCOREC/core/blob/4dc04098b5ef18cd8a239e2a914c434e9bd6430e/mds/mds_smb.c#L25

**Comment by jacobmerson** [comment]
Not sure but I definitely think incrementing the smb version is a good idea. In the release notes we can put a comment about why the smb version is incremented.
