### ISSUE TITLE
Tags exist that have higher versions than latest released: phasta_4, phasta_5

### ISSUE THREAD

**Issue by yurivict** [SCOREC/core#379]
The latest version is 2.2.7 but these tags have versions 4 and 5.

They are being picked up by automatic new version discovery systems.

Could you please remove them?

**Comment by cwsmith** [comment]
Hi @yurivict,

Thank you for pointing this out.  Which system(s) are picking up the `phasta_#` tags as 'newer' than the `v2.2.7` tag?  Do you know how those systems sort the tags?

**Comment by yurivict** [comment]
FreeBSD.
It removes leading ```[a-zA-Z_]*``` characters and treats the rest as version.

**Comment by cwsmith** [comment]
Thanks for the quick response.  I'll talk with the developer of the downstream app; we should at least be able to rename the `phasta_#` tags.

**Comment by cwsmith** [comment]
@yurivict Sorry for the slow response.  The `phasta_#` tags were replaced with tags named `phasta_0.#`.

**Comment by yurivict** [comment]
Thanks.
