### ISSUE TITLE
create branch for pumi w/ ghosting

### ISSUE THREAD

**Issue by ibaned** [SCOREC/core#38]
Ideally, we should be able to convert SVN commits to Git commits and somehow replay them into the central Git repo, on a branch that separates at the time when the code was copied to Redmine. Then `git merge` ought to be able to apply most of the big changes such as the CMake stuff.

**Comment by ibaned** [comment]
I have tested this, and it should be ready to go once the SVN repository has undergone a few critical bug fixes

**Comment by seegyoung** [comment]
Thanks for all the ground work. I will let you know when it's ready to go.

**Comment by ibaned** [comment]
This issue was just to create the branch (i.e. copy things into Git), so that part is done. pull request #40 will handle the rest.
