### ISSUE TITLE
3 tests fail

### ISSUE THREAD

**Issue by yurivict** [SCOREC/core#410]
[log](https://freebsd.org/~yuri/scorec-core-2.2.8-tests.log)

Version: 2.2.8
clang-16
FreeBSD 14.0 STABLE

**Comment by bobpaw** [comment]
The first two errors seem to be related to to a file open failure. This could be caused by an out of date [pumi-meshes](https://github.com/SCOREC/pumi-meshes) folder or something else. I'm not sure about the third error. Can you run ctest with `--rerun-failed --output-on-failure`?

**Comment by cwsmith** [comment]
@yurivict If possible can you also post the output of `pkg info` from your FreeBSD system?  We are going to setup a VM to try to reproduce and debug the failures.

**Comment by cwsmith** [comment]
Using the LLVM/Clang 18 C++ compiler, develop @24dd23e0, and the following cmake configure line:

```
cmake -S core -B buildPumiOptoffSimoffOmegaoff_freeBsd -DBUILD_SHARED_LIBS=off -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_Fortran_COMPILER=gfortran -DSCOREC_CXX_OPTIMIZE=off -DMDS_ID_TYPE=int -DPCU_COMPRESS=ON -DENABLE_ZOLTAN=OFF -DIS_TESTING=ON  -DCMAKE_INSTALL_PREFIX=buildPumiOptoffSimoffOmegaoff_freeBsd/install
```


all `ctest` tests are passing on our FreeBSD system (`twister`):

```
97/97 Test #97: chef10 ...........................   Passed    2.89 sec

100% tests passed, 0 tests failed out of 97

Label Time Summary:
SMOKE_TEST    =   1.30 sec*proc (2 tests)

Total Test time (real) = 132.31 sec
```

Please reopen this if you are still hitting issues.
