### ISSUE TITLE
malloc.h on OS X

### ISSUE THREAD

**Issue by bgranzow** [SCOREC/core#42]
Compiling at: 5b5c0cb
gives the following error on OS X El Capitan:

[ 34%] Building CXX object pumi/CMakeFiles/pumi.dir/pumi_ghost.cc.o
/Users/bng/core/pumi/pumi_ghost.cc:18:10: fatal error: 'malloc.h' file not found
#include <malloc.h>

This is because malloc.h is nested for some reason in OS X in a directory named malloc, so that the correct syntax becomes: `#include <malloc/malloc.h>`

Probably the best thing to do is  `#include <cstdlib>` instead of `#include<malloc.h>`

I recall PCU did something to circumvent this issue long ago, but it looks like it's since been switched to `#include <stdlib.h>`.

**Comment by bgranzow** [comment]
This issue exists in pumi_mesh.cc as well:
https://github.com/SCOREC/core/blob/master/pumi/pumi_mesh.cc#L22
I was going to submit a patch, but @ibaned  beat me to it 👍 💯 👍

**Comment by ibaned** [comment]
This issue should auto-close when the big giant merge finally gets into the master branch tonight.
