### ISSUE TITLE
fmemopen, open_memstream break OS X compatability

### ISSUE THREAD

**Issue by bgranzow** [SCOREC/core#43]
Compiling at: 532450e
on OS X El Capitan results in warnings of the type:

/Users/bng/core/phasta/phstream.cc:56:13: error: use of undeclared identifier 'fmemopen';
  FILE* f = fmemopen(rs->restart, rs->rSz, "r");

/Users/bng/core/phasta/phstream.cc:63:13: error: use of undeclared identifier 'open_memstream';
  FILE* f = open_memstream(&(rs->restart), &(rs->rSz));

These are probably essential to the phasta file stream stuff, so they still need to exist. The best solution is to probably disable the compilation of these methods if architecture type = OS X.

**Comment by ibaned** [comment]
@cwsmith can you handle this one (or @bgranzow if you want to try) ? Sounds like you just need to throw `#ifdef __APPLE__` around some stuff
