### ISSUE TITLE
Use bob.cmake to set some default cxx flags

### ISSUE THREAD

**Issue by bgranzow** [SCOREC/core#46]
Seems like it would prevent some manual intervention after commits if all developers used the compile flags,  `-Wall -Wextra -Werror` at a minimum. This could easily be accomplished by setting the commands

```
bob_begin_cxx_flags()
bob_end_cxx_flags()
```

somewhere in the top-level CMakeLists.txt. The default flags for Clang compilers in the `bob.cmake` package are a bit too strict, though, and it would take a lot of unneeded effort to get SCOREC/core to compile under those flags. I propose switching the Clang compile flags to `-Wall -Wextra -Werror` locally in cmake/bob.cmake, as well.

Any objections? If not, I'll push this change to develop.

**Comment by ibaned** [comment]
You'll also want to document that setting CMAKE_CXX_FLAGS in config now does nothing, and people need to specify SCOREC_[EXTRA_]CXX_FLAGS to get something in there. I think this is the place to document it:
https://github.com/SCOREC/core/wiki/General-Build-instructions

**Comment by ibaned** [comment]
couple more things:

1. these lines should be removed (https://github.com/SCOREC/core/blob/master/cdash/nightly.cmake#L279)
2. we should consider the C flags as well. for now, setting them equal to the CXX flags after the processing is done should be fine (as long as it happens before we add the C99 flag).

**Comment by bgranzow** [comment]
The initial changes can be seen here:
https://github.com/SCOREC/core/commit/0ccae6116c1402adde0e440bc769d111fb04e309
and the updates to the documentation are in place:
https://github.com/SCOREC/core/wiki/General-Build-instructions

**Comment by ibaned** [comment]
👍 💯

**Comment by bgranzow** [comment]
seems like the nightly tests went well, closing this issue
