### ISSUE TITLE
maQuality.cc [maQuality.h]?

### ISSUE THREAD

**Issue by mortezah** [SCOREC/core#47]
@ibaned, is it ok if I create maQuality.h with the declaration of functions in maQuality.cc?

**Comment by ibaned** [comment]
Thats sounds fine. Note that they are right now declared in `maShape.h`:

https://github.com/SCOREC/core/blob/master/ma/maShape.h#L24

So be sure to remove them from there and include `maQuality.h` in `maShape.h`.

**Comment by mortezah** [comment]
Oh, I did not realize they are defined elsewhere! I will not make any changes for now, and if it turned out that such a change is necessary, I will do it in the future.
