### ISSUE TITLE
Add optional delete argument to apf::makeGlobal

### ISSUE THREAD

**Issue by bgranzow** [SCOREC/core#54]
I would like to modify the function makeGlobal():
https://github.com/SCOREC/core/blob/master/apf/apfNumbering.h#L195

from
GlobalNumbering* makeGlobal(Numbering* n);

to
GlobalNumbering* makeGlobal(Numbering* n, bool delete=true);

where the delete argument specifies whether or not to delete the input Numbering*. The default value of delete=true would retain previous behavior.

Any objections?

**Comment by ibaned** [comment]
sounds fine to me.

**Comment by bgranzow** [comment]
done in : 7528d18fe265df9d5f6950afacf97b878ba06563
