### ISSUE TITLE
error: identifier "Field_def" is undefined

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SCOREC/core#56]
Hi,
I m reopening an issue, as I get the same error using core instead of core-sim:

I m trying to compile the latest version but it fails because of some undefined identifier.
I m using the latest SimModeler library (10.0-161031), with the following components:

components=( gmcore-linux64.tgz aciskrnl-linux64.tgz discrete-linux64.tgz fdcore-linux64.tgz gmabstract-linux64.tgz gmadv-linux64.tgz msadapt-linux64.tgz msadv-linux64.tgz mscore-linux64.tgz msparalleladapt-linux64.tgz msparallelmesh-linux64.tgz pskrnl-linux64.tgz )

Here the error message when compiling the most recent code (latest commit ab1d69505268b0adcf6e01a62624b63e75ebd08b ):

di73yeq2@login22:/gpfs/work/pr63qo/di73yeq2/core/build> ../install_coresim.sh 
-- The CXX compiler identification is Intel 15.0.4.20150805
-- The C compiler identification is Intel 15.0.4.20150805
-- Check for working CXX compiler: /lrz/sys/parallel/mpi.ibm/pecurrent/intel/bin/mpicc
-- Check for working CXX compiler: /lrz/sys/parallel/mpi.ibm/pecurrent/intel/bin/mpicc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working C compiler: /lrz/sys/parallel/mpi.ibm/pecurrent/intel/bin/mpicc
-- Check for working C compiler: /lrz/sys/parallel/mpi.ibm/pecurrent/intel/bin/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- CMAKE_VERSION: 3.4.0
-- SCOREC_VERSION: 2.1.0
-- BUILD_TESTING: OFF
-- BUILD_SHARED_LIBS: OFF
-- CMAKE_INSTALL_PREFIX: /gpfs/work/pr63qo/di73yeq2/core/lib
-- CMAKE_CXX_FLAGS:  -O2 -g -Werror -Wall 
-- Try C99 C flag = [ ]
-- Performing Test C99_FLAG_DETECTED
-- Performing Test C99_FLAG_DETECTED - Failed
-- Try C99 C flag = [-std=gnu99]
-- Performing Test C99_FLAG_DETECTED
-- Performing Test C99_FLAG_DETECTED - Success
-- CMAKE_C_FLAGS = -std=gnu99  -O2 -g -Werror -Wall 
-- IS_TESTING: OFF
-- BUILD_EXES: ON
-- MPIRUN: MPIRUN-NOTFOUND -np
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- ENABLE_SIMMETRIX: ON
-- ENABLE_OMEGA_H: OFF
-- SIM_ARCHOS x64_rhel5_gcc41
-- Found SIMMODSUITE: /gpfs/work/pr63qo/di73yeq2/SimModelerLib/10.0-161031/lib/x64_rhel5_gcc41/libSimPartitionedMesh-mpi.a;/gpfs/work/pr63qo/di73yeq2/SimModelerLib/10.0-161031/lib/x64_rhel5_gcc41/libSimField.a;/gpfs/work/pr63qo/di73yeq2/SimModelerLib/10.0-161031/lib/x64_rhel5_gcc41/libSimAdvMeshing.a;/gpfs/work/pr63qo/di73yeq2/SimModelerLib/10.0-161031/lib/x64_rhel5_gcc41/libSimPartitionedMesh-mpi.a;/gpfs/work/pr63qo/di73yeq2/SimModelerLib/10.0-161031/lib/x64_rhel5_gcc41/libSimMeshing.a;/gpfs/work/pr63qo/di73yeq2/SimModelerLib/10.0-161031/lib/x64_rhel5_gcc41/libSimMeshTools.a;/gpfs/work/pr63qo/di73yeq2/SimModelerLib/10.0-161031/lib/x64_rhel5_gcc41/libSimModel.a;/gpfs/work/pr63qo/di73yeq2/SimModelerLib/10.0-161031/lib/x64_rhel5_gcc41/libSimPartitionWrapper-mpich2.a  
-- PCU_COMPRESS: OFF
-- LION_COMPRESS: OFF
-- MDS_SET_MAX: 256
-- MDS_ID_TYPE: long
-- ENABLE_ZOLTAN: OFF
-- ENABLE_STK: OFF
-- ENABLE_STK_MESH: OFF
-- ENABLE_DSP: OFF
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ENABLE_THREADS

-- Build files have been written to: /gpfs/work/pr63qo/di73yeq2/core/build
Scanning dependencies of target pcu
[  0%] Building C object pcu/CMakeFiles/pcu.dir/pcu.c.o
[  0%] Building C object pcu/CMakeFiles/pcu.dir/pcu_aa.c.o
[  1%] Building C object pcu/CMakeFiles/pcu.dir/pcu_coll.c.o
[  1%] Building C object pcu/CMakeFiles/pcu.dir/pcu_io.c.o
[  1%] Building C object pcu/CMakeFiles/pcu.dir/pcu_buffer.c.o
[  1%] Building C object pcu/CMakeFiles/pcu.dir/pcu_mpi.c.o
[  2%] Building C object pcu/CMakeFiles/pcu.dir/pcu_msg.c.o
[  2%] Building C object pcu/CMakeFiles/pcu.dir/pcu_order.c.o
[  2%] Building C object pcu/CMakeFiles/pcu.dir/pcu_pmpi.c.o
[  2%] Building C object pcu/CMakeFiles/pcu.dir/noto/noto_malloc.c.o
[  2%] Building C object pcu/CMakeFiles/pcu.dir/reel/reel.c.o
[  4%] Linking C static library libpcu.a
[  4%] Built target pcu
Scanning dependencies of target gmi
[  4%] Building C object gmi/CMakeFiles/gmi.dir/gmi.c.o
[  4%] Building C object gmi/CMakeFiles/gmi.dir/agm.c.o
[  5%] Building C object gmi/CMakeFiles/gmi.dir/gmi_base.c.o
[  5%] Building C object gmi/CMakeFiles/gmi.dir/gmi_file.c.o
[  5%] Building C object gmi/CMakeFiles/gmi.dir/gmi_lookup.c.o
[  5%] Building C object gmi/CMakeFiles/gmi.dir/gmi_mesh.c.o
[  6%] Building C object gmi/CMakeFiles/gmi.dir/gmi_null.c.o
[  6%] Building C object gmi/CMakeFiles/gmi.dir/gmi_analytic.c.o
[  6%] Linking C static library libgmi.a
[  6%] Built target gmi
Scanning dependencies of target gmi_sim
[  6%] Building CXX object gmi_sim/CMakeFiles/gmi_sim.dir/gmi_sim.cc.o
[  8%] Linking CXX static library libgmi_sim.a
[  8%] Built target gmi_sim
Scanning dependencies of target mth
[  8%] Building CXX object mth/CMakeFiles/mth.dir/mthQR.cc.o
[  9%] Linking CXX static library libmth.a
[  9%] Built target mth
Scanning dependencies of target lion
[  9%] Building CXX object lion/CMakeFiles/lion.dir/lionBase64.cc.o
[  9%] Building CXX object lion/CMakeFiles/lion.dir/lionNoZLib.cc.o
[ 10%] Linking CXX static library liblion.a
[ 10%] Built target lion
Scanning dependencies of target apf
[ 10%] Building CXX object apf/CMakeFiles/apf.dir/apf.cc.o
[ 10%] Building CXX object apf/CMakeFiles/apf.dir/apfCavityOp.cc.o
[ 12%] Building CXX object apf/CMakeFiles/apf.dir/apfElement.cc.o
[ 12%] Building CXX object apf/CMakeFiles/apf.dir/apfField.cc.o
[ 12%] Building CXX object apf/CMakeFiles/apf.dir/apfFieldOf.cc.o
[ 12%] Building CXX object apf/CMakeFiles/apf.dir/apfGradientByVolume.cc.o
[ 13%] Building CXX object apf/CMakeFiles/apf.dir/apfIntegrate.cc.o
[ 13%] Building CXX object apf/CMakeFiles/apf.dir/apfMatrix.cc.o
[ 13%] Building CXX object apf/CMakeFiles/apf.dir/apfDynamicMatrix.cc.o
[ 13%] Building CXX object apf/CMakeFiles/apf.dir/apfDynamicVector.cc.o
[ 14%] Building CXX object apf/CMakeFiles/apf.dir/apfMatrixField.cc.o
[ 14%] Building CXX object apf/CMakeFiles/apf.dir/apfMesh.cc.o
[ 14%] Building CXX object apf/CMakeFiles/apf.dir/apfMesh2.cc.o
[ 14%] Building CXX object apf/CMakeFiles/apf.dir/apfMigrate.cc.o
[ 14%] Building CXX object apf/CMakeFiles/apf.dir/apfScalarElement.cc.o
[ 16%] Building CXX object apf/CMakeFiles/apf.dir/apfScalarField.cc.o
[ 16%] Building CXX object apf/CMakeFiles/apf.dir/apfShape.cc.o
[ 16%] Building CXX object apf/CMakeFiles/apf.dir/apfIPShape.cc.o
[ 16%] Building CXX object apf/CMakeFiles/apf.dir/apfHierarchic.cc.o
[ 17%] Building CXX object apf/CMakeFiles/apf.dir/apfVector.cc.o
[ 17%] Building CXX object apf/CMakeFiles/apf.dir/apfVectorElement.cc.o
[ 17%] Building CXX object apf/CMakeFiles/apf.dir/apfVectorField.cc.o
[ 17%] Building CXX object apf/CMakeFiles/apf.dir/apfPackedField.cc.o
[ 18%] Building CXX object apf/CMakeFiles/apf.dir/apfNumbering.cc.o
[ 18%] Building CXX object apf/CMakeFiles/apf.dir/apfMixedNumbering.cc.o
[ 18%] Building CXX object apf/CMakeFiles/apf.dir/apfAdjReorder.cc.o
[ 18%] Building CXX object apf/CMakeFiles/apf.dir/apfVtk.cc.o
[ 20%] Building CXX object apf/CMakeFiles/apf.dir/apfFieldData.cc.o
[ 20%] Building CXX object apf/CMakeFiles/apf.dir/apfTagData.cc.o
[ 20%] Building CXX object apf/CMakeFiles/apf.dir/apfCoordData.cc.o
[ 20%] Building CXX object apf/CMakeFiles/apf.dir/apfArrayData.cc.o
[ 21%] Building CXX object apf/CMakeFiles/apf.dir/apfUserData.cc.o
[ 21%] Building CXX object apf/CMakeFiles/apf.dir/apfPartition.cc.o
[ 21%] Building CXX object apf/CMakeFiles/apf.dir/apfConvert.cc.o
[ 21%] Building CXX object apf/CMakeFiles/apf.dir/apfConstruct.cc.o
[ 21%] Building CXX object apf/CMakeFiles/apf.dir/apfVerify.cc.o
[ 22%] Building CXX object apf/CMakeFiles/apf.dir/apfGeometry.cc.o
[ 22%] Building CXX object apf/CMakeFiles/apf.dir/apfBoundaryToElementXi.cc.o
[ 22%] Building CXX object apf/CMakeFiles/apf.dir/apfFile.cc.o
[ 22%] Linking CXX static library libapf.a
[ 22%] Built target apf
Scanning dependencies of target apf_sim
[ 24%] Building CXX object apf_sim/CMakeFiles/apf_sim.dir/apfSIM.cc.o
/gpfs/work/pr63qo/di73yeq2/core/apf_sim/apfSIM.cc(32): error: identifier "Field_def" is undefined
    pPolyField pf = static_cast<pPolyField>(Field_def(fd));
                                            ^

/gpfs/work/pr63qo/di73yeq2/core/apf_sim/apfSIMDataOf.h(21): error: identifier "Field_def" is undefined
      pf = static_cast<pPolyField>(Field_def(fd));
                                   ^

compilation aborted for /gpfs/work/pr63qo/di73yeq2/core/apf_sim/apfSIM.cc (code 2)
make[2]: *** [apf_sim/CMakeFiles/apf_sim.dir/apfSIM.cc.o] Error 2
make[1]: *** [apf_sim/CMakeFiles/apf_sim.dir/all] Error 2
make: *** [all] Error 2
[  4%] Built target pcu
[  6%] Built target gmi
[  8%] Built target gmi_sim
[  9%] Built target mth
[ 10%] Built target lion
[ 22%] Built target apf
[ 24%] Building CXX object apf_sim/CMakeFiles/apf_sim.dir/apfSIM.cc.o
/gpfs/work/pr63qo/di73yeq2/core/apf_sim/apfSIM.cc(32): error: identifier "Field_def" is undefined
    pPolyField pf = static_cast<pPolyField>(Field_def(fd));
                                            ^

/gpfs/work/pr63qo/di73yeq2/core/apf_sim/apfSIMDataOf.h(21): error: identifier "Field_def" is undefined
      pf = static_cast<pPolyField>(Field_def(fd));
                                   ^

compilation aborted for /gpfs/work/pr63qo/di73yeq2/core/apf_sim/apfSIM.cc (code 2)
make[2]: *** [apf_sim/CMakeFiles/apf_sim.dir/apfSIM.cc.o] Error 2
make[1]: *** [apf_sim/CMakeFiles/apf_sim.dir/all] Error 2
make: *** [all] Error 2

here is my install script:

di73yeq2@login22:/gpfs/work/pr63qo/di73yeq2/core/build> cat ../install_coresim.sh 
cmake .. \
  -DSIM_MPI=mpich2 \
  -DCMAKE_C_COMPILER="`which mpicc`" \
  -DCMAKE_CXX_COMPILER="`which mpicc`" \
  -DCMAKE_C_FLAGS="-O2 -g -Wall" \
  -DCMAKE_CXX_FLAGS="-O2 -g -Wall" \
  -DMDS_ID_TYPE=long \
  -DENABLE_THREADS:BOOL=OFF \
  -DSIMMETRIX_LIB_DIR="/gpfs/work/pr63qo/di73yeq2/SimModelerLib/10.0-161031/lib/x64_rhel5_gcc41/" \
  -DSIMMODSUITE_INCLUDE_DIR="/gpfs/work/pr63qo/di73yeq2/SimModelerLib/10.0-161031/include" \
  -DENABLE_ZOLTAN=OFF \
  -DCMAKE_INSTALL_PREFIX="/gpfs/work/pr63qo/di73yeq2/core/lib"\
  -DENABLE_SIMMETRIX:BOOL=ON

make
make install

Thanks for helping,

Thomas Ulrich

**Comment by cwsmith** [comment]
`core` relies on APIs from Simmetrix's SimModSuite only provided by version 11 (or newer).  Please contact Simmetrix support and ask for a 11.0-160922 or newer build of SimModSuite.

**Comment by Thomas-Ulrich** [comment]
I see, thank you for the answer.

**Comment by Thomas-Ulrich** [comment]
For information, it seems that:
git revert fd190e37af17123bdd7e4fdcff3372d89c442a04
allows compiling core with SimModeler 10.0-161031

**Comment by cwsmith** [comment]
Yeah.  That commit adds support for additional field interpolation functionality.

The build wiki was updated to describe the dependency:
https://github.com/SCOREC/core/wiki/General-Build-instructions#Install_dependencies
