### ISSUE TITLE
Phasta restart has required dependence on apf_sim

### ISSUE THREAD

**Issue by bgranzow** [SCOREC/core#57]
phRestart.cc has a required dependence on the apf_sim package by including apfSim.h.  This can be seen here:

https://github.com/SCOREC/core/blob/master/phasta/phRestart.cc#L13

This breaks the SCOREC/core build when ENABLE_SIMMETRIX is set to OFF. It looks like the correct thing to do would be to place the phRestart.cc source file under this if statement in the phasta/CMakeLists.txt file:

https://github.com/SCOREC/core/blob/master/phasta/CMakeLists.txt#L25

I would like SCOREC developers to be conscious that many users of SCOREC/core do not build with the Simmetrix tools enabled.

**Comment by ibaned** [comment]
Just discovered this as well, have an unpushed fix. Updates coming up.

**Comment by bgranzow** [comment]
Yea the issue is more subtle than I thought, but I just wrote a patch... I was going to try to attach it here, but I can't figure out how

**Comment by bgranzow** [comment]
Well, you did exactly what I did, so that's neat

**Comment by ibaned** [comment]
We're either both wrong or both right :)
