### ISSUE TITLE
move writeGeomBCFiles logic to phasta-chef adaptive loop driver(s)

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/core#62]
see 
https://github.com/SCOREC/core/commit/4897c4b2e064ed669a0d16e7e5c1f59c09686961#commitcomment-20026660

**Comment by yangf4** [comment]
closed

**Comment by cwsmith** [comment]
Was there a commit for this?

**Comment by yangf4** [comment]
Here it is:
https://github.com/SCOREC/core/commit/a193f80689be77b4a18c61460b3552365fda9c36

**Comment by cwsmith** [comment]
OK.  Thank you.
