### ISSUE TITLE
Tutorial 

### ISSUE THREAD

**Issue by vikramsg** [SCOREC/core#67]
Hi,

I wanted to develop a Discontinuous Galerkin code using PUMI. I built PUMI but I was hoping there was some tutorial to walk through the initial process including mesh files. Is there such a tutorial?

Thanks,
Vikram

**Comment by mortezah** [comment]
@vikramsg, here is an informal introduction http://scorec.rpi.edu/~dibanez/crean_intro.pdf.
Also, the API documentation is here http://www.scorec.rpi.edu/~seol/scorec/doxygen/

**Comment by bgranzow** [comment]
Hi Vikram,

I have written several continuous Galerkin mini-applications using PETSc and PUMI that are quite small in scope, and may serve as an introductory example to writing FEM codes with PUMI.

https://github.com/bgranzow/pe
https://github.com/bgranzow/vms

A fork to the first repository added some additional capabilities in terms of boundary conditions:

https://github.com/FrancescoCasalegno/pe

I do not have any experience with Discontinuous Galerkin finite element methods. It may be likely that you would like to implement your own shape functions for your analyses. This can be achieved through the APF interface seen here:

https://github.com/SCOREC/core/blob/master/apf/apfShape.h#L73

Cheers,
Brian

**Comment by vikramsg** [comment]
Hi Brian,

Thanks for that. I wanted to get something that would guide me through the initial process and your code seems just the right thing. 

Thanks also for pointing out where I would need to change the shape function.
