### ISSUE TITLE
check_ent

### ISSUE THREAD

**Issue by seegyoung** [SCOREC/core#81]
During the profiling of a routine that calls getAdjacent heavily, we found that substantial percentage of time is spent on "check_ent". Let me know if you object putting "check_ent" and all other sanity check such as "assert" inside #ifdef DEBUG-#endif. Or suggest any better way to do sanity check selectively. See sample of our profile result.

```
Flat profile:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls  ms/call  ms/call  name    
 25.00      0.05     0.05                             xgc_mesh_search_(int*, double*, int*, double*, int*)
 10.00      0.07     0.02  2761972     0.00     0.00  check_ent
 10.00      0.09     0.02   375939     0.00     0.00  apf::MeshMDS::getUp(apf::MeshEntity*, apf::Up&)
  5.00      0.10     0.01  5143796     0.00     0.00  mds_type
  5.00      0.11     0.01  1884781     0.00     0.00  apf::MeshMDS::getDownward(apf::MeshEntity*, int, apf::MeshEntity**)
  5.00      0.12     0.01  1065899     0.00     0.00  skip
  5.00      0.13     0.01   376231     0.00     0.00  apf::MeshMDS::getRemotes(apf::MeshEntity*, std::map<int, apf::MeshEntity*, std::less<int>, std::allocator<std::pair<int const, apf::MeshEntity*> > >&)
  5.00      0.14     0.01   375939     0.00     0.00  apf::MeshMDS::getPoint_(apf::MeshEntity*, int, apf::Vector3&)
  5.00      0.15     0.01   188115     0.00     0.00  apf::getDimension(apf::Mesh*, apf::MeshEntity*)
  5.00      0.16     0.01       74     0.14     0.14  pcu_swap_unsigneds
  5.00      0.17     0.01        1    10.00    10.95  read_conn
  5.00      0.18     0.01                             apf::getBridgeAdjacent(apf::Mesh*, apf::MeshEntity*, int, int, apf::DynamicArray<apf::MeshEntity*>&)
  5.00      0.19     0.01                             mds_destroy
  2.50      0.20     0.01  2010094     0.00     0.00  apf::MeshMDS::getType(apf::MeshEntity*)
```

**Comment by cwsmith** [comment]
Passing `-DNDEBUG` to the compiler should skip many `assert(...)` calls and may improve performance a bit.  I'm not sure if it's possible to place these `check_ent(...)` calls in `assert(...)` statements, but that would be an interesting option.

If wrapping the calls in `assert(...)` won't work then using a `SCOREC_FAST` (or something like that) cmake option would be a good second choice.  This option should be `OFF` by default so users get all the safety checks unless the explicitly ask the performance trade-off.

**Comment by seegyoung** [comment]
With -DNDEBUG, the code doesn't compile as it complains about many "unused variables". 
I will proceed with altering the code so we can compile the code with -DNDEBUG.

**Comment by cwsmith** [comment]
The code does not need to be altered.  Pass -DSCOREC_CXX_WARNINGS=OFF to silence those unused variable errors when using -DNDEBUG.

**Comment by cwsmith** [comment]
On second thought... we should fix the warnings (```(void)foo;``` should do the trick [as done here](https://github.com/SCOREC/core/blob/5198f7de40b78bc96a79f688d7b2aaae61c614a6/lion/lionNoZLib.cc#L9-L15)) found when compiled with -DNDEBUG, but it is not critical.

An issue for the warning fix is here: #86

**Comment by seegyoung** [comment]
Does it sound ok to make -DENABLE_CHECK controls how we do configuration?
So if ENABLE_CHECK=OFF, -DNDEBUG is turned on and SCOREC_CXX_WARNINGS will be set to OFF automatically.

The addition to the CMakeLists.txt will be like this:
==
option(${PROJECT_NAME}_CXX_WARNINGS "Compile C++ with warnings" ON)
option(ENABLE_CHECK "Do sanity check with core data including entity" ON)
if(ENABLE_CHECK)
  add_definitions(-DDEBUG)
else()
  add_definitions(-DNDEBUG)
  set (${PROJECT_NAME}_CXX_WARNINGS "OFF")
endif()
==

**Comment by seegyoung** [comment]
Sorry about the big fonts above. copy and paste screwed it up.

**Comment by cwsmith** [comment]
no worries.  '===' is a heading in markdown; i replaced them with three backticks '```'

**Comment by cwsmith** [comment]
I'd prefer not to add more compilation options/flags, especially if we will soon(?) fix the underlying warning issue.

**Comment by seegyoung** [comment]
That sounds fair - check_ent will be embedded with #ifndef NDEBUG.

**Comment by cwsmith** [comment]
Can you elaborate on what you mean by `#ifndef NDEBUG` and/or provide an example?  I'm not sure I follow.

**Comment by ibaned** [comment]
Pieces of code that are only needed as part of an `assert()` call need to be disabled with the same mechanism that disables `assert()`:
```
{
#ifndef NDEBUG
  int checksum = parma_checksum(mesh);
#endif
  //code that always needs to run
  assert(checksum);
}
```

**Comment by bgranzow** [comment]
There's quite a few examples like this:

```
{
  int nv = m->getDownward(edges[j], 0, verts);
  assert(nv==2);
}
```
where `nv` is not used when `NDEBUG=ON`, but the function that returns this unused variable is doing useful stuff, making this a bad idea:
```
{
#ifndef NDEBUG
  int nv = m->getDownward(edges[j], 0, verts);
#endif
  assert(nv==2);
}
```
The best I can come up with is:
```
{
  int nv = m->getDownward(edges[j], 0, verts);
  assert(nv==2);
  (void)nv
}
```
which I think should be OK since variables like this are entirely local in scope

**Comment by ibaned** [comment]
@seegyoung maybe you should manually remove check_ent and see what the percentage change is in total runtime of the particle tracking benchmark ? If its not a huge benefit, maybe its not worth going through all of SCOREC/core and removing all the asserts.

**Comment by seegyoung** [comment]
I modified check_ent in mds.c to have only "assert" statements so it will do nothing if CMAKE_BUILD_TYPE=Release. It's consistent with check_ent in agm.c. I will close this issue. Thanks for all your input.

**Comment by cwsmith** [comment]
for reference 531682cf44c21005cc6a8b558add57bb76548298

**Comment by ibaned** [comment]
Well now its fast when `NDEBUG` is defined but it might be slower in the other case (the TYPE and INDEX calculations are now repeated). You should do some timing to make sure it didn't get significantly slow.

**Comment by bgranzow** [comment]
I should be a few minutes away from fixing this with #86

**Comment by bgranzow** [comment]
Done in 871a190

Please reference [this](https://github.com/SCOREC/core/issues/86#issuecomment-285095134) comment for details.

**Comment by seegyoung** [comment]
using test/pumi.cc, 4 proc, 24K 2D mesh in scorec linux,
- 531682c: Debug 1.06 sec, Release 0.91 sec
- 871a190: Debug 1.07 sec, Release 1.04 sec

Any input or thought?

**Comment by cwsmith** [comment]
probably need a test that runs longer / has a bigger mesh

**Comment by seegyoung** [comment]
I suggest to revert 871a190 until we confirm that it doesn't cause overhead. We cannot compete with the slower code.

**Comment by cwsmith** [comment]
In the run that produced the gprof output how many elements per-part were there?

**Comment by ibaned** [comment]
1. You do not revert things before you know they cause problems, you revert things *after* you know they cause problems. It is trivial to test the commit prior to that one.

2. 871a190 cannot possibly make anything slower. All it does is disable code.

3. `test/pumi.cc` is not what you want to be running. run whatever benchmark you used to get the `gprof` data.

4. `gprof` is not a good profiler, because it adds code to the beginning and end of each function. This adds a constant overhead to each function, which means it skews the relative timings of functions. Very small functions (e.g. `check_ent`) will look like they take much more time than they actually do. Use a sampling profiler like `perf`, which is not biased. My guess is `check_ent` actually doesn't take any significant runtime, which is why I recommended the simple test of commenting it out and measuring total runtime of the particle tracking benchmark.

**Comment by seegyoung** [comment]
test/pumi.cc has huge demand on adjacency queries due to repeated ghosting. The performance with adjacency queries is critical in PIC computation.

 Agree that 871a190 cannot possibly make anything slower however, with the last commit with PCU_ALWAYS_ASSERT, I see the slow-down with my test case which I cannot accept for fusion development. I will work on a branch for fusion development.

**Comment by bgranzow** [comment]
https://github.com/SCOREC/core/issues/81#issuecomment-285140480
This is just my opinion, but I don't really think that's a long-term sustainable solution. If the code truly is slower now than it was before, then this is not just an issue for you, but for all users of the code-base. That is why it is important to have (meaningful) data that corroborates this claim.

I would like to see `perf` output from a meaningful (not pumi.cc) benchmark test case using:
(1) The current develop HEAD compiled without modifying the default CXX flags (-O2 -g)
(2) The SHA fc42307 compiled without modifying the default CXX flags
(3) The SHA 531682c compiled without modifying the default CXX flags

Furthermore, it sounds like you are building with CMAKE_BUILD_TYPE=Release
This ends up passing conflicting information in terms of compiler flags. You can easily verify this yourself by building with `make VERBOSE=1`. I am looking into this. I will open a separate issue if it turns out to need it.

**Comment by bgranzow** [comment]
Running [this](https://github.com/SCOREC/core/blob/develop/test/assert_timing.cc) executable three times consecutively to test timings for c `assert` and for `PCU_ALWAYS_ASSERT` yields the following results on jenga when core is compiled with `SCOREC_CXX_FLAGS=-O3 -Wall -Wextra`

```
granzb@jenga:/lore/granzb/core/build/test$ ./assert_timing 0
c assert in 12.196935 seconds
c assert in 12.243357 seconds
c assert in 12.194879 seconds
c assert in 12.202749 seconds
c assert in 12.218542 seconds
granzb@jenga:/lore/granzb/core/build/test$ ./assert_timing 1
pcu assert in 12.127429 seconds
pcu assert in 12.121092 seconds
pcu assert in 12.121313 seconds
pcu assert in 12.119352 seconds
pcu assert in 12.114894 seconds
granzb@jenga:/lore/granzb/core/build/test$ ./assert_timing 0
c assert in 12.192294 seconds
c assert in 12.163935 seconds
c assert in 12.165538 seconds
c assert in 12.173873 seconds
c assert in 12.173478 seconds
granzb@jenga:/lore/granzb/core/build/test$ ./assert_timing 1
pcu assert in 12.119284 seconds
pcu assert in 12.106641 seconds
pcu assert in 12.108695 seconds
pcu assert in 12.127692 seconds
pcu assert in 12.118656 seconds
granzb@jenga:/lore/granzb/core/build/test$ ./assert_timing 0
c assert in 12.154912 seconds
c assert in 12.176955 seconds
c assert in 12.174755 seconds
c assert in 12.196451 seconds
c assert in 12.169984 seconds
granzb@jenga:/lore/granzb/core/build/test$ ./assert_timing 1
pcu assert in 12.103965 seconds
pcu assert in 12.098752 seconds
pcu assert in 12.090134 seconds
pcu assert in 12.099428 seconds
pcu assert in 12.090594 seconds
```

Averaging over the totality of the `c assert` run times and the `PCU_ALWAYS_ASSERT` run times indicates that *for this particular set of runs* `PCU_ALWAYS_ASSERT` is on average 0.6% faster than c `assert`. Obviously, you want to be careful what conclusions you draw from this, but this does provide an initial sanity check that `PCU_ALWAYS_ASSERT` isn't doing anything too horrible.

I can't really emphasize how useful it will be to have good profiling results for a benchmark problem that mimics (or is exactly) a problem you are interested in solving, that way we can see where (if any) large benefits will arise by disabling assert code with `-DNDEBUG`. The new PCU assert macros should give us a way to disable those specific code portions with fine granularity.
