### ISSUE TITLE
loading curved meshes

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/core#83]
When a curved mesh is loaded it appears that the data defining the mid-side nodes is ignored.

The `describe` tool lists the 'coordinates_edg' tag but when `render` is ran no mid-side nodes are present in the resulting `vtu` files.

Attached is a 2D quad mesh and its associated model.  Note, the names are 'reorder' as these meshes were previously used in assignment two of the Finite Element Programming class.

When we load the attached quad mesh, add a call to `apf::changeMeshShape(m,apf::getLagrange(2),true);` and then call `apf::writeVtkFiles(argv[3], m);` then we see the mid-side nodes in paraview.  If the mesh is written to a '.smb' and `render` ran on it the resulting '.vtu' file does not have mid-side nodes.

I propose we add a test (in SCOREC/core/test) that simply loads a curved mesh and `assert(...)` that it is curved.

```
+cwsmith@pachisi: $ describe reorder_a.dmg reorder_a.smb
malloc used before: min 6698608.000000 max 6698608.000000 avg 6698608.000000 imb 1.000000
model reorder_a.dmg loaded in 0.000699 seconds
mesh reorder_a.smb loaded in 0.000781 seconds
number of triangle 0 quad 36
mesh entity counts: v 49 e 84 f 36 r 0
kernel heap: min 2211840.000000 max 2211840.000000 avg 2211840.000000 imb 1.000000
malloc used: min 6719296.000000 max 6719296.000000 avg 6719296.000000 imb 1.000000
PARMA_STATUS  disconnected <max avg> 0 0.000
PARMA_STATUS  neighbors <max avg> 0 0.000
PARMA_STATUS  smallest side of max neighbor part 49
PARMA_STATUS  num parts with max neighbors 1
PARMA_STATUS  empty parts 0
PARMA_STATUS  small neighbor counts 1:0 2:0 3:0 4:0 5:0 6:0 7:0 8:0 9:0 10:0
PARMA_STATUS  weighted vtx <tot max min avg> 49.0 49.0 49.0 49.000
PARMA_STATUS  weighted edge <tot max min avg> 84.0 84.0 84.0 84.000
PARMA_STATUS  weighted face <tot max min avg> 36.0 36.0 36.0 36.000
PARMA_STATUS  owned bdry vtx <tot max min avg> 0 0 0 0.000
PARMA_STATUS  shared bdry vtx <tot max min avg> 0 0 0 0.000
PARMA_STATUS  model bdry vtx <tot max min avg> 24 24 24 24.000
PARMA_STATUS  sharedSidesToElements <max min avg> 0.000 0.000 0.000
PARMA_STATUS  entity imbalance <v e f r>: 1.00 1.00 1.00 1.00
tag: "coordinates_ver"
tag: "coordinates_edg"
```

[reorder.tar.gz](https://github.com/SCOREC/core/files/804783/reorder.tar.gz)

**Comment by mortezah** [comment]
The .smb mesh in this folder does not seem to be quadratic.

The .sms mesh in issue #82 when converted to .smb with the fixed convert tool loads fine with the render tool.

**Comment by cwsmith** [comment]
How are the quadratic nodes stored(written) in an mds(.smb) mesh?  The example 'reorder' .smb has the `coordinates_edg` tag. Is that no longer used to store the nodes (assuming that is how it was done before)?

**Comment by mortezah** [comment]
@cwsmith you are correct, reorder_a0.smb has those tags and so must be second-order, but somehow it seems to be different from the new (which load fine with render) meshes that I make (one obvious difference is the size). Any idea when that mesh was created? Maybe something can be done by comparing the state of the current code and the code at the time when that mesh was created.

**Comment by cwsmith** [comment]
The mesh was uploaded to fep on Feb 16, 2015.  So... going on a bit of a dig here

```
$ git log --since 2015-02-14 --before 2015-02-16
commit 9896ea8c1df034c355647740ae719210d6aa3f0e
Author: Dan Ibanez <dan.a.ibanez@gmail.com>
Date:   Mon Feb 16 20:49:44 2015 -0500

    hacking in support for quadratic quadrilaterals

    theres a few things wrong with this commit.
    first, the quadratic is returned from
    getLagrange(2), but since whats really
    coded is just mid-edge nodes, then these
    are really Serendipity shapes, not
    Lagrange.
    this is just a placeholder to get students
    through an assignment involving meshes
    with mid-edge nodes.
...
```

**Comment by ibaned** [comment]
I think what is going on is that that old mesh file was created prior to the implementation of storing true shape information in SMB and automatically reconstructing fields from this information. Although SMB is properly versioned and the version number uniquely defined what features the file supports, there is little visibility into this version or the associated features.

If you really need to revive that particular mesh, the thing to do is to call this after loading it:
```cpp
apf::changeMeshShape(mesh, apf::getSerendipity(), /*project=*/ false);
```
then writing it out again will write it in the new format which should auto-load the right fields.

In the long run, it may be useful for `describe` to be able to print the SMB version number, and to document the features introduced at each version number.

**Comment by ibaned** [comment]
In particular, commit e93d83b increments SMB to version 5, the difference being support for proper shape information storage and automatic APF field loading.

**Comment by mortezah** [comment]
Two tests were added in regards to this issue.

The first uses the convert tool to convert simmetrix 2D triangular and quadrilateral meshes to scorec meshes. 
The second uses verify_2nd_order_shapes to verify that the entity shapes are written properly in the scorec meshes.
