### ISSUE TITLE
Issue running "zbalance.cc"

### ISSUE THREAD

**Issue by KazemKamran** [SCOREC/core#87]
I notice that **zbalance.cc** does not work with **.null** or **.smd** models. 
It works with **.dmg** models. For the **.null** model I understand that it is not working because there is no **gmi_register_null()**. 

My question is does the **zoltan** and **balancer** need a model to work? I am asking because I try to **loadMdsMesh** with a **null** model but still have errors with 

  _apf::Balancer* balancer = makeZoltanBalancer(m, apf::GRAPH, apf::REPARTITION);
  balancer->balance(weights, 1.10);_

**Comment by cwsmith** [comment]
This should be fixed but you'll also need a model for running most tools.  See this page on discrete model creation:
https://github.com/SCOREC/core/wiki/Geometric-Models#discrete-models

**Comment by bgranzow** [comment]
@KazemKamran Is this issue resolved ?

**Comment by KazemKamran** [comment]
I am not sure, I think it makes sense to expect balancer works with null model or at least an smd  model.

**Comment by cwsmith** [comment]
did you try creating the `.dmg` model as described above?

**Comment by KazemKamran** [comment]
It works with `.dmg` no doubt. What happen when I have a real model? do I have to make always a `.dmg`?

**Comment by KazemKamran** [comment]
@mortezah FYI this is how to make a `.dmg` model

**Comment by cwsmith** [comment]
https://github.com/SCOREC/core/commit/7e7324dc7de1f1d5ec93a8a0493b893aa6cbcb52 adds support for GeomSim and null models.
