### ISSUE TITLE
Storage of Gmsh Physical Tags

### ISSUE THREAD

**Issue by zhang-alvin** [SCOREC/core#94]
Currently, mds cannot read partitioned gmsh meshes or the associated physical tags/classification of mesh entities. The required information is discarded in the following lines:
https://github.com/SCOREC/core/blob/8c462070cc75172b931cef0ee08079762b01babe/mds/mdsGmsh.cc#L140
 https://github.com/SCOREC/core/blob/8c462070cc75172b931cef0ee08079762b01babe/mds/mdsGmsh.cc#L143

To simplify the workflow in the [Proteus toolkit,](http://proteustoolkit.org/) I would like to add these two capabilities. I made a first attempt at addressing the storage of the physical tags by creating a MeshTag* over the mesh: 

https://github.com/zhang-alvin/core/commit/ebc3784dfb5e7af5893217c67c66f4458fd1caa6 

I'd like to know
1) if these features are desired (ultimately) in the master branch.
2) if there are any pitfalls to the MeshTag approach to storing the physical tags.

**Comment by bgranzow** [comment]
I can't speak to item 2. but I would certainly be interested in what seems to be your ultimate goal (converting partitioned gmsh meshes to mds meshes), so I support item 1.

**Comment by bgranzow** [comment]
Let's split this into two issues: Parallel Gmsh readers and storage of physical tags. This issue will remain the physical tags issue.

**Comment by zhang-alvin** [comment]
This feature is no longer necessary for me. Closing for now.
