### ISSUE TITLE
Parallel Gmsh Reader

### ISSUE THREAD

**Issue by bgranzow** [SCOREC/core#95]
@zhang-alvin reports that it would be useful to have the ability to convert from partitioned Gmsh files to an mds mesh.

Apparently, partitioned Gmsh files are simply exactly the same as a serial Gmsh file, with additional information tagged to each element describing which partition it belongs to. While it may be convenient to read in and partition meshes based this information, it's important to note that this is in no way scalable.

**Comment by zhang-alvin** [comment]
In the application that I am interested in (Proteus), scalability would only be an issue during the initialization stage of a simulation. After loading in the mesh and performing mesh adaptation, there will not be a need (at present) to write a corresponding "adapted" Gmsh file. The slowdown in I/O is an acceptable trade-off for the convenience it grants since a Gmsh-based workflow will be the default path for most Proteus users. As such, being able to easily convert the majority of existing and future cases to SCOREC-capable cases for mesh adaptivity would be very useful.

**Comment by bgranzow** [comment]
That's fine, I wasn't trying to discourage this feature, just wanted to let you know about its limitations.

Do users of Proteus with a Gmsh-based work flow interact solely through the Gmsh GUI? If not, partitioning could easily be achieved via SCOREC/core APIs after a serial conversion from Gmsh to mds, which could be made user-friendly enough if it's not at the GUI level...

**Comment by zhang-alvin** [comment]
Those are good points. The workflow isn't solely through the Gmsh GUI. After the mesh is generated, boundary conditions are defined in various separate files pertaining to different model equations. At the moment, I actually convert serial Gmsh meshes to the mds format before proceeding.  Some cases make use of the "physical classification"  feature that is available in Gmsh while others do not. 

After talking with the primary Proteus developer, it looks like the scalability issue of the Gmsh mesh is resolved by first converting the .msh file into a Triangle/Tetgen format and then loaded into the Proteus data structures.

It looks like the best way to handle the mesh in this case is to convert the Proteus mesh data structures into a SCOREC mesh in-memory, making the parallel Gmsh reader likely a non-issue on this end.

**Comment by bgranzow** [comment]
@zhang-alvin I'd like to make you aware of a geometric pre-processor for Gmsh that was written by @ibaned, called [Gmodel](https://github.com/ibaned/gmodel). This library allows you to generate Gmsh geometric models with C++ APIs, and also provides an API for output to the SCOREC .dmg geometric file format.

I've written some notes about my current Gmsh model+mesh generation workflow [here](https://scorec.rpi.edu/~granzb/goal/MeshGen.html), which may be useful. This workflow is currently file-based, but there is no reason it couldn't be made in-memory.

This comment has strayed a bit from the current GitHub issue at hand, but I feel like this info may be useful.

**Comment by zhang-alvin** [comment]
Thanks @bgranzow. These notes are very helpful and I will likely improve upon my current workflow  based on some of those ideas. 

Regarding the issue, I will no longer need the stated feature.
