### ISSUE TITLE
Develop into master

### ISSUE THREAD

**Issue by bgranzow** [SCOREC/core#96]
@seegyoung, it looks like develop-into-master has not been run in ~6 days even though the develop branch is green on the dashboard. The develop branch is now 31 commits ahead of master. Do you know why the merge isn't being run automatically with the nightly script?

http://my.cdash.org/index.php?project=SCOREC

**Comment by bgranzow** [comment]
Nevermind, it appears that everything is up to date! The nightly script doesn't merge develop into master unless there are new commits in develop (which is very reasonable behavior).  The 31 commits on develop that are ahead of the master branch are merge commits.

**Comment by ibaned** [comment]
Its actually the master branch that is ahead, that is where all the merge commits are. Thats one of the few downsides of this system. One could either periodically manually merge master into develop, or augment the script to also try merging back from master to develop as the last step.
