### ISSUE TITLE
Non-manifold gmi model creation from null

### ISSUE THREAD

**Issue by zhang-alvin** [SCOREC/core#99]
Assuming I am provided mesh information (region-to-vertex/face-to-vertex/edge-to-vertex adjacencies, equal-order classification info, vertex coordinates) but **not a discrete model**, I want to be able to recreate a mesh via apf along with its corresponding discrete model so that it can be passed into MeshAdapt. 

The only requirement for the model is that it can be non-manifold with an interior edge/face and that the mesh "adheres" to the model in that mesh regions cannot cross the interior edge/face and model vertices are necessarily mesh vertices.

Without the interior edge/face, I can use the apf::deriveMdsModel() function.

If I attempt to "create" an interior model edge (for a 2D case) using apf::Mesh2::findModelEntity() and have mesh entities classified on that edge, I receive an error like the following:

```
APF FAILED: apf::Verify: edge with 2 adjacent faces
centroid: (0.5, 0.75, 0)APF FAILED: apf::Verify: edge with 2 adjacent faces
centroid: (0.5, 0.75, 0)
based on the following:
 - edge is classified on a model edge
   which is adjacent to 0 model faces
   and is a manifold boundary edge
   making the edge "exposed" at the geometric boundary
we would expect the adjacent face count to be exactly 1
based on the following:
 - edge is classified on a model edge
   which is adjacent to 0 model faces
   and is a manifold boundary edge
   making the edge "exposed" at the geometric boundary
we would expect the adjacent face count to be exactly 1
```
Is there a way to specify that a gmi entity is non-manifold?

**Comment by ibaned** [comment]
Yea, the null model can't represent non-manifold geometry. What `apf::verify` is looking for is adjacencies in the model, so the model edge needs to be connected to those model faces by adjacencies. You can see that this is missing because it printed:

```
   which is adjacent to 0 model faces
```

I recommend using `agm` and `gmi_base` to build your model with adjacencies, see my answer to #100 as well.

**Comment by zhang-alvin** [comment]
Thanks. I am able to successfully create a non-manifold model by via agm/gmi_base if I specify the upward adjacency.
